info:
  description: Endpoints for system utilities. e.g.Health
  title: OnSched API Utility
  version: v1
  x-apisguru-categories:
    - collaboration
  x-logo:
    url: 'https://onsched.com/img/apple-touch-icon-57x57-precomposed.ico'
  x-origin:
    - format: openapi
      url: 'https://sandbox-api.onsched.com/swagger/utility/swagger.json'
      version: '3.0'
  x-providerName: onsched.com
  x-serviceName: utility
paths:
  /utility/v1/health/heartbeat:
    get:
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: string
      tags:
        - Health
  '/{planId}':
    get:
      parameters:
        - in: path
          name: planId
          required: true
          type: string
        - in: query
          name: locationId
          type: string
      responses:
        '200':
          description: Success
      tags:
        - StripePlans
security:
  - oauth2:
      - OnSchedApi
securityDefinitions:
  oauth2:
    flow: application
    scopes:
      OnSchedApi: Consumer and Setup Interface
    tokenUrl: 'https://sandbox-identity.onsched.com/connect/token'
    type: oauth2
swagger: '2.0'
x-components: {}

