definitions:
  AltLabel:
    additionalProperties: false
    properties:
      langIdent:
        type: string
        x-nullable: true
      mode:
        allOf:
          - $ref: '#/definitions/AltLabelMode'
      text:
        type: string
        x-nullable: true
    type: object
  AltLabelMode:
    enum:
      - 1
      - 2
    format: int32
    type: integer
  DataItem:
    additionalProperties: false
    properties:
      ident:
        type: string
        x-nullable: true
      parentIdent:
        allOf:
          - $ref: '#/definitions/ParentRef'
        x-nullable: true
      values:
        items:
          type: string
        type: array
        x-nullable: true
    type: object
  HierarchicalInterview:
    additionalProperties: false
    properties:
      dataItems:
        items:
          $ref: '#/definitions/DataItem'
        type: array
        x-nullable: true
      hierarchicalInterviews:
        items:
          $ref: '#/definitions/HierarchicalInterview'
        type: array
        x-nullable: true
      ident:
        type: string
        x-nullable: true
      level:
        allOf:
          - $ref: '#/definitions/Level'
        x-nullable: true
    type: object
  Hierarchy:
    additionalProperties: false
    properties:
      ident:
        type: string
        x-nullable: true
      metadata:
        allOf:
          - $ref: '#/definitions/SurveyMetadataBase'
        x-nullable: true
      parent:
        allOf:
          - $ref: '#/definitions/ParentDetails'
        x-nullable: true
    type: object
  Interview:
    additionalProperties: false
    properties:
      dataItems:
        items:
          $ref: '#/definitions/DataItem'
        type: array
        x-nullable: true
      hierarchicalInterviews:
        items:
          $ref: '#/definitions/HierarchicalInterview'
        type: array
        x-nullable: true
      ident:
        type: string
        x-nullable: true
    type: object
  Label:
    additionalProperties: false
    properties:
      altLabels:
        items:
          $ref: '#/definitions/AltLabel'
        type: array
        x-nullable: true
      text:
        type: string
        x-nullable: true
    type: object
  Language:
    additionalProperties: false
    properties:
      ident:
        type: string
        x-nullable: true
      name:
        type: string
        x-nullable: true
      subLanguages:
        items:
          $ref: '#/definitions/Language'
        type: array
        x-nullable: true
    type: object
  Level:
    additionalProperties: false
    properties:
      ident:
        type: string
        x-nullable: true
    type: object
  ParentDetails:
    additionalProperties: false
    properties:
      level:
        type: string
        x-nullable: true
      linkVar:
        type: string
        x-nullable: true
      ordered:
        type: boolean
    type: object
  ParentRef:
    additionalProperties: false
    properties:
      parentValueIdent:
        type: string
        x-nullable: true
      parentVariableIdent:
        type: string
        x-nullable: true
    type: object
  ParentType:
    enum:
      - 1
      - 2
      - 3
    format: int32
    type: integer
  SurveyDetail:
    additionalProperties: false
    properties:
      id:
        format: uuid
        type: string
      name:
        type: string
        x-nullable: true
      title:
        type: string
        x-nullable: true
    type: object
  SurveyMetadata:
    additionalProperties: false
    properties:
      hierarchies:
        items:
          $ref: '#/definitions/Hierarchy'
        type: array
        x-nullable: true
      interviewCount:
        format: int32
        type: integer
      languages:
        items:
          $ref: '#/definitions/Language'
        type: array
        x-nullable: true
      name:
        type: string
        x-nullable: true
      title:
        type: string
        x-nullable: true
      variables:
        items:
          $ref: '#/definitions/Variable'
        type: array
        x-nullable: true
    type: object
  SurveyMetadataBase:
    additionalProperties: false
    properties:
      interviewCount:
        format: int32
        type: integer
      languages:
        items:
          $ref: '#/definitions/Language'
        type: array
        x-nullable: true
      name:
        type: string
        x-nullable: true
      title:
        type: string
        x-nullable: true
      variables:
        items:
          $ref: '#/definitions/Variable'
        type: array
        x-nullable: true
    type: object
  UseType:
    enum:
      - 1
      - 2
      - 3
      - 4
    format: int32
    type: integer
  Value:
    additionalProperties: false
    properties:
      code:
        type: string
        x-nullable: true
      ident:
        type: string
        x-nullable: true
      label:
        allOf:
          - $ref: '#/definitions/Label'
        x-nullable: true
      score:
        format: int32
        type: integer
        x-nullable: true
    type: object
  ValueRange:
    additionalProperties: false
    properties:
      from:
        type: string
        x-nullable: true
      to:
        type: string
        x-nullable: true
    type: object
  Variable:
    additionalProperties: false
    properties:
      ident:
        type: string
        x-nullable: true
      label:
        allOf:
          - $ref: '#/definitions/Label'
        x-nullable: true
      maxResponses:
        format: int32
        type: integer
      name:
        type: string
        x-nullable: true
      parentType:
        allOf:
          - $ref: '#/definitions/ParentType'
      questions:
        items:
          $ref: '#/definitions/Variable'
        type: array
        x-nullable: true
      type:
        allOf:
          - $ref: '#/definitions/VariableType'
      use:
        allOf:
          - $ref: '#/definitions/UseType'
      variableValues:
        allOf:
          - $ref: '#/definitions/VariableValues'
        x-nullable: true
    type: object
  VariableType:
    enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    format: int32
    type: integer
  VariableValues:
    additionalProperties: false
    properties:
      range:
        allOf:
          - $ref: '#/definitions/ValueRange'
        x-nullable: true
      values:
        items:
          $ref: '#/definitions/Value'
        type: array
        x-nullable: true
    type: object
info:
  title: TSAPI
  version: v1
  x-apisguru-categories:
    - analytics
  x-logo:
    url: >-
      https://www.tsapi.net/wp-content/uploads/2019/11/cropped-icon-black-1-180x180.png
  x-origin:
    - format: openapi
      url: 'https://api.tsapi.net/swagger/v1/swagger.json'
      version: '3.0'
  x-providerName: tsapi.net
paths:
  /Surveys:
    get:
      parameters: []
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            items:
              $ref: '#/definitions/SurveyDetail'
            type: array
      summary: Returns a list of available Surveys
      tags:
        - Surveys
  '/Surveys/{surveyId}/Interviews':
    get:
      parameters:
        - format: uuid
          in: path
          name: surveyId
          required: true
          type: string
        - format: int32
          in: query
          name: start
          type: integer
        - format: int32
          in: query
          name: maxLength
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            items:
              $ref: '#/definitions/Interview'
            type: array
      summary: Fetches some interview records for a specific survey
      tags:
        - Surveys
  '/Surveys/{surveyId}/Metadata':
    get:
      parameters:
        - format: uuid
          in: path
          name: surveyId
          required: true
          type: string
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SurveyMetadata'
      summary: Fetches the metadata for a specific survey
      tags:
        - Surveys
security:
  - basic: []
securityDefinitions:
  basic:
    description: Basic Authorization header using the Bearer scheme.
    in: header
    name: Authorization
    type: apiKey
swagger: '2.0'
x-components: {}

