basePath: /v2
host: tv.api.pressassociation.io
info:
  description: >-
    Welcome to the API Reference Docs page for the Press Association TV API
    (v2).
  title: TV API
  version: '2.0'
  x-apisguru-categories:
    - media
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/PressAssociation/tv-api-v2-development-kit/master/swagger.yaml
      version: '3.0'
  x-providerName: pressassociation.io
paths:
  /asset:
    get:
      description: Return a collection of Assets.
      operationId: listAssets
      parameters:
        - default: '2015-05-05T00:00:00.000Z'
          description: Updated After
          in: query
          name: updatedAfter
          pattern: date-time
          required: false
          type: string
        - default: 100
          description: >-
            Limit the the number of items to be returned per page. For example:
            5.
          format: int32
          in: query
          name: limit
          required: false
          type: integer
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Asset Collection
      tags:
        - Asset
  '/asset/{assetId}':
    get:
      description: Return the content of the selected asset.
      operationId: getAsset
      parameters:
        - description: >-
            A asset ID filter for the schedule collection. This can be a
            reference to any type of asset i.e. movie, season, series or
            episode.
          in: path
          name: assetId
          required: true
          type: string
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Asset Detail
      tags:
        - Asset
  '/asset/{assetId}/contributor':
    get:
      description: Return the contributors of the selected asset.
      operationId: getAssetContributors
      parameters:
        - description: >-
            A asset ID filter for the schedule collection. This can be a
            reference to any type of asset i.e. movie, season, series or
            episode.
          in: path
          name: assetId
          required: true
          type: string
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Asset Contributors
      tags:
        - Asset
  /channel:
    get:
      description: >-
        If you are interested in a list of channels that have had there schedule
        updated you can filter by the following query params.
         - scheduleStart
         - scheduleEnd
         - scheduleUpdatedSince

        adding these query params will filter the channel collection to only
        return channels that have been updated within the given range,
        updatedSince stores the state of your previous call.


        Example Usage: Every 10 minutes get me the channels that have updated
        schedules for the next 2 weeks.


        /channel?platform={uuid}&scheduleStart={today}&scheduleEnd={today + 2
        weeks}&updatedSince={10 minutes ago}


        Also please note epg numbers are only exposed when a platform and region
        are passed to the query.
      operationId: listChannels
      parameters:
        - default: d3b26caa-8c7d-5f97-9eff-40fcf1a6f8d3
          description: >-
            The identifier for the selected platform. Multiple platforms can be
            passed to the API without a region Id. Passing multiple platforms
            without a region will not return epg numbers as these are linked to
            a platform and region.
          in: query
          name: platformId
          required: false
          type: string
        - default: afa4f624-da9b-54ce-b514-570345dbbdce
          description: The platform region ID for the channel selection.
          in: query
          name: regionId
          required: false
          type: string
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
        - default: '2018-09-15T00:00:00.000Z'
          description: >-
            Date of the Channel State to select, this will display channel names
            and attributes in the future or past.
          in: query
          name: date
          pattern: date
          required: false
          type: string
        - default: '2015-05-05T00:00:00.000Z'
          description: The Start Date for the schedule.
          in: query
          name: scheduleStart
          pattern: date-time
          required: false
          type: string
        - default: '2015-05-06T00:00:00.000Z'
          description: The End Date for the schedule.
          in: query
          name: scheduleEnd
          pattern: date-time
          required: false
          type: string
        - default: '2015-05-05T00:00:00.000Z'
          description: Schedule Updated Since
          in: query
          name: scheduleUpdatedSince
          pattern: date-time
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Channel Collection
      tags:
        - Channel
  '/channel/{channelId}':
    get:
      description: Return the content of the selected channel.
      operationId: getChannel
      parameters:
        - description: The identifier for the selected channel.
          in: path
          name: channelId
          required: true
          type: string
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Channel Detail
      tags:
        - Channel
  /contributor:
    get:
      description: Return a collection of Contributors.
      operationId: listContributor
      parameters:
        - default: '2015-05-05T00:00:00.000Z'
          description: Updated After
          in: query
          name: updatedAfter
          pattern: date-time
          required: false
          type: string
        - default: 100
          description: >-
            Limit the the number of items to be returned per page. For example:
            5.
          format: int32
          in: query
          name: limit
          required: false
          type: integer
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Contributor Collection
      tags:
        - Contributor
  '/contributor/{contributorId}':
    get:
      description: Return the content of the selected contributor.
      operationId: getContributor
      parameters:
        - description: Filter the schedule items by contributor ID
          in: path
          name: contributorId
          required: true
          type: string
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Contributor Detail
      tags:
        - Contributor
  /feature:
    get:
      description: Return a collection of Feature.
      operationId: listFeatures
      parameters:
        - default: netflix-monthly
          description: The namespace of the feature type.
          in: query
          name: type
          required: false
          type: string
        - default: '2018-09-15T00:00:00.000Z'
          description: Date of the collection of feature items.
          in: query
          name: date
          pattern: date
          required: false
          type: string
        - default: '2018-09-15T00:00:00.000Z'
          description: Start date for a range of features.
          in: query
          name: start
          pattern: date
          required: false
          type: string
        - default: '2018-10-15T00:00:00.000Z'
          description: End date for a range of features.
          in: query
          name: end
          pattern: date
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Feature Collection
      tags:
        - Feature
  /feature-type:
    get:
      description: Return a collection of Feature Types.
      operationId: listFeatureTypes
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Feature Type Collection
      tags:
        - Feature
  '/feature/{featureId}':
    get:
      description: Return the content of the selected feature.
      operationId: getFeature
      parameters:
        - description: The identifier for the selected feature.
          in: path
          name: featureId
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Feature Detail
      tags:
        - Feature
  /platform:
    get:
      description: Return a list of available platforms.
      operationId: listPlatforms
      parameters:
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Platform Collection
      tags:
        - Platform
  '/platform/{platformId}':
    get:
      description: Return the content of the selected platform.
      operationId: getPlatform
      parameters:
        - default: d3b26caa-8c7d-5f97-9eff-40fcf1a6f8d3
          description: The identifier for the selected platform.
          in: path
          name: platformId
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Platform Detail
      tags:
        - Platform
  '/platform/{platformId}/region':
    get:
      description: Return a list of regions for a platform.
      operationId: listPlatformRegions
      parameters:
        - default: d3b26caa-8c7d-5f97-9eff-40fcf1a6f8d3
          description: The identifier for the selected platform.
          in: path
          name: platformId
          required: true
          type: string
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Platform Region Collection
      tags:
        - Platform
  /schedule:
    get:
      description: >-
        The schedule endpoint produces a linear TV schedule for a given channel
        and date range.

         - The date range supplied must be no larger than 21 days.
         - If no end data is passed the API will default to start date + 24 hours.
      operationId: listSchedule
      parameters:
        - description: The identifier for the selected channel.
          in: query
          name: channelId
          required: true
          type: string
        - default: '2015-05-05T00:00:00.000Z'
          description: The Start Date for the schedule.
          in: query
          name: start
          pattern: date-time
          required: true
          type: string
        - default: '2015-05-06T00:00:00.000Z'
          description: The End Date for the schedule.
          in: query
          name: end
          pattern: date-time
          required: false
          type: string
        - default: true
          description: Flag to display Legacy and Provider Ids.
          in: query
          name: aliases
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
      security:
        - apikey: []
      summary: Schedule Collection
      tags:
        - Schedule
schemes:
  - https
securityDefinitions:
  apikey:
    in: header
    name: apikey
    type: apiKey
swagger: '2.0'
x-components: {}

