basePath: /
definitions:
  GoogleCloudResourcesettingsV1ListSettingsResponse:
    description: The response from ListSettings.
    properties:
      nextPageToken:
        description: Unused. A page token used to retrieve the next page.
        type: string
      settings:
        description: A list of settings that are available at the specified Cloud resource.
        items:
          $ref: '#/definitions/GoogleCloudResourcesettingsV1Setting'
        type: array
    type: object
  GoogleCloudResourcesettingsV1Setting:
    description: The schema for settings.
    properties:
      effectiveValue:
        $ref: '#/definitions/GoogleCloudResourcesettingsV1Value'
        description: >-
          Output only. The effective value of the setting at the given parent
          resource, evaluated based on the resource hierarchy The effective
          value evaluates to one of the following options, in this order. If an
          option is not valid or doesn't exist, then the next option is used: 1.
          The local setting value on the given resource: Setting.local_value 2.
          If one of the given resource's ancestors in the resource hierarchy
          have a local setting value, the local value at the nearest such
          ancestor. 3. The setting's default value:
          SettingMetadata.default_value 4. An empty value, defined as a `Value`
          with all fields unset. The data type of Value must always be
          consistent with the data type defined in Setting.metadata.
        readOnly: true
      etag:
        description: >-
          A fingerprint used for optimistic concurrency. See UpdateSetting for
          more details.
        type: string
      localValue:
        $ref: '#/definitions/GoogleCloudResourcesettingsV1Value'
        description: >-
          The configured value of the setting at the given parent resource,
          ignoring the resource hierarchy. The data type of Value must always be
          consistent with the data type defined in Setting.metadata.
      metadata:
        $ref: '#/definitions/GoogleCloudResourcesettingsV1SettingMetadata'
        description: >-
          Output only. Metadata about a setting which is not editable by the end
          user.
        readOnly: true
      name:
        description: >-
          The resource name of the setting. Must be in one of the following
          forms: * `projects/{project_number}/settings/{setting_name}` *
          `folders/{folder_id}/settings/{setting_name}` *
          `organizations/{organization_id}/settings/{setting_name}` For example,
          "/projects/123/settings/gcp-enableMyFeature"
        type: string
    type: object
  GoogleCloudResourcesettingsV1SettingMetadata:
    description: Metadata about a setting which is not editable by the end user.
    properties:
      dataType:
        description: The data type for this setting.
        enum:
          - DATA_TYPE_UNSPECIFIED
          - BOOLEAN
          - STRING
          - STRING_SET
          - ENUM_VALUE
          - DURATION_VALUE
          - STRING_MAP
        type: string
      defaultValue:
        $ref: '#/definitions/GoogleCloudResourcesettingsV1Value'
        description: >-
          The value provided by Setting.effective_value if no setting value is
          explicitly set. Note: not all settings have a default value.
      description:
        description: A detailed description of what this setting does.
        type: string
      displayName:
        description: The human readable name for this setting.
        type: string
      readOnly:
        description: >-
          A flag indicating that values of this setting cannot be modified. See
          documentation for the specific setting for updates and reasons.
        type: boolean
    type: object
  GoogleCloudResourcesettingsV1Value:
    description: The data in a setting value.
    properties:
      booleanValue:
        description: Defines this value as being a boolean value.
        type: boolean
      durationValue:
        description: Defines this value as being a Duration.
        format: google-duration
        type: string
      enumValue:
        $ref: '#/definitions/GoogleCloudResourcesettingsV1ValueEnumValue'
        description: Defines this value as being a Enum.
      stringMapValue:
        $ref: '#/definitions/GoogleCloudResourcesettingsV1ValueStringMap'
        description: Defines this value as being a StringMap.
      stringSetValue:
        $ref: '#/definitions/GoogleCloudResourcesettingsV1ValueStringSet'
        description: Defines this value as being a StringSet.
      stringValue:
        description: Defines this value as being a string value.
        type: string
    type: object
  GoogleCloudResourcesettingsV1ValueEnumValue:
    description: >-
      A enum value that can hold any enum type setting values. Each enum type is
      represented by a number, this representation is stored in the definitions.
    properties:
      value:
        description: The value of this enum
        type: string
    type: object
  GoogleCloudResourcesettingsV1ValueStringMap:
    description: >-
      A string->string map value that can hold a map of string keys to string
      values. The maximum length of each string is 200 characters and there can
      be a maximum of 50 key-value pairs in the map.
    properties:
      mappings:
        additionalProperties:
          type: string
        description: The key-value pairs in the map
        type: object
    type: object
  GoogleCloudResourcesettingsV1ValueStringSet:
    description: >-
      A string set value that can hold a set of strings. The maximum length of
      each string is 200 characters and there can be a maximum of 50 strings in
      the string set.
    properties:
      values:
        description: The strings in the set
        items:
          type: string
        type: array
    type: object
externalDocs:
  url: 'https://cloud.google.com/resource-manager/docs/resource-settings/overview'
host: resourcesettings.googleapis.com
info:
  contact:
    name: Google
    url: 'https://google.com'
    x-twitter: youtube
  description: >-
    The Resource Settings API allows users to control and modify the behavior of
    their GCP resources (e.g., VM, firewall, Project, etc.) across the Cloud
    Resource Hierarchy.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Resource Settings API
  version: v1
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: >-
      https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: openapi
      url: 'https://resourcesettings.googleapis.com/$discovery/rest?version=v1'
      version: '3.0'
  x-providerName: googleapis.com
  x-serviceName: resourcesettings
paths:
  '/v1/{name}':
    get:
      description: >-
        Returns a specified setting. Returns a `google.rpc.Status` with
        `google.rpc.Code.NOT_FOUND` if the setting does not exist.
      operationId: resourcesettings.projects.settings.get
      parameters:
        - description: >-
            Required. The name of the setting to get. See Setting for naming
            requirements.
          in: path
          name: name
          required: true
          type: string
        - description: The SettingView for this request.
          enum:
            - SETTING_VIEW_UNSPECIFIED
            - SETTING_VIEW_BASIC
            - SETTING_VIEW_EFFECTIVE_VALUE
            - SETTING_VIEW_LOCAL_VALUE
          in: query
          name: view
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/GoogleCloudResourcesettingsV1Setting'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
    parameters:
      - description: V1 error format.
        enum:
          - '1'
          - '2'
        in: query
        name: $.xgafv
        type: string
      - description: OAuth access token.
        in: query
        name: access_token
        type: string
      - description: Data format for response.
        enum:
          - json
          - media
          - proto
        in: query
        name: alt
        type: string
      - description: JSONP
        in: query
        name: callback
        type: string
      - description: Selector specifying which fields to include in a partial response.
        in: query
        name: fields
        type: string
      - description: >-
          API key. Your API key identifies your project and provides you with
          API access, quota, and reports. Required unless you provide an OAuth
          2.0 token.
        in: query
        name: key
        type: string
      - description: OAuth 2.0 token for the current user.
        in: query
        name: oauth_token
        type: string
      - description: Returns response with indentations and line breaks.
        in: query
        name: prettyPrint
        type: boolean
      - description: >-
          Available to use for quota purposes for server-side applications. Can
          be any arbitrary string assigned to a user, but should not exceed 40
          characters.
        in: query
        name: quotaUser
        type: string
      - description: 'Upload protocol for media (e.g. "raw", "multipart").'
        in: query
        name: upload_protocol
        type: string
      - description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
        in: query
        name: uploadType
        type: string
    patch:
      consumes:
        - application/json
      description: >-
        Updates a specified setting. Returns a `google.rpc.Status` with
        `google.rpc.Code.NOT_FOUND` if the setting does not exist. Returns a
        `google.rpc.Status` with `google.rpc.Code.FAILED_PRECONDITION` if the
        setting is flagged as read only. Returns a `google.rpc.Status` with
        `google.rpc.Code.ABORTED` if the etag supplied in the request does not
        match the persisted etag of the setting value. On success, the response
        will contain only `name`, `local_value` and `etag`. The `metadata` and
        `effective_value` cannot be updated through this API. Note: the supplied
        setting will perform a full overwrite of the `local_value` field.
      operationId: resourcesettings.projects.settings.patch
      parameters:
        - description: >-
            The resource name of the setting. Must be in one of the following
            forms: * `projects/{project_number}/settings/{setting_name}` *
            `folders/{folder_id}/settings/{setting_name}` *
            `organizations/{organization_id}/settings/{setting_name}` For
            example, "/projects/123/settings/gcp-enableMyFeature"
          in: path
          name: name
          required: true
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/GoogleCloudResourcesettingsV1Setting'
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/GoogleCloudResourcesettingsV1Setting'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
  '/v1/{parent}/settings':
    get:
      description: >-
        Lists all the settings that are available on the Cloud resource
        `parent`.
      operationId: resourcesettings.projects.settings.list
      parameters:
        - description: >-
            Required. The project, folder, or organization that is the parent
            resource for this setting. Must be in one of the following forms: *
            `projects/{project_number}` * `projects/{project_id}` *
            `folders/{folder_id}` * `organizations/{organization_id}`
          in: path
          name: parent
          required: true
          type: string
        - description: Unused. The size of the page to be returned.
          in: query
          name: pageSize
          type: integer
        - description: Unused. A page token used to retrieve the next page.
          in: query
          name: pageToken
          type: string
        - description: The SettingView for this request.
          enum:
            - SETTING_VIEW_UNSPECIFIED
            - SETTING_VIEW_BASIC
            - SETTING_VIEW_EFFECTIVE_VALUE
            - SETTING_VIEW_LOCAL_VALUE
          in: query
          name: view
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/GoogleCloudResourcesettingsV1ListSettingsResponse'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
    parameters:
      - description: V1 error format.
        enum:
          - '1'
          - '2'
        in: query
        name: $.xgafv
        type: string
      - description: OAuth access token.
        in: query
        name: access_token
        type: string
      - description: Data format for response.
        enum:
          - json
          - media
          - proto
        in: query
        name: alt
        type: string
      - description: JSONP
        in: query
        name: callback
        type: string
      - description: Selector specifying which fields to include in a partial response.
        in: query
        name: fields
        type: string
      - description: >-
          API key. Your API key identifies your project and provides you with
          API access, quota, and reports. Required unless you provide an OAuth
          2.0 token.
        in: query
        name: key
        type: string
      - description: OAuth 2.0 token for the current user.
        in: query
        name: oauth_token
        type: string
      - description: Returns response with indentations and line breaks.
        in: query
        name: prettyPrint
        type: boolean
      - description: >-
          Available to use for quota purposes for server-side applications. Can
          be any arbitrary string assigned to a user, but should not exceed 40
          characters.
        in: query
        name: quotaUser
        type: string
      - description: 'Upload protocol for media (e.g. "raw", "multipart").'
        in: query
        name: upload_protocol
        type: string
      - description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
        in: query
        name: uploadType
        type: string
schemes:
  - https
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': >-
        See, edit, configure, and delete your Google Cloud data and see the
        email address for your Google Account.
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authorizationCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': >-
        See, edit, configure, and delete your Google Cloud data and see the
        email address for your Google Account.
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
swagger: '2.0'
tags:
  - name: folders
  - name: organizations
  - name: projects
x-components:
  parameters:
    _.xgafv:
      description: V1 error format.
      enum:
        - '1'
        - '2'
      in: query
      name: $.xgafv
      type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      type: string
    alt:
      description: Data format for response.
      enum:
        - json
        - media
        - proto
      in: query
      name: alt
      type: string
    callback:
      description: JSONP
      in: query
      name: callback
      type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      type: string
    key:
      description: >-
        API key. Your API key identifies your project and provides you with API
        access, quota, and reports. Required unless you provide an OAuth 2.0
        token.
      in: query
      name: key
      type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      type: boolean
    quotaUser:
      description: >-
        Available to use for quota purposes for server-side applications. Can be
        any arbitrary string assigned to a user, but should not exceed 40
        characters.
      in: query
      name: quotaUser
      type: string
    uploadType:
      description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
      in: query
      name: uploadType
      type: string
    upload_protocol:
      description: 'Upload protocol for media (e.g. "raw", "multipart").'
      in: query
      name: upload_protocol
      type: string

