basePath: /
definitions:
  Arn:
    maxLength: 256
    pattern: 'arn:([a-z\d-]+):personalize:.*:.*:.+'
    type: string
  Date:
    format: date-time
    type: string
  Event:
    description: >-
      Represents user interaction event information sent using the
      <code>PutEvents</code> API.
    properties:
      eventId:
        allOf:
          - $ref: '#/definitions/StringType'
          - description: >-
              An ID associated with the event. If an event ID is not provided,
              Amazon Personalize generates a unique ID for the event. An event
              ID is not used as an input to the model. Amazon Personalize uses
              the event ID to distinquish unique events. Any subsequent events
              after the first with the same event ID are not used in model
              training.
      eventType:
        allOf:
          - $ref: '#/definitions/StringType'
          - description: >-
              The type of event, such as click or download. This property
              corresponds to the <code>EVENT_TYPE</code> field of your
              Interactions schema and depends on the types of events you are
              tracking.
      eventValue:
        allOf:
          - $ref: '#/definitions/FloatType'
          - description: >-
              The event value that corresponds to the <code>EVENT_VALUE</code>
              field of the Interactions schema.
      impression:
        allOf:
          - $ref: '#/definitions/Impression'
          - description: >-
              A list of item IDs that represents the sequence of items you have
              shown the user. For example, <code>["itemId1", "itemId2",
              "itemId3"]</code>.
      itemId:
        allOf:
          - $ref: '#/definitions/ItemId'
          - description: >-
              The item ID key that corresponds to the <code>ITEM_ID</code> field
              of the Interactions schema.
      properties:
        description: >-
          <p>A string map of event-specific data that you might choose to
          record. For example, if a user rates a movie on your site, other than
          movie ID (<code>itemId</code>) and rating (<code>eventValue</code>) ,
          you might also send the number of movie ratings made by the user.</p>
          <p>Each item in the map consists of a key-value pair. For example,</p>
          <p> <code>{"numberOfRatings": "12"}</code> </p> <p>The keys use camel
          case names that match the fields in the Interactions schema. In the
          above example, the <code>numberOfRatings</code> would match the
          'NUMBER_OF_RATINGS' field defined in the Interactions schema.</p>
      recommendationId:
        allOf:
          - $ref: '#/definitions/RecommendationId'
          - description: The ID of the recommendation.
      sentAt:
        allOf:
          - $ref: '#/definitions/Date'
          - description: >-
              The timestamp (in Unix time) on the client side when the event
              occurred.
    required:
      - eventType
      - sentAt
    type: object
  EventList:
    items:
      $ref: '#/definitions/Event'
    maxItems: 10
    minItems: 1
    type: array
  EventPropertiesJSON:
    maxLength: 1024
    minLength: 1
    type: string
  FloatType:
    format: float
    type: number
  Impression:
    items:
      $ref: '#/definitions/ItemId'
    maxItems: 25
    minItems: 1
    type: array
  InvalidInputException: {}
  Item:
    description: >-
      Represents item metadata added to an Items dataset using the
      <code>PutItems</code> API. For more information see <a
      href="https://docs.aws.amazon.com/personalize/latest/dg/importing-items.html">Importing
      Items Incrementally</a>. 
    properties:
      itemId:
        allOf:
          - $ref: '#/definitions/StringType'
          - description: The ID associated with the item.
      properties:
        description: >-
          <p>A string map of item-specific metadata. Each element in the map
          consists of a key-value pair. For example, <code>{"numberOfRatings":
          "12"}</code>.</p> <p>The keys use camel case names that match the
          fields in the schema for the Items dataset. In the previous example,
          the <code>numberOfRatings</code> matches the 'NUMBER_OF_RATINGS' field
          defined in the Items schema. For categorical string data, to include
          multiple categories for a single item, separate each category with a
          pipe separator (<code>|</code>). For example,
          <code>\"Horror|Action\"</code>.</p>
    required:
      - itemId
    type: object
  ItemId:
    maxLength: 256
    minLength: 1
    type: string
  ItemList:
    items:
      $ref: '#/definitions/Item'
    maxItems: 10
    minItems: 1
    type: array
  ItemProperties:
    maxLength: 24262
    minLength: 1
    type: string
  PutEventsRequest:
    properties:
      eventList:
        allOf:
          - $ref: '#/definitions/EventList'
          - description: A list of event data from the session.
      sessionId:
        allOf:
          - $ref: '#/definitions/StringType'
          - description: >-
              The session ID associated with the user's visit. Your application
              generates the sessionId when a user first visits your website or
              uses your application. Amazon Personalize uses the sessionId to
              associate events with the user before they log in. For more
              information, see <a
              href="https://docs.aws.amazon.com/personalize/latest/dg/recording-events.html">Recording
              Events</a>.
      trackingId:
        allOf:
          - $ref: '#/definitions/StringType'
          - description: >-
              The tracking ID for the event. The ID is generated by a call to
              the <a
              href="https://docs.aws.amazon.com/personalize/latest/dg/API_CreateEventTracker.html">CreateEventTracker</a>
              API.
      userId:
        allOf:
          - $ref: '#/definitions/UserId'
          - description: The user associated with the event.
    required:
      - trackingId
      - sessionId
      - eventList
    title: PutEventsRequest
    type: object
  PutItemsRequest:
    properties:
      datasetArn:
        allOf:
          - $ref: '#/definitions/Arn'
          - description: >-
              The Amazon Resource Name (ARN) of the Items dataset you are adding
              the item or items to.
      items:
        allOf:
          - $ref: '#/definitions/ItemList'
          - description: A list of item data.
    required:
      - datasetArn
      - items
    title: PutItemsRequest
    type: object
  PutUsersRequest:
    properties:
      datasetArn:
        allOf:
          - $ref: '#/definitions/Arn'
          - description: >-
              The Amazon Resource Name (ARN) of the Users dataset you are adding
              the user or users to.
      users:
        allOf:
          - $ref: '#/definitions/UserList'
          - description: A list of user data.
    required:
      - datasetArn
      - users
    title: PutUsersRequest
    type: object
  RecommendationId:
    maxLength: 40
    minLength: 1
    type: string
  ResourceInUseException: {}
  ResourceNotFoundException: {}
  StringType:
    maxLength: 256
    minLength: 1
    type: string
  User:
    description: >-
      Represents user metadata added to a Users dataset using the
      <code>PutUsers</code> API. For more information see <a
      href="https://docs.aws.amazon.com/personalize/latest/dg/importing-users.html">Importing
      Users Incrementally</a>.
    properties:
      properties:
        description: >-
          <p>A string map of user-specific metadata. Each element in the map
          consists of a key-value pair. For example,
          <code>{"numberOfVideosWatched": "45"}</code>.</p> <p>The keys use
          camel case names that match the fields in the schema for the Users
          dataset. In the previous example, the
          <code>numberOfVideosWatched</code> matches the
          'NUMBER_OF_VIDEOS_WATCHED' field defined in the Users schema. For
          categorical string data, to include multiple categories for a single
          user, separate each category with a pipe separator (<code>|</code>).
          For example, <code>\"Member|Frequent shopper\"</code>.</p>
      userId:
        allOf:
          - $ref: '#/definitions/StringType'
          - description: The ID associated with the user.
    required:
      - userId
    type: object
  UserId:
    maxLength: 256
    minLength: 1
    type: string
  UserList:
    items:
      $ref: '#/definitions/User'
    maxItems: 10
    minItems: 1
    type: array
  UserProperties:
    maxLength: 4096
    minLength: 1
    type: string
externalDocs:
  description: Amazon Web Services documentation
  url: 'https://docs.aws.amazon.com/personalize-events/'
host: personalize-events.us-east-1.amazonaws.com
info:
  contact:
    email: mike.ralphson@gmail.com
    name: Mike Ralphson
    url: 'https://github.com/mermade/aws2openapi'
    x-twitter: PermittedSoc
  description: >-
    Amazon Personalize can consume real-time user event data, such as
    <i>stream</i> or <i>click</i> data, and use it for model training either
    alone or combined with historical data. For more information see <a
    href="https://docs.aws.amazon.com/personalize/latest/dg/recording-events.html">Recording
    Events</a>.
  license:
    name: Apache 2.0 License
    url: 'http://www.apache.org/licenses/'
  termsOfService: 'https://aws.amazon.com/service-terms/'
  title: Amazon Personalize Events
  version: '2018-03-22'
  x-apiClientRegistration:
    url: >-
      https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-aws-signingName: personalize
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://twitter.com/awscloud/profile_image?size=original'
  x-origin:
    - contentType: application/json
      converter:
        url: 'https://github.com/mermade/aws2openapi'
        version: 1.0.0
      url: >-
        https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/personalize-events-2018-03-22.normal.json
      x-apisguru-driver: external
  x-preferred: true
  x-providerName: amazonaws.com
  x-release: v4
  x-serviceName: personalize-events
paths:
  /events:
    parameters:
      - in: header
        name: X-Amz-Content-Sha256
        required: false
        type: string
      - in: header
        name: X-Amz-Date
        required: false
        type: string
      - in: header
        name: X-Amz-Algorithm
        required: false
        type: string
      - in: header
        name: X-Amz-Credential
        required: false
        type: string
      - in: header
        name: X-Amz-Security-Token
        required: false
        type: string
      - in: header
        name: X-Amz-Signature
        required: false
        type: string
      - in: header
        name: X-Amz-SignedHeaders
        required: false
        type: string
    post:
      consumes:
        - application/json
      description: >-
        Records user interaction event data. For more information see <a
        href="https://docs.aws.amazon.com/personalize/latest/dg/recording-events.html">Recording
        Events</a>.
      operationId: PutEvents
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              eventList:
                description: A list of event data from the session.
                items:
                  $ref: '#/definitions/Event'
                maxItems: 10
                minItems: 1
                type: array
              sessionId:
                description: >-
                  The session ID associated with the user's visit. Your
                  application generates the sessionId when a user first visits
                  your website or uses your application. Amazon Personalize uses
                  the sessionId to associate events with the user before they
                  log in. For more information, see <a
                  href="https://docs.aws.amazon.com/personalize/latest/dg/recording-events.html">Recording
                  Events</a>.
                maxLength: 256
                minLength: 1
                type: string
              trackingId:
                description: >-
                  The tracking ID for the event. The ID is generated by a call
                  to the <a
                  href="https://docs.aws.amazon.com/personalize/latest/dg/API_CreateEventTracker.html">CreateEventTracker</a>
                  API.
                maxLength: 256
                minLength: 1
                type: string
              userId:
                description: The user associated with the event.
                maxLength: 256
                minLength: 1
                type: string
            required:
              - trackingId
              - sessionId
              - eventList
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '480':
          description: InvalidInputException
          schema:
            $ref: '#/definitions/InvalidInputException'
  /items:
    parameters:
      - in: header
        name: X-Amz-Content-Sha256
        required: false
        type: string
      - in: header
        name: X-Amz-Date
        required: false
        type: string
      - in: header
        name: X-Amz-Algorithm
        required: false
        type: string
      - in: header
        name: X-Amz-Credential
        required: false
        type: string
      - in: header
        name: X-Amz-Security-Token
        required: false
        type: string
      - in: header
        name: X-Amz-Signature
        required: false
        type: string
      - in: header
        name: X-Amz-SignedHeaders
        required: false
        type: string
    post:
      consumes:
        - application/json
      description: >-
        Adds one or more items to an Items dataset. For more information see <a
        href="https://docs.aws.amazon.com/personalize/latest/dg/importing-items.html">Importing
        Items Incrementally</a>. 
      operationId: PutItems
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              datasetArn:
                description: >-
                  The Amazon Resource Name (ARN) of the Items dataset you are
                  adding the item or items to.
                maxLength: 256
                pattern: 'arn:([a-z\d-]+):personalize:.*:.*:.+'
                type: string
              items:
                description: A list of item data.
                items:
                  $ref: '#/definitions/Item'
                maxItems: 10
                minItems: 1
                type: array
            required:
              - datasetArn
              - items
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '480':
          description: InvalidInputException
          schema:
            $ref: '#/definitions/InvalidInputException'
        '481':
          description: ResourceNotFoundException
          schema:
            $ref: '#/definitions/ResourceNotFoundException'
        '482':
          description: ResourceInUseException
          schema:
            $ref: '#/definitions/ResourceInUseException'
  /users:
    parameters:
      - in: header
        name: X-Amz-Content-Sha256
        required: false
        type: string
      - in: header
        name: X-Amz-Date
        required: false
        type: string
      - in: header
        name: X-Amz-Algorithm
        required: false
        type: string
      - in: header
        name: X-Amz-Credential
        required: false
        type: string
      - in: header
        name: X-Amz-Security-Token
        required: false
        type: string
      - in: header
        name: X-Amz-Signature
        required: false
        type: string
      - in: header
        name: X-Amz-SignedHeaders
        required: false
        type: string
    post:
      consumes:
        - application/json
      description: >-
        Adds one or more users to a Users dataset. For more information see <a
        href="https://docs.aws.amazon.com/personalize/latest/dg/importing-users.html">Importing
        Users Incrementally</a>.
      operationId: PutUsers
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              datasetArn:
                description: >-
                  The Amazon Resource Name (ARN) of the Users dataset you are
                  adding the user or users to.
                maxLength: 256
                pattern: 'arn:([a-z\d-]+):personalize:.*:.*:.+'
                type: string
              users:
                description: A list of user data.
                items:
                  $ref: '#/definitions/User'
                maxItems: 10
                minItems: 1
                type: array
            required:
              - datasetArn
              - users
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '480':
          description: InvalidInputException
          schema:
            $ref: '#/definitions/InvalidInputException'
        '481':
          description: ResourceNotFoundException
          schema:
            $ref: '#/definitions/ResourceNotFoundException'
        '482':
          description: ResourceInUseException
          schema:
            $ref: '#/definitions/ResourceInUseException'
schemes:
  - http
security:
  - hmac: []
securityDefinitions:
  hmac:
    description: Amazon Signature authorization v4
    in: header
    name: Authorization
    type: apiKey
    x-amazon-apigateway-authtype: awsSigv4
swagger: '2.0'
x-components:
  parameters:
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      type: string
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      type: string

