basePath: /
definitions:
  detections:
    items:
      properties:
        confidence:
          description: Confidence value
          example: 0.6
          format: float
          maximum: 1
          minimum: 0
          type: number
        language:
          description: Language code
          example: en
          type: string
      type: object
    type: array
  error-response:
    properties:
      error:
        description: Error message
        type: string
    type: object
  error-slow-down:
    properties:
      error:
        description: Reason for slow down
        type: string
    type: object
  frontend-settings:
    properties:
      charLimit:
        description: Character input limit for this language (-1 indicates no limit)
        type: integer
      frontendTimeout:
        description: Frontend translation timeout
        type: integer
      language:
        properties:
          source:
            properties:
              code:
                description: Language code
                type: string
              name:
                description: Human-readable language name (in English)
                type: string
            type: object
          target:
            properties:
              code:
                description: Language code
                type: string
              name:
                description: Human-readable language name (in English)
                type: string
            type: object
        type: object
    type: object
  languages:
    items:
      properties:
        code:
          description: Language code
          type: string
        name:
          description: Human-readable language name (in English)
          type: string
      type: object
    type: array
  translate:
    properties:
      translatedText:
        description: Translated text(s)
    type: object
host: libretranslate.local
info:
  title: LibreTranslate
  version: '1.2'
  x-apisguru-categories:
    - text
  x-origin:
    - format: openapi
      url: 'https://libretranslate.com/spec'
      version: '3.0'
  x-providerName: libretranslate.local
paths:
  /detect:
    post:
      consumes:
        - application/x-www-form-urlencoded
      description: ''
      parameters:
        - in: formData
          name: body
          type: string
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Detections
          schema:
            $ref: '#/definitions/detections'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error-response'
        '403':
          description: Banned
          schema:
            $ref: '#/definitions/error-response'
        '429':
          description: Slow down
          schema:
            $ref: '#/definitions/error-slow-down'
        '500':
          description: Detection error
          schema:
            $ref: '#/definitions/error-response'
      summary: Detect the language of a single text
      tags:
        - translate
  /frontend/settings:
    get:
      description: ''
      parameters: []
      produces:
        - application/octet-stream
      responses:
        '200':
          description: frontend settings
          schema:
            $ref: '#/definitions/frontend-settings'
      summary: Retrieve frontend specific settings
      tags:
        - frontend
  /languages:
    get:
      description: ''
      parameters: []
      produces:
        - application/octet-stream
      responses:
        '200':
          description: List of languages
          schema:
            $ref: '#/definitions/languages'
        '429':
          description: Slow down
          schema:
            $ref: '#/definitions/error-slow-down'
      summary: Retrieve list of supported languages
      tags:
        - translate
    post:
      description: ''
      parameters: []
      produces:
        - application/octet-stream
      responses:
        '200':
          description: List of languages
          schema:
            $ref: '#/definitions/languages'
        '429':
          description: Slow down
          schema:
            $ref: '#/definitions/error-slow-down'
      summary: Retrieve list of supported languages
      tags:
        - translate
  /translate:
    post:
      consumes:
        - application/x-www-form-urlencoded
      description: ''
      parameters:
        - in: formData
          name: body
          type: string
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Translated text
          schema:
            $ref: '#/definitions/translate'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error-response'
        '403':
          description: Banned
          schema:
            $ref: '#/definitions/error-response'
        '429':
          description: Slow down
          schema:
            $ref: '#/definitions/error-slow-down'
        '500':
          description: Translation error
          schema:
            $ref: '#/definitions/error-response'
      summary: Translate text from a language to another
      tags:
        - translate
schemes:
  - http
swagger: '2.0'
x-components:
  requestBodies:
    postDetect:
      content:
        application/x-www-form-urlencoded:
          schema:
            example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
            type: string

