basePath: /
definitions:
  apply_yara_rule:
    properties:
      error_message:
        description: 'error message, if YARA failed'
        type: string
      is_success:
        description: is operation success
        type: boolean
      matched_yara_rules:
        description: matched YARA rules
        items:
          items:
            description: Yara rule meta data section
            properties:
              rule:
                description: matched rule
                type: string
              string_information:
                description: string which matched during the scanning
                items:
                  type: string
                type: array
            required:
              - rule
              - string_information
            type: object
          type: array
        type: array
      yara_command:
        description: Yara command executed
        type: string
    required:
      - yara_command
      - is_success
  error:
    properties:
      message:
        type: string
      status:
        type: integer
    required:
      - status
      - message
    type: object
  yara:
    properties:
      meta:
        description: Yara rule meta data section
        properties:
          date:
            description: Date of the YARA rule created
            type: string
          md5sum:
            description: MD5 check sum
            type: string
          sha256sum:
            description: SHA 256 check sum
            type: string
          sha512sum:
            description: SHA 512 check sum
            type: string
        required:
          - date
          - md5sum
          - sha256sum
          - sha512sum
        type: object
      name:
        description: Yara rule name
        type: string
      strings:
        description: Yara rule string section
        items:
          items:
            type: string
          maxItems: 2
          minItems: 2
          type: array
        type: array
    required:
      - name
      - meta
      - strings
host: restful4up.local
info:
  description: RESTful API 4 Unipacker
  title: RESTful4Up
  version: 1.0.0
  x-apisguru-categories:
    - developer_tools
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/rpgeeganage/restful4up/master/app/spec/api.yml
      version: '3.0'
  x-providerName: restful4up.local
paths:
  /apply-yara-rules:
    post:
      consumes:
        - multipart/form-data
      description: apply given YARA rules to the given executable. (upto 10 rules)
      operationId: applyYaraRules
      parameters:
        - in: formData
          name: body
          required: true
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Yara rules
          schema:
            properties:
              result:
                $ref: '#/definitions/apply_yara_rule'
        '400':
          description: request error
          schema:
            $ref: '#/definitions/error'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/error'
  /clean:
    head:
      description: clean up the uploaded files
      operationId: clean
      parameters: []
      produces:
        - application/octet-stream
      responses:
        '204':
          description: Ok
        '500':
          description: server error
          schema:
            $ref: '#/definitions/error'
  /emulation-output:
    post:
      consumes:
        - multipart/form-data
      description: try to get the emulation output after unpacking the file
      operationId: emulationOutput
      parameters:
        - in: formData
          name: body
          required: true
      produces:
        - application/octet-stream
      responses:
        '200':
          description: emulation output after unpacking the file
          schema:
            properties:
              output:
                items:
                  type: string
                type: array
            required:
              - output
        '400':
          description: request error
          schema:
            $ref: '#/definitions/error'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/error'
  /generate-partial-yara-rules:
    post:
      consumes:
        - multipart/form-data
      description: >-
        generate partial YARA rules for give executable. (Rule without the
        condition section)
      operationId: generatePartialYaraRule
      parameters:
        - in: formData
          name: body
          required: true
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Yara rules
          schema:
            properties:
              rule:
                $ref: '#/definitions/yara'
        '400':
          description: request error
          schema:
            $ref: '#/definitions/error'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/error'
  /unpack:
    post:
      consumes:
        - multipart/form-data
      description: try to unpack the given file
      operationId: unpack
      parameters:
        - in: formData
          name: body
          required: true
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Ok
          schema:
            format: binary
            type: string
        '400':
          description: request error
          schema:
            $ref: '#/definitions/error'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/error'
schemes:
  - http
swagger: '2.0'
x-components: {}

