basePath: /customvision/v2.0/Prediction
definitions:
  BoundingBox:
    properties:
      height:
        format: float
        nullable: false
        type: number
      left:
        format: float
        nullable: false
        type: number
      top:
        format: float
        nullable: false
        type: number
      width:
        format: float
        nullable: false
        type: number
    type: object
    x-nullable: true
  ImagePrediction:
    properties:
      created:
        format: date-time
        nullable: false
        readOnly: true
        type: string
      id:
        format: uuid
        nullable: false
        readOnly: true
        type: string
      iteration:
        format: uuid
        nullable: false
        readOnly: true
        type: string
      predictions:
        items:
          $ref: '#/definitions/Prediction'
        readOnly: true
        type: array
        x-nullable: true
      project:
        format: uuid
        nullable: false
        readOnly: true
        type: string
    type: object
    x-nullable: true
  ImageUrl:
    properties:
      url:
        type: string
        x-nullable: true
    type: object
    x-nullable: true
  Prediction:
    properties:
      boundingBox:
        $ref: '#/definitions/BoundingBox'
      probability:
        format: float
        nullable: false
        readOnly: true
        type: number
      tagId:
        format: uuid
        nullable: false
        readOnly: true
        type: string
      tagName:
        readOnly: true
        type: string
        x-nullable: true
    type: object
    x-nullable: true
host: southcentralus.api.cognitive.microsoft.com
info:
  contact:
    x-twitter: microsoft
  title: Custom Vision Prediction Client
  version: '2.0'
  x-apisguru-categories:
    - developer_tools
    - cloud
  x-logo:
    url: 'https://twitter.com/microsoft/profile_image?size=original'
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/CustomVision/Prediction/stable/v2.0/Prediction.json
      version: '3.0'
  x-preferred: false
  x-providerName: microsoft.com
  x-serviceName: cognitiveservices-Prediction
  x-tags:
    - Microsoft
paths:
  '/{projectId}/image':
    post:
      consumes:
        - multipart/form-data
      operationId: PredictImage
      parameters:
        - description: The project id
          examples:
            Successful PredictImage request:
              value: 64b822c5-8082-4b36-a426-27225f4aa18c
          format: uuid
          in: path
          name: projectId
          required: true
          type: string
          x-nullable: false
        - description: "Optional. Specifies the id of a particular iteration to evaluate against.\r\n            The default iteration for the project will be used when not specified"
          examples:
            Successful PredictImage request:
              value: fe1e83c4-6f50-4899-9544-6bb08cf0e15a
          format: uuid
          in: query
          name: iterationId
          required: false
          type: string
          x-nullable: true
        - description: Optional. Specifies the name of application using the endpoint
          in: query
          name: application
          required: false
          type: string
          x-nullable: true
        - examples:
            Successful PredictImage request:
              value: '{API Key}'
            Successful PredictImageUrl request:
              value: '{API Key}'
            Successful PredictImageUrlWithNoStore request:
              value: '{API Key}'
            Successful PredictImageWithNoStore request:
              value: '{API Key}'
          in: header
          name: Prediction-Key
          required: true
          type: string
          x-ms-client-name: ApiKey
          x-ms-parameter-location: client
        - format: binary
          in: formData
          name: imageData
          required: true
          type: string
      produces:
        - application/json
        - application/xml
        - text/json
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ImagePrediction'
      summary: Predict an image and saves the result
      tags:
        - ImagePredictionApi
  '/{projectId}/image/nostore':
    post:
      consumes:
        - multipart/form-data
      operationId: PredictImageWithNoStore
      parameters:
        - description: The project id
          examples:
            Successful PredictImageWithNoStore request:
              value: 64b822c5-8082-4b36-a426-27225f4aa18c
          format: uuid
          in: path
          name: projectId
          required: true
          type: string
          x-nullable: false
        - description: "Optional. Specifies the id of a particular iteration to evaluate against.\r\n            The default iteration for the project will be used when not specified"
          examples:
            Successful PredictImageWithNoStore request:
              value: fe1e83c4-6f50-4899-9544-6bb08cf0e15a
          format: uuid
          in: query
          name: iterationId
          required: false
          type: string
          x-nullable: true
        - description: Optional. Specifies the name of application using the endpoint
          in: query
          name: application
          required: false
          type: string
          x-nullable: true
        - examples:
            Successful PredictImage request:
              value: '{API Key}'
            Successful PredictImageUrl request:
              value: '{API Key}'
            Successful PredictImageUrlWithNoStore request:
              value: '{API Key}'
            Successful PredictImageWithNoStore request:
              value: '{API Key}'
          in: header
          name: Prediction-Key
          required: true
          type: string
          x-ms-client-name: ApiKey
          x-ms-parameter-location: client
        - format: binary
          in: formData
          name: imageData
          required: true
          type: string
      produces:
        - application/json
        - application/xml
        - text/json
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ImagePrediction'
      summary: Predict an image without saving the result
      tags:
        - ImagePredictionApi
  '/{projectId}/url':
    post:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
        - application/xml
        - text/json
        - text/xml
      operationId: PredictImageUrl
      parameters:
        - description: The project id
          examples:
            Successful PredictImageUrl request:
              value: 64b822c5-8082-4b36-a426-27225f4aa18c
          format: uuid
          in: path
          name: projectId
          required: true
          type: string
          x-nullable: false
        - description: "Optional. Specifies the id of a particular iteration to evaluate against.\r\n            The default iteration for the project will be used when not specified"
          examples:
            Successful PredictImageUrl request:
              value: fe1e83c4-6f50-4899-9544-6bb08cf0e15a
          format: uuid
          in: query
          name: iterationId
          required: false
          type: string
          x-nullable: true
        - description: Optional. Specifies the name of application using the endpoint
          in: query
          name: application
          required: false
          type: string
          x-nullable: true
        - examples:
            Successful PredictImage request:
              value: '{API Key}'
            Successful PredictImageUrl request:
              value: '{API Key}'
            Successful PredictImageUrlWithNoStore request:
              value: '{API Key}'
            Successful PredictImageWithNoStore request:
              value: '{API Key}'
          in: header
          name: Prediction-Key
          required: true
          type: string
          x-ms-client-name: ApiKey
          x-ms-parameter-location: client
        - description: >-
            An {Iris.Web.Api.Models.ImageUrl} that contains the url of the image
            to be evaluated
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ImageUrl'
      produces:
        - application/json
        - application/xml
        - text/json
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ImagePrediction'
      summary: Predict an image url and saves the result
      tags:
        - ImagePredictionApi
  '/{projectId}/url/nostore':
    post:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
        - application/xml
        - text/json
        - text/xml
      operationId: PredictImageUrlWithNoStore
      parameters:
        - description: The project id
          examples:
            Successful PredictImageUrlWithNoStore request:
              value: 64b822c5-8082-4b36-a426-27225f4aa18c
          format: uuid
          in: path
          name: projectId
          required: true
          type: string
          x-nullable: false
        - description: "Optional. Specifies the id of a particular iteration to evaluate against.\r\n            The default iteration for the project will be used when not specified"
          examples:
            Successful PredictImageUrlWithNoStore request:
              value: fe1e83c4-6f50-4899-9544-6bb08cf0e15a
          format: uuid
          in: query
          name: iterationId
          required: false
          type: string
          x-nullable: true
        - description: Optional. Specifies the name of application using the endpoint
          in: query
          name: application
          required: false
          type: string
          x-nullable: true
        - examples:
            Successful PredictImage request:
              value: '{API Key}'
            Successful PredictImageUrl request:
              value: '{API Key}'
            Successful PredictImageUrlWithNoStore request:
              value: '{API Key}'
            Successful PredictImageWithNoStore request:
              value: '{API Key}'
          in: header
          name: Prediction-Key
          required: true
          type: string
          x-ms-client-name: ApiKey
          x-ms-parameter-location: client
        - description: >-
            An {Iris.Web.Api.Models.ImageUrl} that contains the url of the image
            to be evaluated
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ImageUrl'
      produces:
        - application/json
        - application/xml
        - text/json
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ImagePrediction'
      summary: Predict an image url without saving the result
      tags:
        - ImagePredictionApi
schemes:
  - https
swagger: '2.0'
x-components:
  examples:
    Successful_PredictImageUrlWithNoStore_request:
      value:
        created: '2017-12-19T14:21:41.678Z'
        id: 951098b2-9b69-427b-bddb-d5cb618874e3
        iteration: fe1e83c4-6f50-4899-9544-6bb08cf0e15a
        predictions:
          - probability: 0.05149666
            tagId: e31ff107-5505-4753-be42-b369b21b026c
            tagName: Hemlock
          - probability: 0.000193528482
            tagId: 349d72ac-0948-4d51-b1e4-c14a1f9b848a
            tagName: Japanese Cherry
        project: 64b822c5-8082-4b36-a426-27225f4aa18c
    Successful_PredictImageUrl_request:
      value:
        created: '2017-12-19T14:21:41.678Z'
        id: 951098b2-9b69-427b-bddb-d5cb618874e3
        iteration: fe1e83c4-6f50-4899-9544-6bb08cf0e15a
        predictions:
          - probability: 0.05149666
            tagId: e31ff107-5505-4753-be42-b369b21b026c
            tagName: Hemlock
          - probability: 0.000193528482
            tagId: 349d72ac-0948-4d51-b1e4-c14a1f9b848a
            tagName: Japanese Cherry
        project: 64b822c5-8082-4b36-a426-27225f4aa18c
    Successful_PredictImageWithNoStore_request:
      value:
        created: '2017-12-19T14:21:41.678Z'
        id: 951098b2-9b69-427b-bddb-d5cb618874e3
        iteration: fe1e83c4-6f50-4899-9544-6bb08cf0e15a
        predictions:
          - probability: 0.05149666
            tagId: e31ff107-5505-4753-be42-b369b21b026c
            tagName: Hemlock
          - probability: 0.000193528482
            tagId: 349d72ac-0948-4d51-b1e4-c14a1f9b848a
            tagName: Japanese Cherry
        project: 64b822c5-8082-4b36-a426-27225f4aa18c
    Successful_PredictImage_request:
      value:
        created: '2017-12-19T14:21:41.678Z'
        id: 951098b2-9b69-427b-bddb-d5cb618874e3
        iteration: fe1e83c4-6f50-4899-9544-6bb08cf0e15a
        predictions:
          - probability: 0.05149666
            tagId: e31ff107-5505-4753-be42-b369b21b026c
            tagName: Hemlock
          - probability: 0.000193528482
            tagId: 349d72ac-0948-4d51-b1e4-c14a1f9b848a
            tagName: Japanese Cherry
        project: 64b822c5-8082-4b36-a426-27225f4aa18c
  parameters:
    ApiKey:
      examples:
        Successful PredictImage request:
          value: '{API Key}'
        Successful PredictImageUrl request:
          value: '{API Key}'
        Successful PredictImageUrlWithNoStore request:
          value: '{API Key}'
        Successful PredictImageWithNoStore request:
          value: '{API Key}'
      in: header
      name: Prediction-Key
      required: true
      type: string
      x-ms-client-name: ApiKey
      x-ms-parameter-location: client
    Endpoint:
      description: Supported Cognitive Services endpoints
      in: path
      name: Endpoint
      required: true
      schema:
        type: string
      x-ms-parameter-location: client
      x-ms-skip-url-encoding: true
  requestBodies:
    ImageUrl:
      content:
        application/json:
          schema:
            $ref: '#/definitions/ImageUrl'
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/definitions/ImageUrl'
        application/xml:
          schema:
            $ref: '#/definitions/ImageUrl'
        text/json:
          schema:
            $ref: '#/definitions/ImageUrl'
        text/xml:
          schema:
            $ref: '#/definitions/ImageUrl'
      description: >-
        An {Iris.Web.Api.Models.ImageUrl} that contains the url of the image to
        be evaluated
      required: true
    PredictImage:
      content:
        multipart/form-data:
          schema:
            properties:
              imageData:
                format: binary
                type: string
            required:
              - imageData
            type: object
      required: true

