basePath: /api.ote-godaddy.com
definitions:
  AftermarketListingAction:
    properties:
      listingActionId:
        description: Action Id
        type: integer
    required:
      - listingActionId
  AftermarketListingExpiryCreate:
    properties:
      domain:
        description: Domain name
        type: string
      expiresAt:
        description: Date when the domain expires
        format: iso-datetime
        type: string
      losingRegistrarId:
        default: 1
        description: Losing registrar id for the domain
        minimum: 1
        type: integer
      pageViewsMonthly:
        description: Monthly traffic page view for the domain
        type: integer
      revenueMonthly:
        description: Monthly parking revenue (in USD micro unit) for the domain
        type: integer
    required:
      - domain
      - expiresAt
      - losingRegistrarId
  Error:
    properties:
      code:
        description: >-
          Short identifier for the error, suitable for indicating the specific
          error within client code
        format: constant
        type: string
      fields:
        description: 'List of the specific fields, and the errors found with their contents'
        items:
          $ref: '#/definitions/ErrorField'
        type: array
      message:
        description: 'Human-readable, English description of the error'
        type: string
    required:
      - code
  ErrorField:
    properties:
      code:
        description: >-
          Short identifier for the error, suitable for indicating the specific
          error within client code
        format: constant
        type: string
      message:
        description: >-
          Human-readable, English description of the problem with the contents
          of the field
        type: string
      path:
        description: >-
          <ul>

          <li style='margin-left: 12px;'>JSONPath referring to a field
          containing an error</li>

          <strong style='margin-left: 12px;'>OR</strong>

          <li style='margin-left: 12px;'>JSONPath referring to a field that
          refers to an object containing an error, with more detail in
          `pathRelated`</li>

          </ul>
        format: json-path
        type: string
      pathRelated:
        description: >-
          JSONPath referring to a field containing an error, which is referenced
          by `path`
        format: json-path
        type: string
    required:
      - path
      - code
  ErrorLimit:
    properties:
      code:
        description: >-
          Short identifier for the error, suitable for indicating the specific
          error within client code
        format: constant
        type: string
      fields:
        description: 'List of the specific fields, and the errors found with their contents'
        items:
          $ref: '#/definitions/ErrorField'
        type: array
      message:
        description: 'Human-readable, English description of the error'
        type: string
      retryAfterSec:
        description: Number of seconds to wait before attempting a similar request
        format: integer-positive
        type: integer
    required:
      - retryAfterSec
      - code
  expiry:
    properties:
      id:
        format: double
        type: number
info:
  title: ''
  version: 1.0.0
  x-apisguru-categories:
    - hosting
  x-origin:
    - format: swagger
      url: 'https://developer.godaddy.com/swagger/swagger_aftermarket.json'
      version: '2.0'
  x-providerName: ote-godaddy.com
  x-serviceName: aftermarket
paths:
  /v1/aftermarket/listings:
    delete:
      operationId: deleteListings
      parameters:
        - collectionFormat: csv
          description: A comma separated list of domain names
          in: query
          items:
            type: string
          name: domains
          required: true
          type: array
      produces:
        - application/javascript
        - application/json
        - application/xml
        - text/javascript
        - text/xml
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/AftermarketListingAction'
        '400':
          description: Request was malformed
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Authentication info not sent or invalid
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Authenticated user is not allowed access
          schema:
            $ref: '#/definitions/Error'
        '422':
          description: "\tRequired parameters must be specified in correct format"
          schema:
            $ref: '#/definitions/Error'
        '429':
          description: Too many requests received within interval
          schema:
            $ref: '#/definitions/ErrorLimit'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      summary: Remove listings from GoDaddy Auction
      tags:
        - v1
  /v1/aftermarket/listings/expiry:
    post:
      consumes:
        - application/json
        - application/xml
        - text/xml
      operationId: addExpiryListings
      parameters:
        - description: An array of expiry listings to be loaded
          in: body
          name: body
          required: true
          schema:
            items:
              $ref: '#/definitions/AftermarketListingExpiryCreate'
            type: array
      produces:
        - application/javascript
        - application/json
        - application/xml
        - text/javascript
        - text/xml
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/AftermarketListingAction'
        '400':
          description: Request was malformed
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Authentication info not sent or invalid
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Authenticated user is not allowed access
          schema:
            $ref: '#/definitions/Error'
        '422':
          description: >-
            Required parameters must be specified in correct format<br>Too many
            Listings provided
          schema:
            $ref: '#/definitions/Error'
        '429':
          description: Too many requests received within interval
          schema:
            $ref: '#/definitions/ErrorLimit'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      summary: Add expiry listings into GoDaddy Auction
      tags:
        - v1
swagger: '2.0'
tags:
  - description: ''
    name: v1
x-components: {}

