basePath: /
host: api.math.tools
info:
  description: >
    All about Numbers. REST access with json/xml/jsonp result support. Below is
    the documentation for the Numbers API. You can try them out right here. Find
    more information and subscribe at
    [math.tools](https://math.tools/api/numbers/)  
  title: Numbers API
  version: '1.5'
  x-apisguru-categories:
    - open_data
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://math.tools/branding/blackboard_small.png'
  x-origin:
    - converter:
        url: 'https://github.com/mermade/oas-kit'
        version: 7.0.4
      format: openapi
      url: 'https://api.math.tools/yaml/math.tools.numbers.openapi.yaml'
      version: '3.0'
  x-providerName: math.tools
paths:
  /numbers/base:
    get:
      description: Convert a given number from one base to another base
      parameters:
        - description: Number to convert to the target base
          format: integer
          in: query
          name: number
          required: true
          type: integer
        - description: Base of the supplied number (Optional base 10 assumed by default)
          format: integer
          in: query
          name: from
          required: false
          type: integer
        - description: Target base to convert to
          format: integer
          in: query
          name: to
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Base Conversion
  /numbers/base/binary:
    get:
      description: Convert a given number to binary
      parameters:
        - description: Number to convert to binary
          format: integer
          in: query
          name: number
          required: true
          type: integer
        - description: Base of the supplied number (Optional base 10 assumed by default)
          format: integer
          in: query
          name: from
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Base Conversion
  /numbers/base/hex:
    get:
      description: Convert a given number to hexadecimal
      parameters:
        - description: Number to convert to hex
          format: integer
          in: query
          name: number
          required: true
          type: integer
        - description: Base of the supplied number (Optional base 10 assumed by default)
          format: integer
          in: query
          name: from
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Base Conversion
  /numbers/base/octal:
    get:
      description: Convert a given number to octal
      parameters:
        - description: Number to convert to octal
          format: integer
          in: query
          name: number
          required: true
          type: integer
        - description: Base of the supplied number (Optional base 10 assumed by default)
          format: integer
          in: query
          name: from
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Base Conversion
  /numbers/cardinal:
    get:
      description: Get the cardinal of the given number
      parameters:
        - description: Number value
          format: integer
          in: query
          name: number
          required: false
          type: integer
        - description: Language to use
          format: string
          in: query
          name: language
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Spell
  /numbers/currency:
    get:
      description: Spells out the number as a currency
      parameters:
        - description: Number to spell
          format: integer
          in: query
          name: number
          required: false
          type: integer
        - description: Language to use
          format: string
          in: query
          name: language
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Spell
  /numbers/fact:
    get:
      description: Get a random fact about a number
      parameters:
        - description: Number value
          format: integer
          in: query
          name: number
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Facts
  /numbers/is-cube:
    get:
      description: Checks whether a given number is a cube number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Checks
  /numbers/is-palindrome:
    get:
      description: Checks whether a given number is a palindrome number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Checks
  /numbers/is-square:
    get:
      description: Checks whether a given number is a square number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Checks
  /numbers/is-triangle:
    get:
      description: Checks whether a given number is a triangle number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Checks
  /numbers/nod:
    get:
      description: Get the number of the day for current day
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number of the day
  /numbers/numeral/chinese:
    get:
      description: Convert base 10 representation of a given number to chinese numeral.
      parameters:
        - description: Number to convert
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Systems Conversion
  /numbers/numeral/egyptian:
    get:
      description: Convert base 10 representation of a given number to egyptian numeral.
      parameters:
        - description: Number to convert
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Systems Conversion
  /numbers/numeral/roman:
    get:
      description: Convert base 10 representation of a given number to roman numeral.
      parameters:
        - description: Number to convert
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Systems Conversion
  /numbers/ordinal:
    get:
      description: Get the ordinal of the given number
      parameters:
        - description: Number value
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Spell
  /numbers/pi:
    get:
      description: Get digits of pi (Ï€)
      parameters:
        - description: Optional start position
          format: integer
          in: query
          name: from
          required: false
          type: integer
        - description: Optional start position
          format: integer
          in: query
          name: to
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - PI
  /numbers/prime/factors:
    get:
      description: Get the prime factors of a given number.
      parameters:
        - description: Number to get the factors
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Prime
  /numbers/prime/is-fermat-prime:
    get:
      description: Checks whether a given number is a known fermat prime number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Prime
        - Number Checks
  /numbers/prime/is-fibonacci-prime:
    get:
      description: Checks whether a given number is a known fibonacci prime number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Prime
        - Number Checks
  /numbers/prime/is-mersenne-prime:
    get:
      description: Checks whether a given number is a known mersenne prime number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Prime
        - Number Checks
  /numbers/prime/is-partition-prime:
    get:
      description: Checks whether a given number is a known partition prime number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Prime
        - Number Checks
  /numbers/prime/is-pell-prime:
    get:
      description: Checks whether a given number is a known pell prime number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Prime
        - Number Checks
  /numbers/prime/is-perfect:
    get:
      description: Checks whether a given number is a perfect number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Prime
        - Number Checks
  /numbers/prime/is-prime:
    get:
      description: Checks whether a given number is a known prime number or not.
      parameters:
        - description: Number to check
          format: integer
          in: query
          name: number
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Prime
        - Number Checks
  /numbers/random:
    get:
      description: Generate random number(s)
      parameters:
        - description: Minimum Number value in the range
          format: integer
          in: query
          name: min
          required: false
          type: integer
        - description: Maximum Number value
          format: integer
          in: query
          name: max
          required: false
          type: integer
        - description: Total number of random numbers to generate. Defaults to 1
          format: integer
          in: query
          name: total
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Mathtools-Api-Secret: []
      tags:
        - Number Generation
schemes:
  - https
securityDefinitions:
  X-Mathtools-Api-Secret:
    in: header
    name: X-Mathtools-Api-Secret
    type: apiKey
swagger: '2.0'
tags:
  - description: Number of the day. This API is free (rate limited).
    name: Number of the day
  - description: Get random interesting fact about a given number.
    name: Number Facts
  - description: Generate Random and interesting numbers.
    name: Number Generation
  - description: >-
      Spell out a number ordinal, cardinal or currency. This API is free (rate
      limited).
    name: Spell
  - description: Convert from one base to another. This API is free (rate limited).
    name: Base Conversion
  - description: Convert from one number system to another.
    name: Number Systems Conversion
  - description: Things to do with Prime numbers
    name: Prime
  - description: Digits of PI and more.This API is free (rate limited).
    name: PI
  - description: Check Property of a given number.
    name: Number Checks
x-components: {}

