basePath: /
definitions:
  AccountDetails:
    description: >-
      Contains the account information such as the licensing status for the user
      in the scope.
    properties:
      appLicensingVerdict:
        description: >-
          Required. Details about the licensing status of the user for the app
          in the scope.
        enum:
          - UNKNOWN
          - LICENSED
          - UNLICENSED
          - UNEVALUATED
        type: string
    type: object
  AppIntegrity:
    description: Contains the application integrity information.
    properties:
      appRecognitionVerdict:
        description: Required. Details about the app recognition verdict
        enum:
          - UNKNOWN
          - PLAY_RECOGNIZED
          - UNRECOGNIZED_VERSION
          - UNEVALUATED
        type: string
      certificateSha256Digest:
        description: >-
          Hex fingerprint of the application signing certificate. e.g.
          “ABCE1F....” Set iff app_recognition_verdict != UNEVALUATED.
        items:
          type: string
        type: array
      packageName:
        description: >-
          Package name of the application under attestation. Set iff
          app_recognition_verdict != UNEVALUATED.
        type: string
      versionCode:
        description: >-
          Version code of the application. Set iff app_recognition_verdict !=
          UNEVALUATED.
        format: int64
        type: string
    type: object
  DecodeIntegrityTokenRequest:
    description: Request to decode the integrity token.
    properties:
      integrityToken:
        description: Encoded integrity token.
        type: string
    type: object
  DecodeIntegrityTokenResponse:
    description: Response containing the decoded integrity payload.
    properties:
      tokenPayloadExternal:
        $ref: '#/definitions/TokenPayloadExternal'
        description: Plain token payload generated from the decoded integrity token.
    type: object
  DeviceIntegrity:
    description: Contains the device attestation information.
    properties:
      deviceRecognitionVerdict:
        description: Details about the integrity of the device the app is running on
        items:
          enum:
            - UNKNOWN
            - MEETS_BASIC_INTEGRITY
            - MEETS_DEVICE_INTEGRITY
            - MEETS_STRONG_INTEGRITY
            - MEETS_VIRTUAL_INTEGRITY
          type: string
        type: array
    type: object
  RequestDetails:
    description: Contains the integrity request information.
    properties:
      nonce:
        description: >-
          Required. Nonce that was provided in the request (which is base64
          web-safe no-wrap).
        type: string
      requestPackageName:
        description: >-
          Required. Application package name this attestation was requested for.
          Note: This field makes no guarantees or promises on the caller
          integrity. For details on application integrity, check
          application_integrity.
        type: string
      timestampMillis:
        description: >-
          Required. Timestamp, in milliseconds, of the integrity application
          request.
        format: int64
        type: string
    type: object
  TestingDetails:
    description: Contains additional information generated for testing responses.
    properties:
      isTestingResponse:
        description: >-
          Required. Indicates that the information contained in this payload is
          a testing response that is statically overridden for a tester.
        type: boolean
    type: object
  TokenPayloadExternal:
    description: >-
      Contains basic app information and integrity signals like device
      attestation and licensing details.
    properties:
      accountDetails:
        $ref: '#/definitions/AccountDetails'
        description: Required. Details about the Play Store account.
      appIntegrity:
        $ref: '#/definitions/AppIntegrity'
        description: Required. Details about the application integrity.
      deviceIntegrity:
        $ref: '#/definitions/DeviceIntegrity'
        description: Required. Details about the device integrity.
      requestDetails:
        $ref: '#/definitions/RequestDetails'
        description: Required. Details about the integrity request.
      testingDetails:
        $ref: '#/definitions/TestingDetails'
        description: >-
          Indicates that this payload is generated for testing purposes and
          contains any additional data that is linked with testing status.
    type: object
externalDocs:
  url: 'https://developer.android.com/google/play/integrity'
host: playintegrity.googleapis.com
info:
  contact:
    name: Google
    url: 'https://google.com'
    x-twitter: youtube
  description: Play Integrity
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Play Integrity API
  version: v1
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: >-
      https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: google
      url: 'https://playintegrity.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-providerName: googleapis.com
  x-serviceName: playintegrity
paths:
  '/v1/{packageName}:decodeIntegrityToken':
    parameters:
      - description: V1 error format.
        enum:
          - '1'
          - '2'
        in: query
        name: $.xgafv
        type: string
      - description: OAuth access token.
        in: query
        name: access_token
        type: string
      - description: Data format for response.
        enum:
          - json
          - media
          - proto
        in: query
        name: alt
        type: string
      - description: JSONP
        in: query
        name: callback
        type: string
      - description: Selector specifying which fields to include in a partial response.
        in: query
        name: fields
        type: string
      - description: >-
          API key. Your API key identifies your project and provides you with
          API access, quota, and reports. Required unless you provide an OAuth
          2.0 token.
        in: query
        name: key
        type: string
      - description: OAuth 2.0 token for the current user.
        in: query
        name: oauth_token
        type: string
      - description: Returns response with indentations and line breaks.
        in: query
        name: prettyPrint
        type: boolean
      - description: >-
          Available to use for quota purposes for server-side applications. Can
          be any arbitrary string assigned to a user, but should not exceed 40
          characters.
        in: query
        name: quotaUser
        type: string
      - description: 'Upload protocol for media (e.g. "raw", "multipart").'
        in: query
        name: upload_protocol
        type: string
      - description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
        in: query
        name: uploadType
        type: string
    post:
      consumes:
        - application/json
      description: Decodes the integrity token and returns the token payload.
      operationId: playintegrity.decodeIntegrityToken
      parameters:
        - description: ' Package name of the app the attached integrity token belongs to.'
          in: path
          name: packageName
          required: true
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/DecodeIntegrityTokenRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/DecodeIntegrityTokenResponse'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/playintegrity'
          Oauth2c:
            - 'https://www.googleapis.com/auth/playintegrity'
      tags:
        - v1
schemes:
  - https
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/playintegrity': 'Private Service: https://www.googleapis.com/auth/playintegrity'
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authorizationCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/playintegrity': 'Private Service: https://www.googleapis.com/auth/playintegrity'
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
swagger: '2.0'
tags:
  - name: v1
x-components:
  parameters:
    _.xgafv:
      description: V1 error format.
      enum:
        - '1'
        - '2'
      in: query
      name: $.xgafv
      type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      type: string
    alt:
      description: Data format for response.
      enum:
        - json
        - media
        - proto
      in: query
      name: alt
      type: string
    callback:
      description: JSONP
      in: query
      name: callback
      type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      type: string
    key:
      description: >-
        API key. Your API key identifies your project and provides you with API
        access, quota, and reports. Required unless you provide an OAuth 2.0
        token.
      in: query
      name: key
      type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      type: boolean
    quotaUser:
      description: >-
        Available to use for quota purposes for server-side applications. Can be
        any arbitrary string assigned to a user, but should not exceed 40
        characters.
      in: query
      name: quotaUser
      type: string
    uploadType:
      description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
      in: query
      name: uploadType
      type: string
    upload_protocol:
      description: 'Upload protocol for media (e.g. "raw", "multipart").'
      in: query
      name: upload_protocol
      type: string

