basePath: /
host: api.fungenerators.com
info:
  contact:
    name: Fun Generators
    url: 'http://fungenerators.com/'
  description: >
    A full featured Facts API. REST access with json/xml/jsonp result support.
    On this day birth and death support, random fact, keyword search support
    etc. Below is the documentation for the Random Facts API calls. You can try
    them out right here. [Click here to
    subscribe](http://fungenerators.com/api/facts/)
  termsOfService: 'https://fungenerators.com/terms'
  title: Facts API
  version: '1.5'
  x-apisguru-categories:
    - text
  x-origin:
    - format: swagger
      url: 'https://fungenerators.com/yaml/facts.yaml'
      version: '2.0'
  x-providerName: fungenerators.com
  x-serviceName: random-facts
paths:
  /fact:
    delete:
      description: Delete a Fact entry identified by the id.
      parameters:
        - description: Fact ID
          format: string
          in: query
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Private Facts
    get:
      description: Get a Fact belonging to the id.
      parameters:
        - description: ID of the fact to fetch
          format: string
          in: query
          name: id
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Random Facts
        - Private Facts
    put:
      description: Add a Fact entry to the database (private collection).
      parameters:
        - description: Fact Text
          format: string
          in: query
          name: fact
          required: true
          type: string
        - description: Category of the fact
          format: string
          in: query
          name: category
          required: true
          type: string
        - description: Sub Category of the fact
          format: string
          in: query
          name: subcategory
          required: true
          type: string
        - description: Tags
          format: string
          in: query
          name: tags
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Private Facts
  /fact/categories:
    get:
      description: Get a random Fact.
      parameters:
        - description: start
          format: integer
          in: query
          name: start
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Random Facts
  /fact/fod:
    get:
      description: Get fact of the day for the given category.
      parameters:
        - description: >-
            Category to get the fact of the day from. Must be one from the list
            returned from /fact/fod/categories
          format: string
          in: query
          name: category
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Fact of the day
  /fact/fod/categories:
    get:
      description: Get the list of supported fact of the day categories.
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Fact of the day
  /fact/numbers:
    get:
      description: Get a random fact about a number
      parameters:
        - description: Number value
          format: integer
          in: query
          name: number
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: 200 Success response
        '401':
          description: 401 Unauthorized response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Number Facts
  /fact/onthisday/born:
    get:
      description: >-
        Returns a random ( famous/ relatively famous ) person born on a given
        day and month
      parameters:
        - description: Optional month (1-12). Defaults to current month
          format: string
          in: query
          name: month
          required: false
          type: string
        - description: >-
            Optional day of the month (1- 28/30/31 based on the month). Defaults
            to current day of the month.
          format: string
          in: query
          name: day
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - On this day
  /fact/onthisday/died:
    get:
      description: >-
        Returns a random ( famous/ relatively famous ) person died on a given
        day and month
      parameters:
        - description: Optional month (1-12). Defaults to current month
          format: string
          in: query
          name: month
          required: false
          type: string
        - description: >-
            Optional day of the month (1- 28/30/31 based on the month). Defaults
            to current day of the month.
          format: string
          in: query
          name: day
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - On this day
  /fact/onthisday/event:
    get:
      description: >-
        Returns a random ( famous/ relatively famous ) historic event on a given
        day and month
      parameters:
        - description: Optional month (1-12). Defaults to current month
          format: string
          in: query
          name: month
          required: false
          type: string
        - description: >-
            Optional day of the month (1- 28/30/31 based on the month). Defaults
            to current day of the month.
          format: string
          in: query
          name: day
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - On this day
  /fact/random:
    get:
      description: >-
        Get a random Fact for a given category(optional) and
        subcategory(optional).
      parameters:
        - description: Category to get the fact from
          format: string
          in: query
          name: category
          required: false
          type: string
        - description: Sub Category to get the fact from
          format: string
          in: query
          name: subcategory
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Random Facts
  /fact/search:
    get:
      description: >-
        Search for random Fact which has the text in the query, for a given
        category(optional) and subcategory(optional).
      parameters:
        - description: Text to search for in the facts
          format: string
          in: query
          name: query
          required: false
          type: string
        - description: Category to get the fact from
          format: string
          in: query
          name: category
          required: false
          type: string
        - description: Sub Category to get the fact from
          format: string
          in: query
          name: subcategory
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: 200  response
        '401':
          description: 401  response
      security:
        - X-Fungenerators-Api-Secret: []
      tags:
        - Random Facts
schemes:
  - https
securityDefinitions:
  X-Fungenerators-Api-Secret:
    in: header
    name: X-Fungenerators-Api-Secret
    type: apiKey
swagger: '2.0'
tags:
  - description: Get fact of the day on various categories. This is refreshed daily.
    externalDocs:
      description: Find out more
      url: 'http://fungenerators.com/api/facts#fact-of-the-day'
    name: Fact of the day
  - description: Get a random interesting fact about a number.
    externalDocs:
      description: Find out more
      url: 'http://fungenerators.com/api/facts#number'
    name: Number Facts
  - description: Get random facts based on category and other criteria.
    externalDocs:
      description: Find out more
      url: 'http://fungenerators.com/api/facts#number'
    name: Random Facts
  - description: 'On this day historical events for birth, death and other events.'
    externalDocs:
      description: Find out more
      url: 'http://fungenerators.com/api/facts#number'
    name: On this day
  - description: Store and manage your own Facts online
    externalDocs:
      description: Find out more
      url: 'http://fungenerators.com/api/facts#private'
    name: Private Facts
x-components: {}

