basePath: /
definitions:
  AuthException: {}
  AvailabilityZone:
    maxLength: 32
    minLength: 6
    pattern: '^(\w+-){2,3}\d+\w+$'
    type: string
  EC2InstanceNotFoundException: {}
  EC2InstanceTypeInvalidException: {}
  InstanceId:
    maxLength: 32
    minLength: 10
    pattern: '^i-[a-f0-9]+$'
    type: string
  InstanceOSUser:
    maxLength: 32
    minLength: 1
    pattern: '^[A-Za-z_][A-Za-z0-9\@\._-]{0,30}[A-Za-z0-9\$_-]?$'
    type: string
  InvalidArgsException: {}
  RequestId:
    type: string
  SSHPublicKey:
    maxLength: 4096
    minLength: 256
    type: string
  SendSSHPublicKeyRequest:
    properties:
      AvailabilityZone:
        allOf:
          - $ref: '#/definitions/AvailabilityZone'
          - description: The Availability Zone in which the EC2 instance was launched.
      InstanceId:
        allOf:
          - $ref: '#/definitions/InstanceId'
          - description: The ID of the EC2 instance.
      InstanceOSUser:
        allOf:
          - $ref: '#/definitions/InstanceOSUser'
          - description: >-
              The OS user on the EC2 instance for whom the key can be used to
              authenticate.
      SSHPublicKey:
        allOf:
          - $ref: '#/definitions/SSHPublicKey'
          - description: >-
              The public key material. To use the public key, you must have the
              matching private key.
    required:
      - InstanceId
      - InstanceOSUser
      - SSHPublicKey
      - AvailabilityZone
    title: SendSSHPublicKeyRequest
    type: object
  SendSSHPublicKeyResponse:
    example:
      RequestId: abcd1234-abcd-1234-abcd-1234abcd1234
      Success: true
    properties:
      RequestId:
        allOf:
          - $ref: '#/definitions/RequestId'
          - description: >-
              The ID of the request. Please provide this ID when contacting AWS
              Support for assistance.
      Success:
        allOf:
          - $ref: '#/definitions/Success'
          - description: Is true if the request succeeds and an error otherwise.
    type: object
  SendSerialConsoleSSHPublicKeyRequest:
    properties:
      InstanceId:
        allOf:
          - $ref: '#/definitions/InstanceId'
          - description: The ID of the EC2 instance.
      SSHPublicKey:
        allOf:
          - $ref: '#/definitions/SSHPublicKey'
          - description: >-
              The public key material. To use the public key, you must have the
              matching private key. For information about the supported key
              formats and lengths, see <a
              href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#how-to-generate-your-own-key-and-import-it-to-aws">Requirements
              for key pairs</a> in the <i>Amazon EC2 User Guide</i>.
      SerialPort:
        allOf:
          - $ref: '#/definitions/SerialPort'
          - description: >-
              <p>The serial port of the EC2 instance. Currently only port 0 is
              supported.</p> <p>Default: 0</p>
    required:
      - InstanceId
      - SSHPublicKey
    title: SendSerialConsoleSSHPublicKeyRequest
    type: object
  SendSerialConsoleSSHPublicKeyResponse:
    properties:
      RequestId:
        allOf:
          - $ref: '#/definitions/RequestId'
          - description: >-
              The ID of the request. Please provide this ID when contacting AWS
              Support for assistance.
      Success:
        allOf:
          - $ref: '#/definitions/Success'
          - description: Is true if the request succeeds and an error otherwise.
    type: object
  SerialConsoleAccessDisabledException: {}
  SerialConsoleSessionLimitExceededException: {}
  SerialConsoleSessionUnavailableException: {}
  SerialPort:
    maximum: 0
    minimum: 0
    type: integer
  ServiceException: {}
  Success:
    type: boolean
  ThrottlingException: {}
externalDocs:
  description: Amazon Web Services documentation
  url: 'https://docs.aws.amazon.com/ec2-instance-connect/'
host: ec2-instance-connect.us-east-1.amazonaws.com
info:
  contact:
    email: mike.ralphson@gmail.com
    name: Mike Ralphson
    url: 'https://github.com/mermade/aws2openapi'
    x-twitter: PermittedSoc
  description: >-
    Amazon EC2 Instance Connect enables system administrators to publish
    one-time use SSH public keys to EC2, providing users a simple and secure way
    to connect to their instances.
  license:
    name: Apache 2.0 License
    url: 'http://www.apache.org/licenses/'
  termsOfService: 'https://aws.amazon.com/service-terms/'
  title: AWS EC2 Instance Connect
  version: '2018-04-02'
  x-apiClientRegistration:
    url: >-
      https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://twitter.com/awscloud/profile_image?size=original'
  x-origin:
    - contentType: application/json
      converter:
        url: 'https://github.com/mermade/aws2openapi'
        version: 1.0.0
      url: >-
        https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/ec2-instance-connect-2018-04-02.normal.json
      x-apisguru-driver: external
  x-preferred: true
  x-providerName: amazonaws.com
  x-release: v4
  x-serviceName: ec2-instance-connect
paths:
  /#X-Amz-Target=AWSEC2InstanceConnectService.SendSSHPublicKey:
    parameters:
      - in: header
        name: X-Amz-Content-Sha256
        required: false
        type: string
      - in: header
        name: X-Amz-Date
        required: false
        type: string
      - in: header
        name: X-Amz-Algorithm
        required: false
        type: string
      - in: header
        name: X-Amz-Credential
        required: false
        type: string
      - in: header
        name: X-Amz-Security-Token
        required: false
        type: string
      - in: header
        name: X-Amz-Signature
        required: false
        type: string
      - in: header
        name: X-Amz-SignedHeaders
        required: false
        type: string
    post:
      consumes:
        - application/json
      description: >-
        Pushes an SSH public key to the specified EC2 instance for use by the
        specified user. The key remains for 60 seconds. For more information,
        see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Connect-using-EC2-Instance-Connect.html">Connect
        to your Linux instance using EC2 Instance Connect</a> in the <i>Amazon
        EC2 User Guide</i>.
      operationId: SendSSHPublicKey
      parameters:
        - enum:
            - AWSEC2InstanceConnectService.SendSSHPublicKey
          in: header
          name: X-Amz-Target
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SendSSHPublicKeyRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SendSSHPublicKeyResponse'
        '480':
          description: AuthException
          schema:
            $ref: '#/definitions/AuthException'
        '481':
          description: InvalidArgsException
          schema:
            $ref: '#/definitions/InvalidArgsException'
        '482':
          description: ServiceException
          schema:
            $ref: '#/definitions/ServiceException'
        '483':
          description: ThrottlingException
          schema:
            $ref: '#/definitions/ThrottlingException'
        '484':
          description: EC2InstanceNotFoundException
          schema:
            $ref: '#/definitions/EC2InstanceNotFoundException'
  /#X-Amz-Target=AWSEC2InstanceConnectService.SendSerialConsoleSSHPublicKey:
    parameters:
      - in: header
        name: X-Amz-Content-Sha256
        required: false
        type: string
      - in: header
        name: X-Amz-Date
        required: false
        type: string
      - in: header
        name: X-Amz-Algorithm
        required: false
        type: string
      - in: header
        name: X-Amz-Credential
        required: false
        type: string
      - in: header
        name: X-Amz-Security-Token
        required: false
        type: string
      - in: header
        name: X-Amz-Signature
        required: false
        type: string
      - in: header
        name: X-Amz-SignedHeaders
        required: false
        type: string
    post:
      consumes:
        - application/json
      description: >-
        Pushes an SSH public key to the specified EC2 instance. The key remains
        for 60 seconds, which gives you 60 seconds to establish a serial console
        connection to the instance using SSH. For more information, see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-serial-console.html">EC2
        Serial Console</a> in the <i>Amazon EC2 User Guide</i>.
      operationId: SendSerialConsoleSSHPublicKey
      parameters:
        - enum:
            - AWSEC2InstanceConnectService.SendSerialConsoleSSHPublicKey
          in: header
          name: X-Amz-Target
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SendSerialConsoleSSHPublicKeyRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SendSerialConsoleSSHPublicKeyResponse'
        '480':
          description: AuthException
          schema:
            $ref: '#/definitions/AuthException'
        '481':
          description: SerialConsoleAccessDisabledException
          schema:
            $ref: '#/definitions/SerialConsoleAccessDisabledException'
        '482':
          description: InvalidArgsException
          schema:
            $ref: '#/definitions/InvalidArgsException'
        '483':
          description: ServiceException
          schema:
            $ref: '#/definitions/ServiceException'
        '484':
          description: ThrottlingException
          schema:
            $ref: '#/definitions/ThrottlingException'
        '485':
          description: EC2InstanceNotFoundException
          schema:
            $ref: '#/definitions/EC2InstanceNotFoundException'
        '486':
          description: EC2InstanceTypeInvalidException
          schema:
            $ref: '#/definitions/EC2InstanceTypeInvalidException'
        '487':
          description: SerialConsoleSessionLimitExceededException
          schema:
            $ref: '#/definitions/SerialConsoleSessionLimitExceededException'
        '488':
          description: SerialConsoleSessionUnavailableException
          schema:
            $ref: '#/definitions/SerialConsoleSessionUnavailableException'
schemes:
  - http
security:
  - hmac: []
securityDefinitions:
  hmac:
    description: Amazon Signature authorization v4
    in: header
    name: Authorization
    type: apiKey
    x-amazon-apigateway-authtype: awsSigv4
swagger: '2.0'
x-components:
  parameters:
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      type: string
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      type: string
x-hasEquivalentPaths: true

