basePath: /
definitions:
  fax.v1.fax:
    properties:
      account_sid:
        description: The SID of the Account that created the resource
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      api_version:
        description: The API version used to transmit the fax
        type: string
        x-nullable: true
      date_created:
        description: >-
          The ISO 8601 formatted date and time in GMT when the resource was
          created
        format: date-time
        type: string
        x-nullable: true
      date_updated:
        description: >-
          The ISO 8601 formatted date and time in GMT when the resource was last
          updated
        format: date-time
        type: string
        x-nullable: true
      direction:
        description: The direction of the fax
        enum:
          - inbound
          - outbound
        type: string
        x-nullable: true
      duration:
        description: The time it took to transmit the fax
        type: integer
        x-nullable: true
      from:
        description: The number the fax was sent from
        type: string
        x-nullable: true
      links:
        description: The URLs of the fax's related resources
        format: uri-map
        type: object
        x-nullable: true
      media_sid:
        description: The SID of the FaxMedia resource that is associated with the Fax
        maxLength: 34
        minLength: 34
        pattern: '^ME[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      media_url:
        description: The Twilio-hosted URL that can be used to download fax media
        type: string
        x-nullable: true
      num_pages:
        description: The number of pages contained in the fax document
        type: integer
        x-nullable: true
      price:
        description: The fax transmission price
        type: number
        x-nullable: true
      price_unit:
        description: The ISO 4217 currency used for billing
        format: currency
        type: string
        x-nullable: true
      quality:
        description: The quality of the fax
        enum:
          - standard
          - fine
          - superfine
        type: string
        x-nullable: true
      sid:
        description: The unique string that identifies the resource
        maxLength: 34
        minLength: 34
        pattern: '^FX[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      status:
        description: The status of the fax
        enum:
          - queued
          - processing
          - sending
          - delivered
          - receiving
          - received
          - no-answer
          - busy
          - failed
          - canceled
        type: string
        x-nullable: true
      to:
        description: The phone number that received the fax
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the fax resource
        format: uri
        type: string
        x-nullable: true
    type: object
  fax.v1.fax.fax_media:
    properties:
      account_sid:
        description: The SID of the Account that created the resource
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      content_type:
        description: The content type of the stored fax media
        type: string
        x-nullable: true
      date_created:
        description: The ISO 8601 date and time in GMT when the resource was created
        format: date-time
        type: string
        x-nullable: true
      date_updated:
        description: The ISO 8601 date and time in GMT when the resource was last updated
        format: date-time
        type: string
        x-nullable: true
      fax_sid:
        description: The SID of the fax the FaxMedia resource is associated with
        maxLength: 34
        minLength: 34
        pattern: '^FX[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      sid:
        description: The unique string that identifies the resource
        maxLength: 34
        minLength: 34
        pattern: '^ME[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the FaxMedia resource
        format: uri
        type: string
        x-nullable: true
    type: object
host: fax.twilio.com
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: 'https://support.twilio.com'
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://www.twilio.com/legal/tos'
  title: Twilio - Fax
  version: 1.29.1
  x-apisguru-categories:
    - telecom
    - messaging
  x-logo:
    url: >-
      https://static1.twilio.com/marketing/bundles/marketing/img/logos/wordmark-red.svg
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_fax_v1.json
      version: '3.0'
  x-providerName: twilio.com
  x-serviceName: twilio_fax_v1
paths:
  /v1/Faxes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all faxes.
      operationId: ListFax
      parameters:
        - description: >-
            Retrieve only those faxes sent from this phone number, specified in
            [E.164](https://www.twilio.com/docs/glossary/what-e164) format.
          in: query
          name: From
          type: string
        - description: >-
            Retrieve only those faxes sent to this phone number, specified in
            [E.164](https://www.twilio.com/docs/glossary/what-e164) format.
          in: query
          name: To
          type: string
        - description: >-
            Retrieve only those faxes with a `date_created` that is before or
            equal to this value, specified in [ISO
            8601](https://en.wikipedia.org/wiki/ISO_8601) format.
          format: date-time
          in: query
          name: DateCreatedOnOrBefore
          type: string
        - description: >-
            Retrieve only those faxes with a `date_created` that is later than
            this value, specified in [ISO
            8601](https://en.wikipedia.org/wiki/ISO_8601) format.
          format: date-time
          in: query
          name: DateCreatedAfter
          type: string
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              faxes:
                items:
                  $ref: '#/definitions/fax.v1.fax'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListFaxResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - Beta
    servers:
      - url: 'https://fax.twilio.com'
    x-twilio:
      className: fax
      defaultOutputProperties:
        - sid
        - from
        - to
        - status
        - date_created
      pathType: list
  '/v1/Faxes/{FaxSid}/Media':
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all fax media instances for the specified fax.
      operationId: ListFaxMedia
      parameters:
        - description: The SID of the fax with the FaxMedia resources to read.
          in: path
          maxLength: 34
          minLength: 34
          name: FaxSid
          pattern: '^FX[0-9a-fA-F]{32}$'
          required: true
          type: string
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              media:
                items:
                  $ref: '#/definitions/fax.v1.fax.fax_media'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListFaxMediaResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - Beta
    servers:
      - url: 'https://fax.twilio.com'
    x-twilio:
      className: fax_media
      defaultOutputProperties:
        - content_type
        - url
      pathType: list
  '/v1/Faxes/{FaxSid}/Media/{Sid}':
    delete:
      description: Delete a specific fax media instance.
      operationId: DeleteFaxMedia
      parameters:
        - description: The SID of the fax with the FaxMedia resource to delete.
          in: path
          maxLength: 34
          minLength: 34
          name: FaxSid
          pattern: '^FX[0-9a-fA-F]{32}$'
          required: true
          type: string
        - description: >-
            The Twilio-provided string that uniquely identifies the FaxMedia
            resource to delete.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^ME[0-9a-fA-F]{32}$'
          required: true
          type: string
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: []
      x-maturity:
        - Beta
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific fax media instance.
      operationId: FetchFaxMedia
      parameters:
        - description: The SID of the fax with the FaxMedia resource to fetch.
          in: path
          maxLength: 34
          minLength: 34
          name: FaxSid
          pattern: '^FX[0-9a-fA-F]{32}$'
          required: true
          type: string
        - description: >-
            The Twilio-provided string that uniquely identifies the FaxMedia
            resource to fetch.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^ME[0-9a-fA-F]{32}$'
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/fax.v1.fax.fax_media'
      security:
        - accountSid_authToken: []
      x-maturity:
        - Beta
    servers:
      - url: 'https://fax.twilio.com'
    x-twilio:
      className: fax_media
      defaultOutputProperties:
        - content_type
        - url
      pathType: instance
  '/v1/Faxes/{Sid}':
    delete:
      description: Delete a specific fax and its associated media.
      operationId: DeleteFax
      parameters:
        - description: >-
            The Twilio-provided string that uniquely identifies the Fax resource
            to delete.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^FX[0-9a-fA-F]{32}$'
          required: true
          type: string
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: []
      x-maturity:
        - Beta
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific fax.
      operationId: FetchFax
      parameters:
        - description: >-
            The Twilio-provided string that uniquely identifies the Fax resource
            to fetch.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^FX[0-9a-fA-F]{32}$'
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/fax.v1.fax'
      security:
        - accountSid_authToken: []
      x-maturity:
        - Beta
    servers:
      - url: 'https://fax.twilio.com'
    x-twilio:
      className: fax
      defaultOutputProperties:
        - sid
        - from
        - to
        - status
        - date_created
      pathType: instance
schemes:
  - https
securityDefinitions:
  accountSid_authToken:
    type: basic
swagger: '2.0'
x-components: {}
x-maturity:
  - description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
    name: Beta

