basePath: ','
info:
  contact: {}
  description: >-
    Welcome to the official API of the brainbi platform. Using this API you can
    freely integrate our analytics platform with any other solution. 

    Please refer to the following documentation and in case of any issues,
    please contact us at service@brainbi.net.


    Please note: for this API you will use your email and password from the
    brainbi.net platform to gather a Bearer Token for any API calls (use Login
    and get token). Once you are finished with your calls, please do a logout to
    remove your token and keep your account safe (use logout).
  title: brainbi
  version: 1.0.0
  x-apisguru-categories:
    - ecommerce
  x-origin:
    - format: postman
      url: >-
        https://www.postman.com/collections/1148203-6a9d2dc5-3f7e-47f5-ae7d-782740625908-SzKZtGPb
      version: 2.x
  x-providerName: brainbi.net
paths:
  /api/analyze/pricing:
    get:
      consumes:
        - application/octet-stream
      description: >-
        To update a product, please use the listed attributes listed
        underneath. 
      operationId: '[beta]ScrapeProductCopy'
      parameters:
        - in: query
          name: url
          type: string
        - in: body
          name: body
          schema:
            format: binary
            type: string
      responses:
        '200':
          description: ''
      summary: '[BETA] Scrape Product Copy'
      tags:
        - Products
  /api/customers:
    get:
      description: >-
        This resource lists all cusomters that are currently saved in your
        account.
      operationId: customers
      parameters:
        - in: query
          name: ''
          type: string
      responses:
        '200':
          description: ''
      summary: Customers
      tags:
        - Customers
  /api/login:
    post:
      description: >-
        Use this endpoint to make the initial call with your email and password
        (same as on brainbi.net) and get your bearer token in response.
      operationId: loginAndGetBearerToken
      parameters:
        - description: The same email you use for our platform.
          in: query
          name: email
          type: string
        - description: The password email you use for our platform.
          in: query
          name: password
          type: string
      responses:
        '200':
          description: ''
      summary: Login and get bearer token
  /api/logout:
    post:
      description: 'Once you are done, call this endpoint to lock your account!'
      operationId: logout
      parameters:
        - description: The same email you use for our platform.
          in: query
          name: email
          type: string
      responses:
        '200':
          description: ''
      summary: Logout
  /api/orders:
    get:
      description: This resource lists all orders that are currently saved in your account.
      operationId: orders
      parameters:
        - in: query
          name: ''
          type: string
      responses:
        '200':
          description: ''
      summary: Orders
      tags:
        - Orders
  /api/orders/1137:
    delete:
      consumes:
        - application/octet-stream
      description: Orders
      operationId: orders1
      parameters:
        - in: query
          name: ''
          type: string
        - in: body
          name: body
          schema:
            format: binary
            type: string
      responses:
        '200':
          description: ''
      summary: Orders
      tags:
        - Orders
  /api/products:
    get:
      description: >-
        This resource lists all products that are currently saved in you
        account.
      operationId: products
      parameters:
        - in: query
          name: ''
          type: string
      responses:
        '200':
          description: ''
      summary: Products
      tags:
        - Products
  /api/products/1137:
    delete:
      consumes:
        - application/octet-stream
      description: Products
      operationId: products1
      parameters:
        - in: query
          name: ''
          type: string
        - in: body
          name: body
          schema:
            format: binary
            type: string
      responses:
        '200':
          description: ''
      summary: Products
      tags:
        - Products
  /api/register:
    post:
      description: >-
        Use this endpoint to make the initial call with your email and password
        (same as on brainbi.net) and get your bearer token in response.
      operationId: register
      parameters:
        - description: required
          in: query
          name: first_name
          type: string
        - description: required
          in: query
          name: last_name
          type: string
        - description: required
          in: query
          name: company_name
          type: string
        - description: required
          in: query
          name: shop_url
          type: string
        - description: required
          in: query
          name: email
          type: string
        - description: required
          in: query
          name: store_name
          type: string
        - description: required
          in: query
          name: store_url
          type: string
        - description: required
          in: query
          name: password
          type: string
        - description: required (always 1)
          in: query
          name: fromuser
          type: string
      responses:
        '200':
          description: ''
      summary: Register
  /api/register_woocommerce:
    post:
      description: >-
        Use this endpoint to make the initial call with your email and password
        (same as on brainbi.net) and get your bearer token in response.
      operationId: registerAndCreateStoreConnectionForWooCommerce
      parameters:
        - description: required
          in: query
          name: first_name
          type: string
        - description: required
          in: query
          name: last_name
          type: string
        - description: required
          in: query
          name: company_name
          type: string
        - description: required
          in: query
          name: shop_url
          type: string
        - description: required
          in: query
          name: email
          type: string
        - description: required
          in: query
          name: store_name
          type: string
        - description: required
          in: query
          name: store_url
          type: string
        - description: required
          in: query
          name: password
          type: string
        - description: required (always 1)
          in: query
          name: fromuser
          type: string
        - description: required
          in: query
          name: api_url
          type: string
        - description: required
          in: query
          name: consumer_key
          type: string
        - description: required
          in: query
          name: consumer_secret
          type: string
      responses:
        '200':
          description: ''
      summary: Register and Create Store Connection for WooCommerce
  /api/rule:
    get:
      description: >-
        This resource lists all pricing rules that are currently saved in you
        account.
      operationId: rules
      parameters:
        - in: query
          name: ''
          type: string
      responses:
        '200':
          description: ''
      summary: Rules
      tags:
        - Pricing Rules
  /api/rule/ruleData/1:
    get:
      description: This resource lists all data that wa saved for pricing rules.
      operationId: ruleData
      parameters:
        - in: query
          name: ''
          type: string
      responses:
        '200':
          description: ''
      summary: Rule Data
      tags:
        - Pricing Rules
  /api/rule/ruleData/1/latest:
    get:
      description: >-
        This resource lists only the latest data point that wa saved for a
        pricing rule.
      operationId: ruleDataLatest
      parameters:
        - in: query
          name: ''
          type: string
      responses:
        '200':
          description: ''
      summary: Rule Data Latest
      tags:
        - Pricing Rules
  /api/seo/ranking/latest:
    get:
      description: >-
        This resource lists all pricing rules that are currently saved in you
        account.
      operationId: seoLatestRankings
      parameters:
        - in: query
          name: ''
          type: string
      responses:
        '200':
          description: ''
      summary: SEO Latest Rankings
      tags:
        - SEO
swagger: '2.0'
tags:
  - name: Pricing Rules
  - name: Products
  - name: Customers
  - name: Orders
  - name: OrderLines
  - name: SEO

