basePath: /
definitions:
  monitor.v1.alert:
    properties:
      account_sid:
        description: The SID of the Account that created the resource
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      alert_text:
        description: The text of the alert
        type: string
        x-nullable: true
      api_version:
        description: The API version used when the alert was generated
        type: string
        x-nullable: true
      date_created:
        description: The ISO 8601 date and time in GMT when the resource was created
        format: date-time
        type: string
        x-nullable: true
      date_generated:
        description: >-
          The date and time when the alert was generated specified in ISO 8601
          format
        format: date-time
        type: string
        x-nullable: true
      date_updated:
        description: The ISO 8601 date and time in GMT when the resource was last updated
        format: date-time
        type: string
        x-nullable: true
      error_code:
        description: The error code for the condition that generated the alert
        type: string
        x-nullable: true
      log_level:
        description: The log level
        type: string
        x-nullable: true
      more_info:
        description: >-
          The URL of the page in our Error Dictionary with more information
          about the error condition
        type: string
        x-nullable: true
      request_method:
        description: The method used by the request that generated the alert
        enum:
          - HEAD
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
        format: http-method
        type: string
        x-nullable: true
      request_url:
        description: The URL of the request that generated the alert
        format: uri
        type: string
        x-nullable: true
      resource_sid:
        description: The SID of the resource for which the alert was generated
        maxLength: 34
        minLength: 34
        pattern: '^[a-zA-Z]{2}[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      service_sid:
        description: The SID of the service or resource that generated the alert
        maxLength: 34
        minLength: 34
        pattern: '^[a-zA-Z]{2}[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      sid:
        description: The unique string that identifies the resource
        maxLength: 34
        minLength: 34
        pattern: '^NO[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the Alert resource
        format: uri
        type: string
        x-nullable: true
    type: object
  monitor.v1.alert-instance:
    properties:
      account_sid:
        description: The SID of the Account that created the resource
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      alert_text:
        description: The text of the alert
        type: string
        x-nullable: true
      api_version:
        description: The API version used when the alert was generated
        type: string
        x-nullable: true
      date_created:
        description: The ISO 8601 date and time in GMT when the resource was created
        format: date-time
        type: string
        x-nullable: true
      date_generated:
        description: >-
          The date and time when the alert was generated specified in ISO 8601
          format
        format: date-time
        type: string
        x-nullable: true
      date_updated:
        description: The ISO 8601 date and time in GMT when the resource was last updated
        format: date-time
        type: string
        x-nullable: true
      error_code:
        description: The error code for the condition that generated the alert
        type: string
        x-nullable: true
      log_level:
        description: The log level
        type: string
        x-nullable: true
      more_info:
        description: >-
          The URL of the page in our Error Dictionary with more information
          about the error condition
        type: string
        x-nullable: true
      request_headers:
        description: The request headers of the request that generated the alert
        type: string
        x-nullable: true
      request_method:
        description: The method used by the request that generated the alert
        enum:
          - HEAD
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
        format: http-method
        type: string
        x-nullable: true
      request_url:
        description: The URL of the request that generated the alert
        format: uri
        type: string
        x-nullable: true
      request_variables:
        description: The variables passed in the request that generated the alert
        type: string
        x-nullable: true
      resource_sid:
        description: The SID of the resource for which the alert was generated
        maxLength: 34
        minLength: 34
        pattern: '^[a-zA-Z]{2}[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      response_body:
        description: The response body of the request that generated the alert
        type: string
        x-nullable: true
      response_headers:
        description: The response headers of the request that generated the alert
        type: string
        x-nullable: true
      service_sid:
        description: The SID of the service or resource that generated the alert
        maxLength: 34
        minLength: 34
        pattern: '^[a-zA-Z]{2}[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      sid:
        description: The unique string that identifies the resource
        maxLength: 34
        minLength: 34
        pattern: '^NO[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the Alert resource
        format: uri
        type: string
        x-nullable: true
    type: object
  monitor.v1.event:
    properties:
      account_sid:
        description: The SID of the Account that created the resource
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      actor_sid:
        description: 'The SID of the actor that caused the event, if available'
        maxLength: 34
        minLength: 34
        pattern: '^US[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      actor_type:
        description: The type of actor that caused the event
        type: string
        x-nullable: true
      description:
        description: A description of the event
        type: string
        x-nullable: true
      event_data:
        description: >-
          A JSON string that represents an object with additional data about the
          event
        x-nullable: true
      event_date:
        description: The ISO 8601 date and time in GMT when the event was recorded
        format: date-time
        type: string
        x-nullable: true
      event_type:
        description: The event's type
        type: string
        x-nullable: true
      links:
        description: The absolute URLs of related resources
        format: uri-map
        type: object
        x-nullable: true
      resource_sid:
        description: The SID of the resource that was affected
        maxLength: 34
        minLength: 34
        pattern: '^[a-zA-Z]{2}[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      resource_type:
        description: The type of resource that was affected
        type: string
        x-nullable: true
      sid:
        description: The unique string that identifies the resource
        maxLength: 34
        minLength: 34
        pattern: '^AE[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      source:
        description: The originating system or interface that caused the event
        type: string
        x-nullable: true
      source_ip_address:
        description: The IP address of the source
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource that was affected
        format: uri
        type: string
        x-nullable: true
    type: object
host: monitor.twilio.com
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: 'https://support.twilio.com'
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://www.twilio.com/legal/tos'
  title: Twilio - Monitor
  version: 1.29.2
  x-apisguru-categories:
    - telecom
    - messaging
  x-logo:
    url: >-
      https://static1.twilio.com/marketing/bundles/marketing/img/logos/wordmark-red.svg
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_monitor_v1.json
      version: '3.0'
  x-providerName: twilio.com
  x-serviceName: twilio_monitor_v1
paths:
  /v1/Alerts:
    description: Debugger alerts
    get:
      description: ''
      operationId: ListAlert
      parameters:
        - description: >-
            Only show alerts for this log-level.  Can be: `error`, `warning`,
            `notice`, or `debug`.
          in: query
          name: LogLevel
          type: string
        - description: >-
            Only include alerts that occurred on or after this date and time.
            Specify the date and time in GMT and format as `YYYY-MM-DD` or
            `YYYY-MM-DDThh:mm:ssZ`. Queries for alerts older than 30 days are
            not supported.
          format: date-time
          in: query
          name: StartDate
          type: string
        - description: >-
            Only include alerts that occurred on or before this date and time.
            Specify the date and time in GMT and format as `YYYY-MM-DD` or
            `YYYY-MM-DDThh:mm:ssZ`. Queries for alerts older than 30 days are
            not supported.
          format: date-time
          in: query
          name: EndDate
          type: string
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              alerts:
                items:
                  $ref: '#/definitions/monitor.v1.alert'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListAlertResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://monitor.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - sid
        - error_code
        - log_level
        - alert_text
      pathType: list
  '/v1/Alerts/{Sid}':
    description: Debugger alerts
    get:
      description: ''
      operationId: FetchAlert
      parameters:
        - description: The SID of the Alert resource to fetch.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^NO[0-9a-fA-F]{32}$'
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/monitor.v1.alert-instance'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://monitor.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - sid
        - error_code
        - log_level
        - alert_text
      pathType: instance
  /v1/Events:
    description: Debugger events
    get:
      description: 'Returns a list of events in the account, sorted by event-date.'
      operationId: ListEvent
      parameters:
        - description: >-
            Only include events initiated by this Actor. Useful for auditing
            actions taken by specific users or API credentials.
          in: query
          maxLength: 34
          minLength: 34
          name: ActorSid
          pattern: '^US[0-9a-fA-F]{32}$'
          type: string
        - description: >-
            Only include events of this [Event
            Type](https://www.twilio.com/docs/usage/monitor-events#event-types).
          in: query
          name: EventType
          type: string
        - description: >-
            Only include events that refer to this resource. Useful for
            discovering the history of a specific resource.
          in: query
          maxLength: 34
          minLength: 34
          name: ResourceSid
          pattern: '^[a-zA-Z]{2}[0-9a-fA-F]{32}$'
          type: string
        - description: >-
            Only include events that originated from this IP address. Useful for
            tracking suspicious activity originating from the API or the Twilio
            Console.
          in: query
          name: SourceIpAddress
          type: string
        - description: >-
            Only include events that occurred on or after this date. Specify the
            date in GMT and [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
            format.
          format: date-time
          in: query
          name: StartDate
          type: string
        - description: >-
            Only include events that occurred on or before this date. Specify
            the date in GMT and [ISO
            8601](https://en.wikipedia.org/wiki/ISO_8601) format.
          format: date-time
          in: query
          name: EndDate
          type: string
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              events:
                items:
                  $ref: '#/definitions/monitor.v1.event'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListEventResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://monitor.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - sid
        - event_type
        - event_type
        - description
      pathType: list
  '/v1/Events/{Sid}':
    description: Debugger events
    get:
      description: ''
      operationId: FetchEvent
      parameters:
        - description: The SID of the Event resource to fetch.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^AE[0-9a-fA-F]{32}$'
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/monitor.v1.event'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://monitor.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - sid
        - event_type
        - event_type
        - description
      pathType: instance
schemes:
  - https
securityDefinitions:
  accountSid_authToken:
    type: basic
swagger: '2.0'
x-components: {}
x-maturity:
  - description: This product is Generally Available.
    name: GA

