info:
  title: nic.at Domainfinder API Documentation
  version: 1.0.0
  x-apisguru-categories:
    - developer_tools
  x-origin:
    - format: openapi
      url: 'https://domainfinder.nic.at/openapi/'
      version: '3.0'
  x-providerName: nic.at
  x-serviceName: domainfinder
paths:
  /api/v0/autocomplete:
    get:
      description: >-
        Provides a list of available .at domain names related to the given input
        term or domain
      parameters:
        - description: Domainname/term to obtain suggestions for
          in: query
          name: term
          required: true
          type: string
          x-example: mydomain
      produces:
        - application/json
      responses:
        '200':
          description: List of domain suggestions
          schema:
            example:
              - mynewdomain.at
              - newdomain.at
            properties:
              '':
                items:
                  type: string
                type: array
            type: object
      summary: Get .at domain name suggestions
  /api/v1/suggest:
    get:
      description: >-
        Provides a list of available .at domain names related to the given input
        term or domain
      parameters:
        - description: Domainname/term to obtain suggestions for
          in: query
          name: term
          required: true
          type: string
          x-example: mydomain
      produces:
        - application/json
      responses:
        '200':
          description: List of domain suggestions
          schema:
            example:
              - mynewdomain.at
              - newdomain.at
            properties:
              '':
                items:
                  type: string
                type: array
            type: object
      summary: Get .at domain name suggestions
swagger: '2.0'

