basePath: /
definitions:
  accounts.v1.auth_token_promotion:
    properties:
      account_sid:
        description: The SID of the Account that the secondary Auth Token was created for
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      auth_token:
        description: The promoted Auth Token
        type: string
        x-nullable: true
      date_created:
        description: >-
          The ISO 8601 formatted date and time in UTC when the resource was
          created
        format: date-time
        type: string
        x-nullable: true
      date_updated:
        description: >-
          The ISO 8601 formatted date and time in UTC when the resource was last
          updated
        format: date-time
        type: string
        x-nullable: true
      url:
        description: 'The URI for this resource, relative to `https://accounts.twilio.com`'
        format: uri
        type: string
        x-nullable: true
    type: object
  accounts.v1.credential:
    properties: {}
    type: object
  accounts.v1.credential.credential_aws:
    properties:
      account_sid:
        description: The SID of the Account that created the resource
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      date_created:
        description: The RFC 2822 date and time in GMT when the resource was created
        format: date-time
        type: string
        x-nullable: true
      date_updated:
        description: The RFC 2822 date and time in GMT when the resource was last updated
        format: date-time
        type: string
        x-nullable: true
      friendly_name:
        description: The string that you assigned to describe the resource
        type: string
        x-nullable: true
      sid:
        description: The unique string that identifies the resource
        maxLength: 34
        minLength: 34
        pattern: '^CR[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      url:
        description: 'The URI for this resource, relative to `https://accounts.twilio.com`'
        format: uri
        type: string
        x-nullable: true
    type: object
  accounts.v1.credential.credential_public_key:
    properties:
      account_sid:
        description: >-
          The SID of the Account that created the Credential that the PublicKey
          resource belongs to
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      date_created:
        description: The RFC 2822 date and time in GMT when the resource was created
        format: date-time
        type: string
        x-nullable: true
      date_updated:
        description: The RFC 2822 date and time in GMT when the resource was last updated
        format: date-time
        type: string
        x-nullable: true
      friendly_name:
        description: The string that you assigned to describe the resource
        type: string
        x-nullable: true
      sid:
        description: The unique string that identifies the resource
        maxLength: 34
        minLength: 34
        pattern: '^CR[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      url:
        description: 'The URI for this resource, relative to `https://accounts.twilio.com`'
        format: uri
        type: string
        x-nullable: true
    type: object
  accounts.v1.secondary_auth_token:
    properties:
      account_sid:
        description: The SID of the Account that the secondary Auth Token was created for
        maxLength: 34
        minLength: 34
        pattern: '^AC[0-9a-fA-F]{32}$'
        type: string
        x-nullable: true
      date_created:
        description: >-
          The ISO 8601 formatted date and time in UTC when the resource was
          created
        format: date-time
        type: string
        x-nullable: true
      date_updated:
        description: >-
          The ISO 8601 formatted date and time in UTC when the resource was last
          updated
        format: date-time
        type: string
        x-nullable: true
      secondary_auth_token:
        description: The generated secondary Auth Token
        type: string
        x-nullable: true
      url:
        description: 'The URI for this resource, relative to `https://accounts.twilio.com`'
        format: uri
        type: string
        x-nullable: true
    type: object
host: accounts.twilio.com
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: 'https://support.twilio.com'
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://www.twilio.com/legal/tos'
  title: Twilio - Accounts
  version: 1.29.2
  x-apisguru-categories:
    - telecom
    - messaging
  x-logo:
    url: >-
      https://static1.twilio.com/marketing/bundles/marketing/img/logos/wordmark-red.svg
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_accounts_v1.json
      version: '3.0'
  x-providerName: twilio.com
  x-serviceName: twilio_accounts_v1
paths:
  /v1/AuthTokens/Promote:
    description: Auth Token promotion
    post:
      description: >-
        Promote the secondary Auth Token to primary. After promoting the new
        token, all requests to Twilio using your old primary Auth Token will
        result in an error.
      operationId: UpdateAuthTokenPromotion
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/accounts.v1.auth_token_promotion'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://accounts.twilio.com'
    x-twilio:
      className: auth_token_promotion
      defaultOutputProperties:
        - account_sid
        - auth_token
        - date_created
      pathType: instance
  /v1/AuthTokens/Secondary:
    delete:
      description: Delete the secondary Auth Token from your account
      operationId: DeleteSecondaryAuthToken
      parameters: []
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    description: Secondary Auth Token
    post:
      description: Create a new secondary Auth Token
      operationId: CreateSecondaryAuthToken
      parameters: []
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/accounts.v1.secondary_auth_token'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://accounts.twilio.com'
    x-twilio:
      className: secondary_auth_token
      defaultOutputProperties:
        - account_sid
        - secondary_auth_token
        - date_created
      pathType: instance
  /v1/Credentials:
    description: 'TODO: Resource-level docs'
    servers:
      - url: 'https://accounts.twilio.com'
    x-twilio:
      className: credential
      defaultOutputProperties: []
      pathType: list
  /v1/Credentials/AWS:
    description: User provided AWS keys
    get:
      description: >-
        Retrieves a collection of AWS Credentials belonging to the account used
        to make the request
      operationId: ListCredentialAws
      parameters:
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              credentials:
                items:
                  $ref: '#/definitions/accounts.v1.credential.credential_aws'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListCredentialAwsResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    post:
      consumes:
        - application/x-www-form-urlencoded
      description: Create a new AWS Credential
      operationId: CreateCredentialAws
      parameters:
        - description: >-
            The SID of the Subaccount that this Credential should be associated
            with. Must be a valid Subaccount of the account issuing the request.
          in: formData
          maxLength: 34
          minLength: 34
          name: AccountSid
          pattern: '^AC[0-9a-fA-F]{32}$'
          type: string
        - description: >-
            A string that contains the AWS access credentials in the format
            `<AWS_ACCESS_KEY_ID>:<AWS_SECRET_ACCESS_KEY>`. For example,
            `AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY`
          in: formData
          name: Credentials
          required: true
          type: string
        - description: >-
            A descriptive string that you create to describe the resource. It
            can be up to 64 characters long.
          in: formData
          name: FriendlyName
          type: string
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/accounts.v1.credential.credential_aws'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://accounts.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - sid
        - friendly_name
        - date_created
      parent: /Credentials
      pathType: list
  '/v1/Credentials/AWS/{Sid}':
    delete:
      description: Delete a Credential from your account
      operationId: DeleteCredentialAws
      parameters:
        - description: >-
            The Twilio-provided string that uniquely identifies the AWS resource
            to delete.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^CR[0-9a-fA-F]{32}$'
          required: true
          type: string
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    description: User provided AWS keys
    get:
      description: Fetch the AWS credentials specified by the provided Credential Sid
      operationId: FetchCredentialAws
      parameters:
        - description: >-
            The Twilio-provided string that uniquely identifies the AWS resource
            to fetch.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^CR[0-9a-fA-F]{32}$'
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/accounts.v1.credential.credential_aws'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    post:
      consumes:
        - application/x-www-form-urlencoded
      description: Modify the properties of a given Account
      operationId: UpdateCredentialAws
      parameters:
        - description: >-
            The Twilio-provided string that uniquely identifies the AWS resource
            to update.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^CR[0-9a-fA-F]{32}$'
          required: true
          type: string
        - description: >-
            A descriptive string that you create to describe the resource. It
            can be up to 64 characters long.
          in: formData
          name: FriendlyName
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/accounts.v1.credential.credential_aws'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://accounts.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - sid
        - friendly_name
        - date_created
      parent: /Credentials
      pathType: instance
  /v1/Credentials/PublicKeys:
    description: User provided public keys
    get:
      description: >-
        Retrieves a collection of Public Key Credentials belonging to the
        account used to make the request
      operationId: ListCredentialPublicKey
      parameters:
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              credentials:
                items:
                  $ref: '#/definitions/accounts.v1.credential.credential_public_key'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListCredentialPublicKeyResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    post:
      consumes:
        - application/x-www-form-urlencoded
      description: Create a new Public Key Credential
      operationId: CreateCredentialPublicKey
      parameters:
        - description: >-
            The SID of the Subaccount that this Credential should be associated
            with. Must be a valid Subaccount of the account issuing the request
          in: formData
          maxLength: 34
          minLength: 34
          name: AccountSid
          pattern: '^AC[0-9a-fA-F]{32}$'
          type: string
        - description: >-
            A descriptive string that you create to describe the resource. It
            can be up to 64 characters long.
          in: formData
          name: FriendlyName
          type: string
        - description: >-
            A URL encoded representation of the public key. For example,
            `-----BEGIN PUBLIC KEY-----MIIBIjANB.pa9xQIDAQAB-----END PUBLIC
            KEY-----`
          in: formData
          name: PublicKey
          required: true
          type: string
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/accounts.v1.credential.credential_public_key'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://accounts.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - sid
        - friendly_name
        - date_created
      parent: /Credentials
      pathType: list
  '/v1/Credentials/PublicKeys/{Sid}':
    delete:
      description: Delete a Credential from your account
      operationId: DeleteCredentialPublicKey
      parameters:
        - description: >-
            The Twilio-provided string that uniquely identifies the PublicKey
            resource to delete.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^CR[0-9a-fA-F]{32}$'
          required: true
          type: string
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    description: User provided public keys
    get:
      description: Fetch the public key specified by the provided Credential Sid
      operationId: FetchCredentialPublicKey
      parameters:
        - description: >-
            The Twilio-provided string that uniquely identifies the PublicKey
            resource to fetch.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^CR[0-9a-fA-F]{32}$'
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/accounts.v1.credential.credential_public_key'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    post:
      consumes:
        - application/x-www-form-urlencoded
      description: Modify the properties of a given Account
      operationId: UpdateCredentialPublicKey
      parameters:
        - description: >-
            The Twilio-provided string that uniquely identifies the PublicKey
            resource to update.
          in: path
          maxLength: 34
          minLength: 34
          name: Sid
          pattern: '^CR[0-9a-fA-F]{32}$'
          required: true
          type: string
        - description: >-
            A descriptive string that you create to describe the resource. It
            can be up to 64 characters long.
          in: formData
          name: FriendlyName
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/accounts.v1.credential.credential_public_key'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://accounts.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - sid
        - friendly_name
        - date_created
      parent: /Credentials
      pathType: instance
schemes:
  - https
securityDefinitions:
  accountSid_authToken:
    type: basic
swagger: '2.0'
x-components: {}
x-maturity:
  - description: This product is Generally Available.
    name: GA

