basePath: /svc/mostpopular/v2
definitions:
  Article:
    properties:
      abstract:
        type: string
      byline:
        type: string
      column:
        type: string
      des_facet:
        $ref: '#/definitions/DesFacet'
      geo_facet:
        $ref: '#/definitions/GeoFacet'
      media:
        items: {}
      org_facet:
        $ref: '#/definitions/OrgFacet'
      per_facet:
        $ref: '#/definitions/PerFacet'
      published_date:
        type: string
      section:
        type: string
      source:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  ArticleWithCountType:
    properties:
      abstract:
        type: string
      byline:
        type: string
      column:
        type: string
      count_type:
        type: string
      des_facet:
        $ref: '#/definitions/DesFacet'
      geo_facet:
        $ref: '#/definitions/GeoFacet'
      media:
        items:
          properties:
            caption:
              type: string
            copyright:
              type: string
            media-metadata:
              properties:
                format:
                  type: string
                height:
                  type: integer
                url:
                  type: string
                width:
                  type: integer
              type: object
            subtype:
              type: string
            type:
              type: string
          type: object
        type: array
        x-runscope/nullable: true
        x-runscope/nullable/value: ''''''
      org_facet:
        $ref: '#/definitions/OrgFacet'
      per_facet:
        $ref: '#/definitions/PerFacet'
      published_date:
        type: string
      section:
        type: string
      source:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  DesFacet:
    items: {}
  GeoFacet:
    enum:
      - ''
    items: {}
    x-nullable: true
  OrgFacet:
    items: {}
    type: array
    x-nullable: true
  PerFacet:
    items: {}
    type: array
    x-nullable: true
externalDocs:
  url: 'http://developer.nytimes.com/'
host: api.nytimes.com
info:
  description: 'Get lists of NYT Articles based on shares, emails, and views.'
  termsOfService: 'http://developer.nytimes.com/tou'
  title: Most Popular API
  version: 2.0.0
  x-apiClientRegistration:
    url: 'http://developer.nytimes.com/signup'
  x-apisguru-categories:
    - media
    - open_data
  x-logo:
    url: 'https://static01.nyt.com/images/icons/t_logo_291_black.png'
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/nytimes/public_api_specs/master/most_popular_api/most_popular_api_v2.json
      version: '3.0'
  x-providerName: nytimes.com
  x-serviceName: most_popular_api
paths:
  '/mostemailed/{section}/{time-period}.json':
    get:
      description: ''
      operationId: GET_mostemailed-section-time-period-json
      parameters: []
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: An array of Articles
          schema:
            properties:
              copyright:
                type: string
              num_results:
                type: integer
              results:
                items:
                  $ref: '#/definitions/ArticleWithCountType'
                type: array
              status:
                type: string
            type: object
        '400':
          description: ''
          schema:
            properties:
              copyright:
                type: string
              errors:
                items:
                  type: string
                type: array
              results:
                items: {}
                type: array
              status:
                type: string
            type: object
        '403':
          description: ''
          schema:
            type: object
      security:
        - api-key: []
      summary: Most Emailed by Section & Time Period
    parameters:
      - description: >
          Limits the results by one or more sections. You can use

          `all-sections` or one or more section names seperated by semicolons.
          See `viewed/sections.json` call to get a list of sections. 
        enum:
          - Arts
          - Automobiles
          - Blogs
          - Books
          - Business Day
          - Education
          - Fashion & Style
          - Food
          - Health
          - Job Market
          - Magazine
          - membercenter
          - Movies
          - Multimedia
          - N.Y.%20%2F%20Region
          - NYT Now
          - Obituaries
          - Open
          - Opinion
          - Public Editor
          - Real Estate
          - Science
          - Sports
          - Style
          - Sunday Review
          - T Magazine
          - Technology
          - The Upshot
          - Theater
          - Times Insider
          - Today’s Paper
          - Travel
          - U.S.
          - World
          - Your Money
          - all-sections
        in: path
        name: section
        required: true
        type: string
      - description: >-
          Number of days `1 | 7 | 30 ` corresponds to a day, a week, or a month
          of content.
        enum:
          - '1'
          - '7'
          - '30'
        in: path
        name: time-period
        required: true
        type: string
  '/mostshared/{section}/{time-period}.json':
    get:
      description: ''
      operationId: GET_mostshared-section-time-period-json
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: An array of Articles
          schema:
            properties:
              copyright:
                type: string
              num_results:
                type: integer
              results:
                items:
                  $ref: '#/definitions/Article'
                type: array
              status:
                type: string
            type: object
        '400':
          description: ''
          schema:
            properties:
              copyright:
                type: string
              errors:
                items:
                  type: string
                type: array
              results:
                items: {}
                type: array
              status:
                type: string
            type: object
      security:
        - api-key: []
      summary: Most Shared by Section & Time Period
    parameters:
      - description: >
          Limits the results by one or more sections. You can use

          `all-sections` or one or more section names seperated by semicolons.
          See `viewed/sections.json` call to get a list of sections. 
        enum:
          - Arts
          - Automobiles
          - Blogs
          - Books
          - Business Day
          - Education
          - Fashion & Style
          - Food
          - Health
          - Job Market
          - Magazine
          - membercenter
          - Movies
          - Multimedia
          - N.Y.%20%2F%20Region
          - NYT Now
          - Obituaries
          - Open
          - Opinion
          - Public Editor
          - Real Estate
          - Science
          - Sports
          - Style
          - Sunday Review
          - T Magazine
          - Technology
          - The Upshot
          - Theater
          - Times Insider
          - Today’s Paper
          - Travel
          - U.S.
          - World
          - Your Money
          - all-sections
        in: path
        name: section
        required: true
        type: string
      - description: >-
          Number of days `1 | 7 | 30 ` corresponds to a day, a week, or a month
          of content.
        enum:
          - '1'
          - '7'
          - '30'
        in: path
        name: time-period
        required: true
        type: string
  '/mostviewed/{section}/{time-period}.json':
    get:
      description: ''
      operationId: GET_mostviewed-section-time-period-json
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: An array of Articles
          schema:
            properties:
              copyright:
                type: string
              num_results:
                type: integer
              results:
                items:
                  $ref: '#/definitions/Article'
                type: array
              status:
                type: string
            type: object
      security:
        - api-key: []
      summary: Most Viewed by Section & Time Period
    parameters:
      - description: >
          Limits the results by one or more sections. You can use

          `all-sections` or one or more section names seperated by semicolons.
          See `viewed/sections.json` call to get a list of sections. 
        enum:
          - Arts
          - Automobiles
          - Blogs
          - Books
          - Business Day
          - Education
          - Fashion & Style
          - Food
          - Health
          - Job Market
          - Magazine
          - membercenter
          - Movies
          - Multimedia
          - N.Y.%20%2F%20Region
          - NYT Now
          - Obituaries
          - Open
          - Opinion
          - Public Editor
          - Real Estate
          - Science
          - Sports
          - Style
          - Sunday Review
          - T Magazine
          - Technology
          - The Upshot
          - Theater
          - Times Insider
          - Today’s Paper
          - Travel
          - U.S.
          - World
          - Your Money
          - all-sections
        in: path
        name: section
        required: true
        type: string
      - description: >-
          Number of days `1 | 7 | 30 ` corresponds to a day, a week, or a month
          of content.
        enum:
          - '1'
          - '7'
          - '30'
        in: path
        name: time-period
        required: true
        type: string
schemes:
  - http
securityDefinitions:
  api-key:
    in: query
    name: api-key
    type: apiKey
swagger: '2.0'
x-components:
  parameters:
    OffSet:
      description: Positive integer in a multiple of 20
      in: query
      name: offset
      schema:
        default: 20
        type: integer
    Section:
      description: >
        Limits the results by one or more sections. You can use

        `all-sections` or one or more section names seperated by semicolons. See
        `viewed/sections.json` call to get a list of sections. 
      enum:
        - Arts
        - Automobiles
        - Blogs
        - Books
        - Business Day
        - Education
        - Fashion & Style
        - Food
        - Health
        - Job Market
        - Magazine
        - membercenter
        - Movies
        - Multimedia
        - N.Y.%20%2F%20Region
        - NYT Now
        - Obituaries
        - Open
        - Opinion
        - Public Editor
        - Real Estate
        - Science
        - Sports
        - Style
        - Sunday Review
        - T Magazine
        - Technology
        - The Upshot
        - Theater
        - Times Insider
        - Today’s Paper
        - Travel
        - U.S.
        - World
        - Your Money
        - all-sections
      in: path
      name: section
      required: true
      type: string
    SharedTypes:
      description: >-
        Limits the results by the method used to share the items only works on
        mostshared requests.
      in: query
      name: shared-types
      schema:
        enum:
          - digg
          - email
          - facebook
          - mixx
          - myspace
          - permalink
          - timespeople
          - twitter
          - yahoobuzz
        type: string
    TimePeriod:
      description: >-
        Number of days `1 | 7 | 30 ` corresponds to a day, a week, or a month of
        content.
      enum:
        - '1'
        - '7'
        - '30'
      in: path
      name: time-period
      required: true
      type: string

