basePath: /prod/authorization
host: tf689y3hbj.execute-api.us-east-1.amazonaws.com
info:
  license:
    name: MIT
  title: ESG Rating Data
  version: 1.0.0
  x-apisguru-categories:
    - open_data
  x-origin:
    - format: openapi
      url: >-
        https://www.esgenterprise.com/wp-content/api/ESGRatingAPI-Definition.json
      version: '3.0'
  x-providerName: esgenterprise.com
paths:
  /search:
    get:
      parameters:
        - description: Company name or stock symbol
          in: query
          name: q
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: An array of ESG Ratings
          headers:
            x-next:
              description: ESG ratings
              type: string
          schema:
            properties:
              company_name:
                type: string
              environment_score:
                format: double
                type: number
              governance_score:
                format: double
                type: number
              last_processing_date:
                format: date
                type: string
              social_score:
                format: double
                type: number
              total:
                format: double
                type: number
      security:
        - api_key: []
      summary: List all company ESG Ratings
      tags:
        - rating
schemes:
  - https
securityDefinitions:
  api_key:
    in: query
    name: token
    type: apiKey
swagger: '2.0'
x-components: {}

