basePath: /api
definitions:
  Carrier:
    properties:
      country:
        type: string
      name:
        type: string
      network_code:
        type: string
      network_type:
        enum:
          - fixed_line
          - fixed_line_or_mobile
          - mobile
          - pager
          - personal_number
          - premium_rate
          - shared_cost
          - toll_free
          - uan
          - unknown
          - voicemail
          - voip
        type: string
    type: object
  Roaming:
    properties:
      roaming_country_code:
        type: string
      roaming_network_code:
        type: string
      roaming_network_name:
        type: string
      status:
        enum:
          - unknown
          - roaming
          - not_roaming
        type: string
    type: object
externalDocs:
  description: Find out more about the Sms77.io SMS gateway.
  url: 'https://sms77.io/en/docs/gateway/http-api'
host: gateway.sms77.io
info:
  contact:
    email: support@sms77.io
    name: Support
    url: 'https://sms77.io/en/company/contact'
  description: sms77.io Swagger API. Get your API-Key now at sms77.io.
  license:
    name: Licensed by Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://sms77.io/en/company/terms/'
  title: sms77.io API
  version: 1.0.0
  x-apisguru-categories:
    - telecom
  x-logo:
    url: 'https://www.sms77.io/wp-content/uploads/integrationen_sms77_logo.png'
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/sms77io/api-schemes/master/json/openapi.json
      version: '3.0'
  x-providerName: sms77.io
paths:
  /analytics:
    get:
      operationId: Analytics
      parameters:
        - description: >-
            Start date of the statistics in the format YYYY-MM-DD. By default,
            the date of 30 days ago is set.
          in: query
          name: start
          type: string
        - description: >-
            End date of the statistics in the format YYYY-MM-DD. By default, the
            current day.
          in: query
          name: end
          type: string
        - description: Shows only data of a specific label.
          in: query
          name: label
          type: string
        - description: >-
            Receive the data only for the main account, all your (sub-)accounts
            or only for specific subaccounts.
          in: query
          name: subaccounts
          type: string
        - description: Defines the grouping of the data.
          enum:
            - date
            - label
            - subaccount
            - country
          in: query
          name: group_by
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              date:
                type: string
              direct:
                type: integer
              economy:
                type: integer
              hlr:
                type: integer
              inbound:
                type: integer
              mnp:
                type: integer
              usage_eur:
                format: float
                type: number
              voice:
                type: integer
            type: object
      tags:
        - analytics
  /balance:
    get:
      operationId: Balance
      parameters: []
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            example: 12.34
            format: float
            type: number
      tags:
        - balance
  /contacts:
    get:
      operationId: ContactsGet
      parameters:
        - description: Determines the action to execute.
          enum:
            - read
          in: query
          name: action
          required: true
          type: string
        - default: 0
          description: >-
            Defines whether to return the response as JSON or CSV separated by
            semicolon.
          enum:
            - 0
            - 1
          in: query
          name: json
          type: number
      produces:
        - application/json
        - text/csv
      responses:
        '200':
          description: OK (CSV)
          schema:
            example: '"1";"Tommy Tester";"0049179876543210"'
            type: string
      tags:
        - contacts
    post:
      operationId: ContactsPOST
      parameters:
        - description: Determines the action to execute.
          enum:
            - del
            - write
          in: query
          name: action
          required: true
          type: string
        - default: 0
          description: >-
            Defines whether to return the response as JSON or CSV separated by
            semicolon.
          enum:
            - 0
            - 1
          in: query
          name: json
          type: number
        - description: The contact ID for editing/deletion.
          in: query
          name: id
          type: string
        - description: The contacts name.
          in: query
          name: nick
          type: string
        - description: The contacts phone number.
          in: query
          name: empfaenger
          type: string
        - description: The contacts email address.
          in: query
          name: email
          type: string
      produces:
        - application/json
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            example: 152
            type: string
      tags:
        - contacts
  /hooks:
    get:
      operationId: HooksGet
      parameters:
        - description: Determines the action to execute.
          enum:
            - read
          in: query
          name: action
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              hooks:
                items:
                  properties:
                    created:
                      type: string
                    event_type:
                      type: string
                    id:
                      type: string
                    request_method:
                      type: string
                    target_url:
                      type: string
                  type: object
                type: array
              success:
                type: boolean
            type: object
      tags:
        - hooks
    post:
      operationId: HooksPOST
      parameters:
        - description: Determines the action to execute.
          enum:
            - subscribe
            - unsubscribe
          in: query
          name: action
          required: true
          type: string
        - description: The Webhook ID you wish to unsubscribe.
          in: query
          name: id
          type: integer
        - description: Target URL of your Webhook.
          in: query
          name: target_url
          type: string
        - description: Type of event for which you would like to receive a webhook.
          enum:
            - all
            - sms_mo
            - dlr
            - voice_status
          in: query
          name: event_type
          type: string
        - default: POST
          description: Request method in which you want to receive the webhook.
          enum:
            - POST
            - JSON
            - GET
          in: query
          name: request_method
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Hook subscribed
          schema:
            properties:
              id:
                type: integer
              success:
                type: boolean
            type: object
      tags:
        - hooks
  /lookup:
    post:
      operationId: Lookup
      parameters:
        - description: 'Allowed values are "cnam", "format", "hlr" and "mnp".'
          in: query
          name: type
          required: true
          type: string
        - collectionFormat: csv
          description: The phone number to look up.
          in: query
          items:
            type: string
          name: number
          required: true
          type: array
        - description: >-
            Determines whether the response shall be returned in JSON format.
            Does not work with type "format".
          in: query
          name: json
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
      tags:
        - lookup
  /pricing:
    get:
      operationId: Pricing
      parameters:
        - description: >-
            The countries ISO code to get pricings for. Allowed values are de,
            fr, at. Omit to show pricings for all channels.
          in: query
          name: country
          type: string
        - description: >-
            Determines the response format. Allowed values are json and csv. The
            default value is json.
          in: query
          name: format
          type: string
      produces:
        - application/json
        - text/csv
      responses:
        '200':
          description: OK
      tags:
        - pricing
  /sms:
    post:
      operationId: Sms
      parameters:
        - description: The actual text message to send.
          in: query
          name: text
          required: true
          type: string
        - description: The recipient number or group name.
          in: query
          name: to
          required: true
          type: string
        - description: Set a custom sender name.
          in: query
          name: from
          type: string
        - description: Identifier to return in callbacks.
          in: query
          name: foreign_id
          pattern: '^[A-Z|a-z|0-9|.|\-|_|@]+'
          type: string
        - description: A custom label.
          in: query
          name: label
          pattern: '^[A-Z|a-z|0-9|.|\-|_|@]+'
          type: string
        - description: A custom User Data Header.
          in: query
          name: udh
          type: string
        - description: Date/Time for delayed dispatch.
          in: query
          name: delay
          type: string
        - default: 0
          description: Disable message sending.
          enum:
            - 1
            - 0
          in: query
          name: debug
          type: number
        - default: 0
          description: Enable sending of duplicated messages within 180 seconds.
          enum:
            - 1
            - 0
          in: query
          name: no_reload
          type: number
        - default: 0
          description: Force unicode encoding. Reduces sms length to 70 chars.
          enum:
            - 1
            - 0
          in: query
          name: unicode
          type: number
        - default: 0
          description: Send as flash.
          enum:
            - 1
            - 0
          in: query
          name: flash
          type: number
        - default: 0
          description: Force UTF8 encoding.
          enum:
            - 1
            - 0
          in: query
          name: utf8
          type: number
        - default: 0
          description: Attach message details to response.
          enum:
            - 1
            - 0
          in: query
          name: details
          type: number
        - default: 0
          description: Attach message ID to second row in a text response.
          enum:
            - 1
            - 0
          in: query
          name: return_msg_id
          type: number
        - default: 0
          description: Return a detailed JSON response.
          enum:
            - 1
            - 0
          in: query
          name: json
          type: number
        - default: 0
          description: Enable performance tracking for found URLs.
          enum:
            - 1
            - 0
          in: query
          name: performance_tracking
          type: number
      produces:
        - application/json
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            properties:
              balance:
                format: float
                type: number
              debug:
                type: string
              messages:
                items:
                  properties:
                    encoding:
                      type: string
                    error:
                      type: string
                    error_text:
                      type: string
                    id:
                      type: string
                    messages:
                      items:
                        type: string
                      type: array
                    parts:
                      type: integer
                    price:
                      type: integer
                    recipient:
                      type: string
                    sender:
                      type: string
                    success:
                      type: boolean
                    text:
                      type: string
                  type: object
                type: array
              sms_type:
                enum:
                  - economy
                  - direct
                type: string
              success:
                type: string
              total_price:
                format: float
                type: number
            type: object
      tags:
        - sms
  /status:
    get:
      operationId: Status
      parameters:
        - description: The ID from the SMS.
          in: query
          name: msg_id
          required: true
          type: string
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            example: |
              DELIVERED
              2020-01-09 15:41:30.656
            type: string
      tags:
        - status
  /validate_for_voice:
    post:
      operationId: ValidateForVoice
      parameters:
        - description: >-
            Determines the recipient. Can only be a number, not a contact from
            your address book.
          in: query
          name: number
          required: true
          type: string
        - description: The callback URL which gets queried right after validation.
          format: uri
          in: query
          name: callback
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              code:
                type: string
              error:
                type: string
              success:
                type: boolean
            type: object
      tags:
        - validate_for_voice
  /voice:
    post:
      operationId: Voice
      parameters:
        - description: >-
            Determines the receiver. Must be a valid phone number or contact
            from the address book.
          in: query
          name: to
          required: true
          type: string
        - description: The text to convert to a voice message. Accepts valid XML too.
          in: query
          maxLength: 10000
          name: text
          required: true
          type: string
        - description: >-
            Decides whether the parameter "text" is plain text or XML. The
            default value is 0.
          enum:
            - 1
            - 0
          in: query
          name: xml
          type: number
        - description: >-
            Sets the sender. Must be a verified sender. Use an inbound number of
            yours or one of ours.
          in: query
          name: from
          type: string
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            example: |
              100
              123456789
              0
            type: string
      tags:
        - voice
schemes:
  - https
security:
  - ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Key
    type: apiKey
swagger: '2.0'
tags:
  - externalDocs:
      description: Retrieve analytics
      url: 'https://www.sms77.io/en/docs/gateway/http-api/analytics'
    name: analytics
  - externalDocs:
      description: Send one/multiple SMS
      url: 'https://sms77.io/en/docs/gateway/http-api/sms-disptach'
    name: sms
  - externalDocs:
      description: Retrieve account balance
      url: 'https://sms77.io/en/docs/gateway/http-api/credit-balance'
    name: balance
  - externalDocs:
      description: Retrieve/edit/delete contact(s)
      url: 'https://sms77.io/en/docs/gateway/http-api/contacts'
    name: contacts
  - externalDocs:
      description: Retrieve pricing information
      url: 'https://sms77.io/en/docs/gateway/http-api/pricing'
    name: pricing
  - externalDocs:
      description: Retrieve the status for a sent SMS with the given ID
      url: 'https://sms77.io/en/docs/gateway/http-api/status-reports'
    name: status
  - externalDocs:
      description: Validate caller ID for voice Voice API
      url: 'https://sms77.io/en/docs/gateway/http-api/caller-ids'
    name: validate_for_voice
  - externalDocs:
      description: Issue voice call to phone number
      url: 'https://sms77.io/en/docs/gateway/http-api/voice'
    name: voice
  - externalDocs:
      description: 'Get number format, CNAM,- HLR- or MNP information for given phone number'
      url: 'https://sms77.io/en/docs/gateway/http-api'
    name: lookup
  - externalDocs:
      description: 'Create, view and delete webhooks'
      url: 'https://www.sms77.io/en/docs/gateway/http-api/webhooks/'
    name: hooks
x-components: {}

