definitions:
  HouseMembershipViewModel:
    properties:
      membershipFrom:
        type: string
    type: object
  LineViewModel:
    properties:
      content:
        type: string
      contentAdditionalJson:
        type: string
      contentType:
        enum:
          - Generic
          - Member
          - OralQuestionTime
          - AnsweringBody
          - Bill
        type: string
      contentUrl:
        type: string
      displayOrder:
        format: int32
        type: integer
      forceCapitalisation:
        type: boolean
      horizontalAlignment:
        enum:
          - Left
          - Right
          - Centre
        type: string
      member:
        $ref: '#/definitions/MemberViewModel'
      style:
        enum:
          - DividerSolid
          - EmptyLine
          - Member
          - Footer
          - AnsweringBody
          - WestminsterHallInfo
          - GrandCommitteeInfo
          - DividerDotted
          - DividerDashed
          - Division
          - Text150
          - Text140
          - Text130
          - Text120
          - Text110
          - Text100
          - Text90
          - Text80
          - Text70
        type: string
      verticalAlignment:
        enum:
          - Top
          - Middle
          - Bottom
        type: string
    type: object
  MemberViewModel:
    properties:
      id:
        format: int32
        type: integer
      latestHouseMembership:
        $ref: '#/definitions/HouseMembershipViewModel'
      latestParty:
        $ref: '#/definitions/PartyViewModel'
      nameAddressAs:
        type: string
      nameDisplayAs:
        type: string
      nameFullTitle:
        type: string
      nameListAs:
        type: string
      thumbnailUrl:
        type: string
    type: object
  MessageViewModel:
    properties:
      annunciatorType:
        enum:
          - CommonsMain
          - LordsMain
          - Security
        type: string
      id:
        format: int32
        type: integer
      isSecurityOverride:
        type: boolean
      publishTime:
        format: date-time
        type: string
      scrollingMessages:
        items:
          $ref: '#/definitions/ScrollingMessageViewModel'
        type: array
        uniqueItems: false
      showCommonsBell:
        type: boolean
      showLordsBell:
        type: boolean
      slides:
        items:
          $ref: '#/definitions/SlideViewModel'
        type: array
        uniqueItems: false
    type: object
  PartyViewModel:
    properties:
      backgroundColour:
        type: string
      id:
        format: int32
        type: integer
      name:
        type: string
    type: object
  ScrollingMessageViewModel:
    properties:
      alertType:
        enum:
          - Standard
          - SecondaryChamber
          - Alert
          - SecurityNormal
          - SecurityHigh
        type: string
      content:
        type: string
      displayFrom:
        format: date-time
        type: string
      displayTo:
        format: date-time
        type: string
      id:
        format: int32
        type: integer
      verticalAlignment:
        enum:
          - Top
          - Middle
          - Bottom
        type: string
    type: object
  SlideViewModel:
    properties:
      carouselDisplaySeconds:
        format: int32
        type: integer
      carouselOrder:
        format: int32
        type: integer
      id:
        format: int32
        type: integer
      lines:
        items:
          $ref: '#/definitions/LineViewModel'
        type: array
        uniqueItems: false
      slideTime:
        format: date-time
        type: string
      soundToPlay:
        enum:
          - NewSlide
          - DivisionBell
          - Alert
          - GenericBeep
        type: string
      speakerTime:
        format: date-time
        type: string
      type:
        enum:
          - Debate
          - Division
          - OralQuestionTime
          - UrgentQuestion
          - Statement
          - Prayers
          - HouseRisen
          - Generic
          - NotSitting
          - PrimeMinistersQuestions
          - PointsOfOrder
          - BlankSlide
        type: string
    type: object
info:
  contact:
    name: Digiminster
    url: 'https://www.twitter.com/digiminster'
  description: Get data from the annunciator system.
  title: Annunciator content API
  version: v1
  x-apisguru-categories:
    - open_data
  x-origin:
    - format: swagger
      url: 'https://now-api.parliament.uk/swagger/v1/swagger.json'
      version: '2.0'
  x-providerName: parliament.uk
  x-serviceName: now
paths:
  '/api/Message/message/{annunciator}/current':
    get:
      operationId: GetMessage
      parameters:
        - description: Current message by annunciator
          enum:
            - CommonsMain
            - LordsMain
            - Security
          in: path
          name: annunciator
          required: true
          type: string
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/MessageViewModel'
        '404':
          description: Not Found
      summary: Return the current message by annunciator type
      tags:
        - Message
  '/api/Message/message/{annunciator}/{date}':
    get:
      operationId: GetSpecificMessage
      parameters:
        - description: Message by annunciator type
          enum:
            - CommonsMain
            - LordsMain
            - Security
          in: path
          name: annunciator
          required: true
          type: string
        - description: First message after date time specified
          format: date-time
          in: path
          name: date
          required: true
          type: string
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: >-
            Latest message for given annunciator was issued before specified
            date
          schema:
            $ref: '#/definitions/MessageViewModel'
        '400':
          description: Date provided wasn't in a valid format
        '404':
          description: No message for given annunciator was issued before specified date
      summary: Return the most recent message by annunciator after date time specified
      tags:
        - Message
swagger: '2.0'
x-components: {}

