info:
  contact:
    name: Alex P. Scigalszky
    url: 'https://github.com/AlexScigalszky'
  description: An API Rest to get random words
  title: Palabras aleatorias
  version: 1.0.0
  x-apisguru-categories:
    - text
  x-logo:
    url: 'https://palabras-aleatorias-public-api.herokuapp.com/icon.jpg'
  x-origin:
    - format: openapi
      url: 'https://palabras-aleatorias-public-api.herokuapp.com/openapi3.json'
      version: '3.0'
  x-providerName: palabras-aleatorias-public-api.herokuapp.com
paths:
  /add-word:
    get:
      description: Add a new word. Need to be accepted by a human.
      parameters:
        - description: Word
          in: query
          name: word
          type: string
        - description: Related word
          in: query
          name: related
          type: string
        - description: Definition
          in: query
          name: definition
          type: string
        - description: Author
          in: query
          name: author
          type: string
      responses:
        '200':
          description: new word added.
      summary: Add new word
  /count:
    get:
      description: Return the count of words in database
      parameters: []
      responses:
        '200':
          description: Success
  /echo:
    get:
      description: Response with all query params
      parameters: []
      responses:
        '200':
          description: Success
  /openapi3.json:
    get:
      description: Response with all query params
      parameters: []
      responses:
        '200':
          description: Success
  /random:
    get:
      description: Return a random spanish word
      parameters: []
      responses:
        '200':
          description: Success
swagger: '2.0'
tags: []
x-components: {}

