basePath: /
definitions:
  lookups.v1.phone_number:
    properties:
      add_ons:
        description: A JSON string with the results of the Add-ons you specified
        x-nullable: true
      caller_name:
        description: The name of the phone number's owner
        x-nullable: true
      carrier:
        description: The telecom company that provides the phone number
        x-nullable: true
      country_code:
        description: The ISO country code for the phone number
        type: string
        x-nullable: true
      national_format:
        description: 'The phone number, in national format'
        type: string
        x-nullable: true
      phone_number:
        description: The phone number in E.164 format
        format: phone-number
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
host: lookups.twilio.com
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: 'https://support.twilio.com'
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://www.twilio.com/legal/tos'
  title: Twilio - Lookups
  version: 1.29.2
  x-apisguru-categories:
    - telecom
    - messaging
  x-logo:
    url: >-
      https://static1.twilio.com/marketing/bundles/marketing/img/logos/wordmark-red.svg
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_lookups_v1.json
      version: '3.0'
  x-providerName: twilio.com
  x-serviceName: twilio_lookups_v1
paths:
  '/v1/PhoneNumbers/{PhoneNumber}':
    description: Detailed information on phone numbers
    get:
      description: ''
      operationId: FetchPhoneNumber
      parameters:
        - description: >-
            The phone number to lookup in
            [E.164](https://www.twilio.com/docs/glossary/what-e164) format,
            which consists of a + followed by the country code and subscriber
            number.
          format: phone-number
          in: path
          name: PhoneNumber
          required: true
          type: string
        - description: >-
            The [ISO country
            code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the phone
            number to fetch. This is used to specify the country when the phone
            number is provided in a national format.
          in: query
          name: CountryCode
          type: string
        - collectionFormat: multi
          description: >-
            The type of information to return. Can be: `carrier` or
            `caller-name`. The default is null.  Carrier information costs
            $0.005 per phone number looked up.  Caller Name information is
            currently available only in the US and costs $0.01 per phone number
            looked up.  To retrieve both types on information, specify this
            parameter twice; once with `carrier` and once with `caller-name` as
            the value.
          in: query
          items:
            type: string
          name: Type
          type: array
        - collectionFormat: multi
          description: >-
            The `unique_name` of an Add-on you would like to invoke. Can be the
            `unique_name` of an Add-on that is installed on your account. You
            can specify multiple instances of this parameter to invoke multiple
            Add-ons. For more information about  Add-ons, see the [Add-ons
            documentation](https://www.twilio.com/docs/add-ons).
          in: query
          items:
            type: string
          name: AddOns
          type: array
        - description: >-
            Data specific to the add-on you would like to invoke. The content
            and format of this value depends on the add-on.
          format: prefixed-collapsible-map-AddOns
          in: query
          name: AddOnsData
          type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/lookups.v1.phone_number'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://lookups.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - caller_name
        - country_code
        - carrier
      pathType: instance
schemes:
  - https
securityDefinitions:
  accountSid_authToken:
    type: basic
swagger: '2.0'
x-components: {}
x-maturity:
  - description: This product is Generally Available.
    name: GA

