basePath: /
definitions:
  pricing.v1.messaging:
    properties:
      links:
        format: uri-map
        type: object
        x-nullable: true
      name:
        type: string
        x-nullable: true
      url:
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.messaging.messaging_country:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.messaging.messaging_country-instance:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      inbound_sms_prices:
        description: The list of InboundPrice records
        items:
          format: inbound-sms-price
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        type: array
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      outbound_sms_prices:
        description: The list of OutboundSMSPrice records
        items:
          format: outbound-sms-price
          properties:
            carrier:
              type: string
            mcc:
              type: string
            mnc:
              type: string
            prices:
              items:
                properties:
                  base_price:
                    type: number
                  current_price:
                    type: number
                  number_type:
                    type: string
                type: object
              type: array
          type: object
        type: array
        x-nullable: true
      price_unit:
        description: >-
          The currency in which prices are measured, in ISO 4127 format (e.g.
          usd, eur, jpy)
        format: currency
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.phone_number:
    properties:
      links:
        format: uri-map
        type: object
        x-nullable: true
      name:
        type: string
        x-nullable: true
      url:
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.phone_number.phone_number_country:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      iso_country:
        description: 'The ISO country code '
        format: iso-country-code
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.phone_number.phone_number_country-instance:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      iso_country:
        description: 'The ISO country code '
        format: iso-country-code
        type: string
        x-nullable: true
      phone_number_prices:
        description: The list of PhoneNumberPrices records
        items:
          format: phone-number-price
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        type: array
        x-nullable: true
      price_unit:
        description: >-
          The currency in which prices are measured, in ISO 4127 format (e.g.
          usd, eur, jpy)
        format: currency
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.voice:
    properties:
      links:
        format: uri-map
        type: object
        x-nullable: true
      name:
        type: string
        x-nullable: true
      url:
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.voice.voice_country:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.voice.voice_country-instance:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      inbound_call_prices:
        description: The list of InboundCallPrice records
        items:
          format: inbound-call-price
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        type: array
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      outbound_prefix_prices:
        description: The list of OutboundPrefixPrice records
        items:
          format: outbound-prefix-price
          properties:
            base_price:
              type: number
            current_price:
              type: number
            friendly_name:
              type: string
            prefixes:
              items:
                type: string
              type: array
          type: object
        type: array
        x-nullable: true
      price_unit:
        description: >-
          The currency in which prices are measured, in ISO 4127 format (e.g.
          usd, eur, jpy)
        format: currency
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v1.voice.voice_number:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      inbound_call_price:
        description: The InboundCallPrice record
        format: inbound-call-price
        properties:
          base_price:
            type: number
          current_price:
            type: number
          number_type:
            type: string
        type: object
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      number:
        description: The phone number
        format: phone-number
        type: string
        x-nullable: true
      outbound_call_price:
        description: The OutboundCallPrice record
        format: outbound-call-price
        properties:
          base_price:
            type: number
          current_price:
            type: number
        type: object
        x-nullable: true
      price_unit:
        description: >-
          The currency in which prices are measured, in ISO 4127 format (e.g.
          usd, eur, jpy)
        format: currency
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
host: pricing.twilio.com
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: 'https://support.twilio.com'
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://www.twilio.com/legal/tos'
  title: Twilio - Pricing
  version: 1.29.2
  x-apisguru-categories:
    - telecom
    - messaging
  x-logo:
    url: >-
      https://static1.twilio.com/marketing/bundles/marketing/img/logos/wordmark-red.svg
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_pricing_v1.json
      version: '3.0'
  x-providerName: twilio.com
  x-serviceName: twilio_pricing_v1
paths:
  /v1/Messaging:
    description: 'TODO: Resource-level docs'
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      className: messaging
      defaultOutputProperties:
        - name
      pathType: instance
  /v1/Messaging/Countries:
    description: Messaging pricing by country
    get:
      description: ''
      operationId: ListMessagingCountry
      parameters:
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              countries:
                items:
                  $ref: '#/definitions/pricing.v1.messaging.messaging_country'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListMessagingCountryResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - outbound_sms_prices
        - inbound_sms_prices
        - price_unit
      parent: /Messaging
      pathType: list
  '/v1/Messaging/Countries/{IsoCountry}':
    description: Messaging pricing by country
    get:
      description: ''
      operationId: FetchMessagingCountry
      parameters:
        - description: >-
            The [ISO country
            code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the
            pricing information to fetch.
          format: iso-country-code
          in: path
          name: IsoCountry
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/pricing.v1.messaging.messaging_country-instance'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - outbound_sms_prices
        - inbound_sms_prices
        - price_unit
      parent: /Messaging
      pathType: instance
  /v1/PhoneNumbers:
    description: 'TODO: Resource-level docs'
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      className: phone_number
      defaultOutputProperties:
        - name
      pathType: list
  /v1/PhoneNumbers/Countries:
    description: Phone number pricing by country
    get:
      description: ''
      operationId: ListPhoneNumberCountry
      parameters:
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              countries:
                items:
                  $ref: '#/definitions/pricing.v1.phone_number.phone_number_country'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListPhoneNumberCountryResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - price_unit
      parent: /PhoneNumbers
      pathType: list
  '/v1/PhoneNumbers/Countries/{IsoCountry}':
    description: Phone number pricing by country
    get:
      description: ''
      operationId: FetchPhoneNumberCountry
      parameters:
        - description: >-
            The [ISO country
            code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the
            pricing information to fetch.
          format: iso-country-code
          in: path
          name: IsoCountry
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: >-
              #/definitions/pricing.v1.phone_number.phone_number_country-instance
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - price_unit
      parent: /PhoneNumbers
      pathType: instance
  /v1/Voice:
    description: 'TODO: Resource-level docs'
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      className: voice
      defaultOutputProperties:
        - name
      pathType: instance
  /v1/Voice/Countries:
    description: Voice pricing by country
    get:
      description: ''
      operationId: ListVoiceCountry
      parameters:
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              countries:
                items:
                  $ref: '#/definitions/pricing.v1.voice.voice_country'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListVoiceCountryResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - price_unit
      parent: /Voice
      pathType: list
  '/v1/Voice/Countries/{IsoCountry}':
    description: Voice pricing by country
    get:
      description: ''
      operationId: FetchVoiceCountry
      parameters:
        - description: >-
            The [ISO country
            code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the
            pricing information to fetch.
          format: iso-country-code
          in: path
          name: IsoCountry
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/pricing.v1.voice.voice_country-instance'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - price_unit
      parent: /Voice
      pathType: instance
  '/v1/Voice/Numbers/{Number}':
    description: Voice pricing for a specific phone number
    get:
      description: ''
      operationId: FetchVoiceNumber
      parameters:
        - description: The phone number to fetch.
          format: phone-number
          in: path
          name: Number
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/pricing.v1.voice.voice_number'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - outbound_call_price
        - inbound_call_price
        - price_unit
      parent: /Voice
      pathType: instance
schemes:
  - https
securityDefinitions:
  accountSid_authToken:
    type: basic
swagger: '2.0'
x-components: {}
x-maturity:
  - description: This product is Generally Available.
    name: GA

