basePath: /
definitions:
  pricing.v2.trunking_country:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v2.trunking_country-instance:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      originating_call_prices:
        description: The list of OriginatingCallPrice records
        items:
          format: inbound-call-price
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        type: array
        x-nullable: true
      price_unit:
        description: >-
          The currency in which prices are measured, in ISO 4127 format (e.g.
          usd, eur, jpy)
        format: currency
        type: string
        x-nullable: true
      terminating_prefix_prices:
        description: The list of TerminatingPrefixPrice records
        items:
          format: outbound-prefix-price-with-origin
          properties:
            base_price:
              type: number
            current_price:
              type: number
            destination_prefixes:
              items:
                type: string
              type: array
            friendly_name:
              type: string
            origination_prefixes:
              items:
                type: string
              type: array
          type: object
        type: array
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v2.trunking_number:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      destination_number:
        description: 'The destination phone number, in E.164 format'
        format: phone-number
        type: string
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      originating_call_price:
        description: The OriginatingCallPrice record
        format: inbound-call-price
        properties:
          base_price:
            type: number
          current_price:
            type: number
          number_type:
            type: string
        type: object
        x-nullable: true
      origination_number:
        description: 'The origination phone number, in E.164 format'
        format: phone-number
        type: string
        x-nullable: true
      price_unit:
        description: >-
          The currency in which prices are measured, in ISO 4127 format (e.g.
          usd, eur, jpy)
        format: currency
        type: string
        x-nullable: true
      terminating_prefix_prices:
        items:
          format: outbound-prefix-price-with-origin
          properties:
            base_price:
              type: number
            current_price:
              type: number
            destination_prefixes:
              items:
                type: string
              type: array
            friendly_name:
              type: string
            origination_prefixes:
              items:
                type: string
              type: array
          type: object
        type: array
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v2.voice:
    properties:
      links:
        description: The URLs of the related Countries and Numbers resources
        format: uri-map
        type: object
        x-nullable: true
      name:
        description: The resource name
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v2.voice.voice_country:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v2.voice.voice_country-instance:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      inbound_call_prices:
        description: The list of InboundCallPrice records
        items:
          format: inbound-call-price
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        type: array
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      outbound_prefix_prices:
        description: The list of OutboundPrefixPriceWithOrigin records
        items:
          format: outbound-prefix-price-with-origin
          properties:
            base_price:
              type: number
            current_price:
              type: number
            destination_prefixes:
              items:
                type: string
              type: array
            friendly_name:
              type: string
            origination_prefixes:
              items:
                type: string
              type: array
          type: object
        type: array
        x-nullable: true
      price_unit:
        description: >-
          The currency in which prices are measured, in ISO 4127 format (e.g.
          usd, eur, jpy)
        format: currency
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
  pricing.v2.voice.voice_number:
    properties:
      country:
        description: The name of the country
        type: string
        x-nullable: true
      destination_number:
        description: 'The destination phone number, in E.164 format'
        format: phone-number
        type: string
        x-nullable: true
      inbound_call_price:
        description: The InboundCallPrice record
        format: inbound-call-price
        properties:
          base_price:
            type: number
          current_price:
            type: number
          number_type:
            type: string
        type: object
        x-nullable: true
      iso_country:
        description: The ISO country code
        format: iso-country-code
        type: string
        x-nullable: true
      origination_number:
        description: 'The origination phone number, in E.164 format'
        format: phone-number
        type: string
        x-nullable: true
      outbound_call_prices:
        description: The list of OutboundCallPriceWithOrigin records
        items:
          format: outbound-call-price-with-origin
          properties:
            base_price:
              type: number
            current_price:
              type: number
            origination_prefixes:
              items:
                type: string
              type: array
          type: object
        type: array
        x-nullable: true
      price_unit:
        description: >-
          The currency in which prices are measured, in ISO 4127 format (e.g.
          usd, eur, jpy)
        format: currency
        type: string
        x-nullable: true
      url:
        description: The absolute URL of the resource
        format: uri
        type: string
        x-nullable: true
    type: object
host: pricing.twilio.com
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: 'https://support.twilio.com'
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://www.twilio.com/legal/tos'
  title: Twilio - Pricing
  version: 1.29.2
  x-apisguru-categories:
    - telecom
    - messaging
  x-logo:
    url: >-
      https://static1.twilio.com/marketing/bundles/marketing/img/logos/wordmark-red.svg
  x-origin:
    - format: openapi
      url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_pricing_v2.json
      version: '3.0'
  x-providerName: twilio.com
  x-serviceName: twilio_pricing_v2
paths:
  /v2/Trunking/Countries:
    description: Trunking pricing by country
    get:
      description: ''
      operationId: ListTrunkingCountry
      parameters:
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              countries:
                items:
                  $ref: '#/definitions/pricing.v2.trunking_country'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListTrunkingCountryResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - price_unit
      pathType: list
  '/v2/Trunking/Countries/{IsoCountry}':
    description: Trunking pricing by country
    get:
      description: Fetch a specific Country.
      operationId: FetchTrunkingCountry
      parameters:
        - description: >-
            The [ISO country
            code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the
            origin-based voice pricing information to fetch.
          format: iso-country-code
          in: path
          name: IsoCountry
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/pricing.v2.trunking_country-instance'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - price_unit
      pathType: instance
  '/v2/Trunking/Numbers/{DestinationNumber}':
    description: Trunking pricing for a specific phone number
    get:
      description: >-
        Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      operationId: FetchTrunkingNumber
      parameters:
        - description: >-
            The destination phone number, in
            [E.164](https://www.twilio.com/docs/glossary/what-e164) format, for
            which to fetch the origin-based voice pricing information. E.164
            format consists of a + followed by the country code and subscriber
            number.
          format: phone-number
          in: path
          name: DestinationNumber
          required: true
          type: string
        - description: >-
            The origination phone number, in
            [E.164](https://www.twilio.com/docs/glossary/what-e164) format, for
            which to fetch the origin-based voice pricing information. E.164
            format consists of a + followed by the country code and subscriber
            number.
          format: phone-number
          in: query
          name: OriginationNumber
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/pricing.v2.trunking_number'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - inbound_call_price
        - price_unit
      pathType: instance
  /v2/Voice:
    description: Voice pricing
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      className: voice
      defaultOutputProperties:
        - name
      pathType: instance
  /v2/Voice/Countries:
    description: Voice pricing by country
    get:
      description: ''
      operationId: ListVoiceCountry
      parameters:
        - description: >-
            How many resources to return in each list page. The default is 50,
            and the maximum is 1000.
          in: query
          maximum: 1000
          minimum: 1
          name: PageSize
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              countries:
                items:
                  $ref: '#/definitions/pricing.v2.voice.voice_country'
                type: array
              meta:
                properties:
                  first_page_url:
                    format: uri
                    type: string
                  key:
                    type: string
                  next_page_url:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_url:
                    format: uri
                    type: string
                  url:
                    format: uri
                    type: string
                type: object
            title: ListVoiceCountryResponse
            type: object
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - price_unit
      parent: /Voice
      pathType: list
  '/v2/Voice/Countries/{IsoCountry}':
    description: Voice pricing by country
    get:
      description: Fetch a specific Country.
      operationId: FetchVoiceCountry
      parameters:
        - description: >-
            The [ISO country
            code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the
            origin-based voice pricing information to fetch.
          format: iso-country-code
          in: path
          name: IsoCountry
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/pricing.v2.voice.voice_country-instance'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - price_unit
      parent: /Voice
      pathType: instance
  '/v2/Voice/Numbers/{DestinationNumber}':
    description: Voice pricing for a specific phone number
    get:
      description: >-
        Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      operationId: FetchVoiceNumber
      parameters:
        - description: >-
            The destination phone number, in
            [E.164](https://www.twilio.com/docs/glossary/what-e164) format, for
            which to fetch the origin-based voice pricing information. E.164
            format consists of a + followed by the country code and subscriber
            number.
          format: phone-number
          in: path
          name: DestinationNumber
          required: true
          type: string
        - description: >-
            The origination phone number, in
            [E.164](https://www.twilio.com/docs/glossary/what-e164) format, for
            which to fetch the origin-based voice pricing information. E.164
            format consists of a + followed by the country code and subscriber
            number.
          format: phone-number
          in: query
          name: OriginationNumber
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/pricing.v2.voice.voice_number'
      security:
        - accountSid_authToken: []
      x-maturity:
        - GA
    servers:
      - url: 'https://pricing.twilio.com'
    x-twilio:
      defaultOutputProperties:
        - country
        - inbound_call_price
        - price_unit
      parent: /Voice
      pathType: instance
schemes:
  - https
securityDefinitions:
  accountSid_authToken:
    type: basic
swagger: '2.0'
x-components: {}
x-maturity:
  - description: This product is Generally Available.
    name: GA

