definitions:
  ErskineMayChapterOverview:
    properties:
      description:
        type: string
      number:
        format: int32
        type: integer
      partNumber:
        format: int32
        type: integer
      sections:
        items:
          $ref: '#/definitions/ErskineMaySectionOverview'
        type: array
        uniqueItems: false
      title:
        type: string
    type: object
  ErskineMayFootnote:
    properties:
      content:
        type: string
      number:
        format: int32
        type: integer
    type: object
  ErskineMayIndexTerm:
    properties:
      childTerms:
        items:
          $ref: '#/definitions/ErskineMayIndexTerm'
        type: array
        uniqueItems: false
      displayAs:
        type: string
      id:
        format: int32
        type: integer
      parentTerm:
        $ref: '#/definitions/ErskineMayIndexTerm'
      references:
        items:
          $ref: '#/definitions/ErskineMayParagraphSearchResult'
        type: array
        uniqueItems: false
      seeLinks:
        items:
          $ref: '#/definitions/ErskineMayIndexTermSeeLink'
        type: array
        uniqueItems: false
      term:
        type: string
    type: object
  ErskineMayIndexTermSearchResult:
    properties:
      displayAs:
        type: string
      id:
        format: int32
        type: integer
      seeValue:
        type: string
    type: object
  ErskineMayIndexTermSeeLink:
    properties:
      indexTermId:
        format: int32
        type: integer
      seeType:
        type: string
      seeValue:
        type: string
    type: object
  ErskineMayParagraphSearchResult:
    properties:
      chapterNumber:
        format: int32
        type: integer
      chapterTitle:
        type: string
      paragraphReference:
        type: string
      partNumber:
        format: int32
        type: integer
      searchResultText:
        type: string
      sectionId:
        format: int32
        type: integer
      sectionTitle:
        type: string
      sectionTitleChain:
        type: string
    type: object
  ErskineMayPart:
    properties:
      chapters:
        items:
          $ref: '#/definitions/ErskineMayChapterOverview'
        type: array
        uniqueItems: false
      description:
        type: string
      number:
        format: int32
        type: integer
      title:
        type: string
    type: object
  ErskineMaySearch_ErskineMayIndexTermSearchResult_:
    properties:
      searchResults:
        items:
          $ref: '#/definitions/ErskineMayIndexTermSearchResult'
        type: array
        uniqueItems: false
      searchTerm:
        type: string
      searchTerms:
        items:
          type: string
        type: array
        uniqueItems: false
      skip:
        format: int32
        type: integer
      suggestedSearch:
        type: string
      take:
        format: int32
        type: integer
      totalResults:
        format: int32
        type: integer
    type: object
  ErskineMaySearch_ErskineMayParagraphSearchResult_:
    properties:
      searchResults:
        items:
          $ref: '#/definitions/ErskineMayParagraphSearchResult'
        type: array
        uniqueItems: false
      searchTerm:
        type: string
      searchTerms:
        items:
          type: string
        type: array
        uniqueItems: false
      skip:
        format: int32
        type: integer
      suggestedSearch:
        type: string
      take:
        format: int32
        type: integer
      totalResults:
        format: int32
        type: integer
    type: object
  ErskineMaySearch_ErskineMaySectionSearchResult_:
    properties:
      searchResults:
        items:
          $ref: '#/definitions/ErskineMaySectionSearchResult'
        type: array
        uniqueItems: false
      searchTerm:
        type: string
      searchTerms:
        items:
          type: string
        type: array
        uniqueItems: false
      skip:
        format: int32
        type: integer
      suggestedSearch:
        type: string
      take:
        format: int32
        type: integer
      totalResults:
        format: int32
        type: integer
    type: object
  ErskineMaySectionDetail:
    properties:
      chapterNumber:
        format: int32
        type: integer
      chapterTitle:
        type: string
      contentHtml:
        type: string
      footnotes:
        items:
          $ref: '#/definitions/ErskineMayFootnote'
        type: array
        uniqueItems: false
      id:
        format: int32
        type: integer
      parentSectionId:
        format: int32
        type: integer
      parentSectionTitle:
        type: string
      partNumber:
        format: int32
        type: integer
      partTitle:
        type: string
      subSections:
        items:
          $ref: '#/definitions/ErskineMaySectionOverview'
        type: array
        uniqueItems: false
      title:
        type: string
      titleChain:
        type: string
    type: object
  ErskineMaySectionOverview:
    properties:
      id:
        format: int32
        type: integer
      subSections:
        items:
          $ref: '#/definitions/ErskineMaySectionOverview'
        type: array
        uniqueItems: false
      title:
        type: string
      titleChain:
        type: string
    type: object
  ErskineMaySectionSearchResult:
    properties:
      chapterNumber:
        format: int32
        type: integer
      chapterTitle:
        type: string
      partNumber:
        format: int32
        type: integer
      sectionId:
        format: int32
        type: integer
      sectionTitle:
        type: string
      sectionTitleChain:
        type: string
    type: object
info:
  contact:
    email: softwareengineering@parliament.uk
    name: UK Parliament
    url: ''
  description: An API that allows querying of Erskine May data.
  title: Erskine May API
  version: v1
  x-apisguru-categories:
    - open_data
  x-origin:
    - format: swagger
      url: 'https://erskinemay-api.parliament.uk/swagger/v1/swagger.json'
      version: '2.0'
  x-providerName: parliament.uk
  x-serviceName: erskine-may
paths:
  '/api/Chapter/{chapterNumber}':
    get:
      operationId: Get
      parameters:
        - description: Chapter overview with the chapter number specified
          format: int32
          in: path
          name: chapterNumber
          required: true
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMayChapterOverview'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      summary: Returns a single chapter overview by chapter number.
      tags:
        - Chapter
  /api/IndexTerm/browse:
    get:
      operationId: BrowseIndexTerms
      parameters:
        - description: Index terms by start letter
          in: query
          name: startLetter
          required: false
          type: string
        - default: 0
          description: 'The number of records to skip from the first, default is 0.'
          format: int32
          in: query
          name: skip
          required: false
          type: integer
        - default: 20
          description: 'The number of records to return, default is 20, maximum is 20.'
          format: int32
          in: query
          name: take
          required: false
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMaySearch_ErskineMayIndexTermSearchResult_'
      summary: Returns a list of index terms by start letter.
      tags:
        - IndexTerm
  '/api/IndexTerm/{indexTermId}':
    get:
      parameters:
        - description: Index term by if
          format: int32
          in: path
          name: indexTermId
          required: true
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMayIndexTerm'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      summary: Returns an index term by id.
      tags:
        - IndexTerm
  /api/Part:
    get:
      parameters: []
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            items:
              $ref: '#/definitions/ErskineMayPart'
            type: array
            uniqueItems: false
      summary: Returns a list of all parts.
      tags:
        - Part
  '/api/Part/{partNumber}':
    get:
      parameters:
        - description: Part by part number
          format: int32
          in: path
          name: partNumber
          required: true
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMayPart'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      summary: Returns a part by part number.
      tags:
        - Part
  '/api/Search/IndexTermSearchResults/{searchTerm}':
    get:
      operationId: GetIndexTermSearchResults
      parameters:
        - description: Index terms which contain search term.
          in: path
          name: searchTerm
          required: true
          type: string
        - default: 0
          description: 'The number of records to skip from the first, default is 0.'
          format: int32
          in: query
          name: skip
          required: false
          type: integer
        - default: 20
          description: 'The number of records to return, default is 20, maximum is 20.'
          format: int32
          in: query
          name: take
          required: false
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMaySearch_ErskineMayIndexTermSearchResult_'
      summary: Returns a list of index terms which contain the search term.
      tags:
        - Search
  '/api/Search/Paragraph/{reference}':
    get:
      operationId: GetParagraphSectionId
      parameters:
        - description: Section overview by reference.
          in: path
          name: reference
          required: true
          type: string
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMaySectionOverview'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      summary: Returns a section overview by reference.
      tags:
        - Search
  '/api/Search/ParagraphSearchResults/{searchTerm}':
    get:
      operationId: GetParagraphSearchResults
      parameters:
        - description: Paragraphs which contain search term in their content.
          in: path
          name: searchTerm
          required: true
          type: string
        - default: 0
          description: 'The number of records to skip from the first, default is 0.'
          format: int32
          in: query
          name: skip
          required: false
          type: integer
        - default: 20
          description: 'The number of records to return, default is 20, maximum is 20.'
          format: int32
          in: query
          name: take
          required: false
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMaySearch_ErskineMayParagraphSearchResult_'
      summary: Returns a list of paragraphs which contain the search term.
      tags:
        - Search
  '/api/Search/SectionSearchResults/{searchTerm}':
    get:
      operationId: GetSectionSearchResults
      parameters:
        - description: Sections which contain search term in their title.
          in: path
          name: searchTerm
          required: true
          type: string
        - default: 0
          description: 'The number of records to skip from the first, default is 0.'
          format: int32
          in: query
          name: skip
          required: false
          type: integer
        - default: 20
          description: 'The number of records to return, default is 20, maximum is 20.'
          format: int32
          in: query
          name: take
          required: false
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMaySearch_ErskineMaySectionSearchResult_'
      summary: Returns a list of sections which contain the search term.
      tags:
        - Search
  '/api/Section/{sectionId}':
    get:
      parameters:
        - description: Section by id.
          format: int32
          in: path
          name: sectionId
          required: true
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMaySectionDetail'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      summary: Returns a section by section id.
      tags:
        - Section
  '/api/Section/{sectionId},{step}':
    get:
      operationId: Navigate
      parameters:
        - description: Section by id.
          format: int32
          in: path
          name: sectionId
          required: true
          type: integer
        - description: Number of sections to step over from given section.
          format: int32
          in: path
          name: step
          required: true
          type: integer
      produces:
        - application/json
        - text/json
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ErskineMaySectionOverview'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      summary: Returns a section overview by section id and step.
      tags:
        - Section
swagger: '2.0'
x-components: {}

