basePath: /doc-converter/
host: api.presalytics.io
info:
  contact:
    email: kevin@presalytics.io
    name: Presalytics.io
    url: 'http://presalytics.io'
  description: >-
    This api converts file formats of OpenXml and OpenOffice documents formats
    to vector files (e.g., svg)
  license:
    name: AGPL
  title: Doc Converter
  version: '0.1'
  x-apisguru-categories:
    - analytics
  x-logo:
    url: 'https://presalytics.io/static/img/Logo/Logos/Orange-White/navbar.png'
  x-origin:
    - format: openapi
      url: 'https://api.presalytics.io/doc-converter/openapi.json'
      version: '3.0'
  x-providerName: presalytics.io
  x-serviceName: converter
paths:
  /svgconvert:
    post:
      consumes:
        - multipart/form-data
      operationId: svgconvert
      parameters:
        - format: binary
          in: formData
          name: file
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Url of svg file
          schema:
            properties:
              blob_name:
                type: string
              blob_url:
                type: string
            title: File Url
            type: object
        '400':
          description: Bad Request.
        '415':
          description: Invalid file type
      summary: converts pptx file to svg image
schemes:
  - https
swagger: '2.0'

