basePath: /
definitions:
  Client:
    description: Metadata gathered about the client
    properties:
      app_name:
        example: 1Password Extension
        type: string
      app_version:
        example: '20127'
        type: string
      ip_address:
        example: 13.227.95.22
        type: string
      os_name:
        example: MacOSX
        type: string
      os_version:
        example: 10.15.6
        type: string
      platform_name:
        example: Chrome
        type: string
      platform_version:
        description: >-
          Depending on the platform used, this can be the version of the browser
          that the client extension is installed, the model of computer that the
          native application is installed or the machine's CPU version that the
          CLI was installed
        type: string
  Cursor:
    description: Cursor
    properties:
      cursor:
        description: >-
          Cursor to fetch more data if available or continue the polling process
          if required
        example: aGVsbG8hIGlzIGl0IG1lIHlvdSBhcmUgbG9va2luZyBmb3IK
        type: string
  CursorCollection:
    allOf:
      - $ref: '#/definitions/Cursor'
      - properties:
          has_more:
            description: >-
              Whether there may still be more data to fetch using the returned
              cursor. If true, the subsequent request could still be empty.
            type: boolean
    description: Common cursor properties for collection responses
  DateTimeRFC3339:
    example: '2020-06-11T19:32:50.000Z'
    format: date-time
    type: string
  Details:
    description: Additional information about the sign-in attempt
    properties:
      value:
        description: >-
          For firewall prevented sign-ins, the value is the chosen continent,
          country, etc. that blocked the sign-in attempt
        example: Europe
        type: string
  Error:
    properties:
      Error:
        properties:
          Message:
            description: The error message.
            type: string
        type: object
    type: object
  Introspection:
    properties:
      Features:
        example:
          - itemusages
          - signinattempts
        items:
          type: string
        type: array
      IssuedAt:
        $ref: '#/definitions/DateTimeRFC3339'
      UUID:
        type: string
    type: object
  ItemUsage:
    description: A single item usage object
    properties:
      client:
        $ref: '#/definitions/Client'
      item_uuid:
        $ref: '#/definitions/UUID'
      timestamp:
        $ref: '#/definitions/DateTimeRFC3339'
      used_version:
        type: integer
      user:
        $ref: '#/definitions/User'
      uuid:
        $ref: '#/definitions/UUID'
      vault_uuid:
        $ref: '#/definitions/UUID'
  ItemUsageItems:
    allOf:
      - properties:
          items:
            items:
              $ref: '#/definitions/ItemUsage'
            type: array
      - $ref: '#/definitions/CursorCollection'
    description: An object wrapping cursor properties and a list of items usages
  ResetCursor:
    description: Reset cursor
    properties:
      end_time:
        $ref: '#/definitions/DateTimeRFC3339'
      limit:
        maximum: 1000
        minimum: 1
        type: number
      start_time:
        $ref: '#/definitions/DateTimeRFC3339'
  SignInAttempt:
    description: A single sign-in attempt object
    properties:
      category:
        enum:
          - success
          - credentials_failed
          - mfa_failed
          - modern_version_failed
          - firewall_failed
          - firewall_reported_success
        example: firewall_failed
        type: string
      client:
        $ref: '#/definitions/Client'
      country:
        description: Country ISO Code
        example: France
        type: string
      details:
        $ref: '#/definitions/Details'
      session_uuid:
        $ref: '#/definitions/UUID'
      target_user:
        $ref: '#/definitions/User'
      timestamp:
        $ref: '#/definitions/DateTimeRFC3339'
      type:
        enum:
          - credentials_ok
          - mfa_ok
          - password_secret_bad
          - mfa_missing
          - totp_disabled
          - totp_bad
          - totp_timeout
          - u2f_disabled
          - u2f_bad
          - u2f_timout
          - duo_disabled
          - duo_bad
          - duo_timeout
          - duo_native_bad
          - platform_secret_disabled
          - platform_secret_bad
          - platform_secret_proxy
          - code_disabled
          - code_bad
          - code_timeout
          - ip_blocked
          - continent_blocked
          - country_blocked
          - anonymous_blocked
          - all_blocked
          - modern_version_missing
          - modern_version_old
        example: continent_blocked
        type: string
      uuid:
        $ref: '#/definitions/UUID'
  SignInAttemptItems:
    allOf:
      - properties:
          items:
            items:
              $ref: '#/definitions/SignInAttempt'
            type: array
      - $ref: '#/definitions/CursorCollection'
    description: An object wrapping cursor properties and a list of sign-in attempts
  UUID:
    example: 56YE2TYN2VFYRLNSHKPW5NVT5E
    type: string
  User:
    description: User object
    properties:
      email:
        format: email
        type: string
      name:
        description: Full name
        example: Jack O'Neill
        type: string
      uuid:
        $ref: '#/definitions/UUID'
host: events.1password.com
info:
  description: 1Password Events API Specification.
  title: Events API
  version: 1.0.0
  x-apisguru-categories:
    - security
  x-logo:
    url: >-
      https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/1password-logo.svg/1280px-1password-logo.svg.png
  x-origin:
    - format: openapi
      url: >-
        https://i.1password.com/media/1password-events-reporting/1password-events-api.yaml
      version: '3.0'
  x-providerName: 1password.com
  x-serviceName: events
paths:
  /api/auth/introspect:
    get:
      operationId: getAuthIntrospect
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: Introspection object
          schema:
            $ref: '#/definitions/Introspection'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Generic error
          schema:
            $ref: '#/definitions/Error'
      security:
        - jwtsa: []
      summary: Performs introspection of the provided Bearer JWT token
      tags:
        - auth
  /api/v1/itemusages:
    post:
      description: >-
        This endpoint requires your JSON Web Token to have the *itemusages*
        feature.
      operationId: getItemUsages
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: Item usages response object
          schema:
            $ref: '#/definitions/ItemUsageItems'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Generic error
          schema:
            $ref: '#/definitions/Error'
      security:
        - jwtsa: []
      summary: Retrieves item usages
      tags:
        - api-v1
  /api/v1/signinattempts:
    post:
      description: >-
        This endpoint requires your JSON Web Token to have the *signinattempts*
        feature.
      operationId: getSignInAttempts
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: Sign-in attempts response object
          schema:
            $ref: '#/definitions/SignInAttemptItems'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Generic error
          schema:
            $ref: '#/definitions/Error'
      security:
        - jwtsa: []
      summary: Retrieves sign-in attempts
      tags:
        - api-v1
schemes:
  - https
securityDefinitions:
  jwtsa:
    description: A JWT SA token issued to this service
    in: header
    name: Authorization
    type: apiKey
swagger: '2.0'
x-components:
  examples:
    Cursor:
      summary: Used for continued calling with a cursor
      value:
        cursor: aGVsbG8hIGlzIGl0IG1lIHlvdSBhcmUgbG9va2luZyBmb3IK
    ResetCursor:
      summary: Used for reseting the cursor
      value:
        limit: 100
        start_time: '2021-06-11T19:32:50.000Z'
  requestBodies:
    CursorRequest:
      content:
        application/json:
          examples:
            Continuing cursor:
              $ref: '#/x-components/examples/Cursor'
            Resetting cursor:
              $ref: '#/x-components/examples/ResetCursor'
          schema:
            oneOf:
              - $ref: '#/definitions/Cursor'
              - $ref: '#/definitions/ResetCursor'
    ItemUsagesRequest:
      $ref: '#/x-components/requestBodies/CursorRequest'
    SignInAttemptsRequest:
      $ref: '#/x-components/requestBodies/CursorRequest'
  responses:
    GenericErrorResponse:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Error'
      description: Generic error
    IntrospectResponse:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Introspection'
      description: Introspection object
    ItemUsagesResponse:
      content:
        application/json:
          schema:
            $ref: '#/definitions/ItemUsageItems'
      description: Item usages response object
    SignInAttemptsResponse:
      content:
        application/json:
          schema:
            $ref: '#/definitions/SignInAttemptItems'
      description: Sign-in attempts response object
    UnauthorizedErrorResponse:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Error'
      description: Unauthorized

