basePath: /api.ote-godaddy.com
definitions:
  Error:
    properties:
      code:
        description: >-
          Short identifier for the error, suitable for indicating the specific
          error within client code
        format: constant
        type: string
      fields:
        description: 'List of the specific fields, and the errors found with their contents'
        items:
          $ref: '#/definitions/ErrorField'
        type: array
      message:
        description: 'Human-readable, English description of the error'
        type: string
    required:
      - code
  ErrorField:
    properties:
      code:
        description: >-
          Short identifier for the error, suitable for indicating the specific
          error within client code
        format: constant
        type: string
      message:
        description: >-
          Human-readable, English description of the problem with the contents
          of the field
        type: string
      path:
        description: >-
          <ul>

          <li style='margin-left: 12px;'>JSONPath referring to a field
          containing an error</li>

          <strong style='margin-left: 12px;'>OR</strong>

          <li style='margin-left: 12px;'>JSONPath referring to a field that
          refers to an object containing an error, with more detail in
          `pathRelated`</li>

          </ul>
        format: json-path
        type: string
      pathRelated:
        description: >-
          JSONPath referring to a field containing an error, which is referenced
          by `path`
        format: json-path
        type: string
    required:
      - path
      - code
  ErrorLimit:
    properties:
      code:
        description: >-
          Short identifier for the error, suitable for indicating the specific
          error within client code
        format: constant
        type: string
      fields:
        description: 'List of the specific fields, and the errors found with their contents'
        items:
          $ref: '#/definitions/ErrorField'
        type: array
      message:
        description: 'Human-readable, English description of the error'
        type: string
      retryAfterSec:
        description: Number of seconds to wait before attempting a similar request
        format: integer-positive
        type: integer
    required:
      - retryAfterSec
      - code
  LegalAgreement:
    properties:
      agreementKey:
        description: Unique identifier for the legal agreement
        type: string
      content:
        description: 'Contents of the legal agreement, suitable for embedding'
        type: string
      title:
        description: Title of the legal agreement
        type: string
      url:
        description: URL to a page containing the legal agreement
        format: url
        type: string
    required:
      - agreementKey
      - title
      - content
info:
  title: ''
  version: 1.0.0
  x-apisguru-categories:
    - hosting
  x-origin:
    - format: swagger
      url: 'https://developer.godaddy.com/swagger/swagger_agreements.json'
      version: '2.0'
  x-providerName: ote-godaddy.com
  x-serviceName: agreements
paths:
  /v1/agreements:
    get:
      operationId: get
      parameters:
        - description: 'PrivateLabelId to operate as, if different from JWT'
          in: header
          name: X-Private-Label-Id
          required: false
          type: integer
        - default: en-US
          description: >-
            Unique identifier of the Market used to retrieve/translate Legal
            Agreements
          format: bcp-47
          in: header
          name: X-Market-Id
          required: false
          type: string
        - collectionFormat: csv
          description: Keys for Agreements whose details are to be retrieved
          in: query
          items:
            type: string
          name: keys
          required: true
          type: array
      produces:
        - application/javascript
        - application/json
        - application/xml
        - text/javascript
        - text/xml
      responses:
        '200':
          description: Request was successful
          schema:
            items:
              $ref: '#/definitions/LegalAgreement'
            type: array
        '400':
          description: Request was malformed
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Authentication info not sent or invalid
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Authenticated user is not allowed access
          schema:
            $ref: '#/definitions/Error'
        '429':
          description: Too many requests received within interval
          schema:
            $ref: '#/definitions/ErrorLimit'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      summary: Retrieve Legal Agreements for provided agreements keys
      tags:
        - v1
swagger: '2.0'
tags:
  - description: ''
    name: v1
x-components: {}

