basePath: /
definitions:
  Questions_Collection: {}
host: polls.apiblueprint.org
info:
  contact:
    x-twitter: Reloadly
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  title: topupsapi
  version: 1.0.0
  x-apisguru-categories:
    - telecom
  x-logo:
    url: 'https://twitter.com/Reloadly/profile_image?size=original'
  x-origin:
    - converter:
        url: 'https://github.com/mermade/oas-kit'
        version: 7.0.4
      format: openapi
      url: 'https://topupsapi.docs.apiary.io/api-description-document'
      version: '3.0'
  x-providerName: reloadly.com
paths:
  /questions:
    get:
      description: ''
      operationId: List All Questions
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          headers: {}
      summary: List All Questions
      tags: []
    post:
      consumes:
        - application/json
      description: |-
        You may create your own question using this action. It takes a JSON
        object containing a question and a collection of answers in the
        form of choices.
      operationId: Create a New Question
      parameters:
        - in: body
          name: body
          schema:
            example:
              choices:
                - Swift
                - Python
                - Objective-C
                - Ruby
              question: Favourite programming language?
            properties:
              choices:
                items:
                  type: string
                type: array
              question:
                type: string
            type: object
      produces:
        - application/json
      responses:
        '201':
          description: Created
          headers:
            Location:
              type: string
      summary: Create a New Question
      tags: []
schemes:
  - https
swagger: '2.0'
tags: []
x-components: {}

