basePath: /
definitions:
  CancelExecutionRequest:
    description: Request for the CancelExecution method.
    properties: {}
    type: object
  Error:
    description: Error describes why the execution was abnormally terminated.
    properties:
      context:
        description: Human-readable stack trace string.
        type: string
      payload:
        description: Error message and data returned represented as a JSON string.
        type: string
      stackTrace:
        $ref: '#/definitions/StackTrace'
        description: Stack trace with detailed information of where error was generated.
    type: object
  Execution:
    description: >-
      A running instance of a
      [Workflow](/workflows/docs/reference/rest/v1beta/projects.locations.workflows).
    properties:
      argument:
        description: >-
          Input parameters of the execution represented as a JSON string. The
          size limit is 32KB. *Note*: If you are using the REST API directly to
          run your workflow, you must escape any JSON string value of
          `argument`. Example:
          `'{"argument":"{\"firstName\":\"FIRST\",\"lastName\":\"LAST\"}"}'`
        type: string
      callLogLevel:
        description: The call logging level associated to this execution.
        enum:
          - CALL_LOG_LEVEL_UNSPECIFIED
          - LOG_ALL_CALLS
          - LOG_ERRORS_ONLY
        type: string
      endTime:
        description: 'Output only. Marks the end of execution, successful or not.'
        format: google-datetime
        readOnly: true
        type: string
      error:
        $ref: '#/definitions/Error'
        description: >-
          Output only. The error which caused the execution to finish
          prematurely. The value is only present if the execution's state is
          `FAILED` or `CANCELLED`.
        readOnly: true
      name:
        description: >-
          Output only. The resource name of the execution. Format:
          projects/{project}/locations/{location}/workflows/{workflow}/executions/{execution}
        readOnly: true
        type: string
      result:
        description: >-
          Output only. Output of the execution represented as a JSON string. The
          value can only be present if the execution's state is `SUCCEEDED`.
        readOnly: true
        type: string
      startTime:
        description: Output only. Marks the beginning of execution.
        format: google-datetime
        readOnly: true
        type: string
      state:
        description: Output only. Current state of the execution.
        enum:
          - STATE_UNSPECIFIED
          - ACTIVE
          - SUCCEEDED
          - FAILED
          - CANCELLED
        readOnly: true
        type: string
      workflowRevisionId:
        description: Output only. Revision of the workflow this execution is using.
        readOnly: true
        type: string
    type: object
  ListExecutionsResponse:
    description: Response for the ListExecutions method.
    properties:
      executions:
        description: The executions which match the request.
        items:
          $ref: '#/definitions/Execution'
        type: array
      nextPageToken:
        description: >-
          A token, which can be sent as `page_token` to retrieve the next page.
          If this field is omitted, there are no subsequent pages.
        type: string
    type: object
  Position:
    description: >-
      Position contains source position information about the stack trace
      element such as line number, column number and length of the code block in
      bytes.
    properties:
      column:
        description: >-
          The source code column position (of the line) the current instruction
          was generated from.
        format: int64
        type: string
      length:
        description: The number of bytes of source code making up this stack trace element.
        format: int64
        type: string
      line:
        description: >-
          The source code line number the current instruction was generated
          from.
        format: int64
        type: string
    type: object
  StackTrace:
    description: A collection of stack elements (frames) where an error occurred.
    properties:
      elements:
        description: An array of stack elements.
        items:
          $ref: '#/definitions/StackTraceElement'
        type: array
    type: object
  StackTraceElement:
    description: A single stack element (frame) where an error occurred.
    properties:
      position:
        $ref: '#/definitions/Position'
        description: The source position information of the stack trace element.
      routine:
        description: The routine where the error occurred.
        type: string
      step:
        description: The step the error occurred at.
        type: string
    type: object
externalDocs:
  url: 'https://cloud.google.com/workflows'
host: workflowexecutions.googleapis.com
info:
  contact:
    name: Google
    url: 'https://google.com'
    x-twitter: youtube
  description: Execute workflows created with Workflows API.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Workflow Executions API
  version: v1beta
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: >-
      https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: openapi
      url: 'https://workflowexecutions.googleapis.com/$discovery/rest?version=v1beta'
      version: '3.0'
  x-providerName: googleapis.com
  x-serviceName: workflowexecutions
paths:
  '/v1beta/{name}':
    get:
      description: Returns an execution of the given name.
      operationId: workflowexecutions.projects.locations.workflows.executions.get
      parameters:
        - description: >-
            Required. Name of the execution to be retrieved. Format:
            projects/{project}/locations/{location}/workflows/{workflow}/executions/{execution}
          in: path
          name: name
          required: true
          type: string
        - description: >-
            Optional. A view defining which fields should be filled in the
            returned execution. The API will default to the FULL view.
          enum:
            - EXECUTION_VIEW_UNSPECIFIED
            - BASIC
            - FULL
          in: query
          name: view
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Execution'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
    parameters:
      - description: V1 error format.
        enum:
          - '1'
          - '2'
        in: query
        name: $.xgafv
        type: string
      - description: OAuth access token.
        in: query
        name: access_token
        type: string
      - description: Data format for response.
        enum:
          - json
          - media
          - proto
        in: query
        name: alt
        type: string
      - description: JSONP
        in: query
        name: callback
        type: string
      - description: Selector specifying which fields to include in a partial response.
        in: query
        name: fields
        type: string
      - description: >-
          API key. Your API key identifies your project and provides you with
          API access, quota, and reports. Required unless you provide an OAuth
          2.0 token.
        in: query
        name: key
        type: string
      - description: OAuth 2.0 token for the current user.
        in: query
        name: oauth_token
        type: string
      - description: Returns response with indentations and line breaks.
        in: query
        name: prettyPrint
        type: boolean
      - description: >-
          Available to use for quota purposes for server-side applications. Can
          be any arbitrary string assigned to a user, but should not exceed 40
          characters.
        in: query
        name: quotaUser
        type: string
      - description: 'Upload protocol for media (e.g. "raw", "multipart").'
        in: query
        name: upload_protocol
        type: string
      - description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
        in: query
        name: uploadType
        type: string
  '/v1beta/{name}:cancel':
    parameters:
      - description: V1 error format.
        enum:
          - '1'
          - '2'
        in: query
        name: $.xgafv
        type: string
      - description: OAuth access token.
        in: query
        name: access_token
        type: string
      - description: Data format for response.
        enum:
          - json
          - media
          - proto
        in: query
        name: alt
        type: string
      - description: JSONP
        in: query
        name: callback
        type: string
      - description: Selector specifying which fields to include in a partial response.
        in: query
        name: fields
        type: string
      - description: >-
          API key. Your API key identifies your project and provides you with
          API access, quota, and reports. Required unless you provide an OAuth
          2.0 token.
        in: query
        name: key
        type: string
      - description: OAuth 2.0 token for the current user.
        in: query
        name: oauth_token
        type: string
      - description: Returns response with indentations and line breaks.
        in: query
        name: prettyPrint
        type: boolean
      - description: >-
          Available to use for quota purposes for server-side applications. Can
          be any arbitrary string assigned to a user, but should not exceed 40
          characters.
        in: query
        name: quotaUser
        type: string
      - description: 'Upload protocol for media (e.g. "raw", "multipart").'
        in: query
        name: upload_protocol
        type: string
      - description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
        in: query
        name: uploadType
        type: string
    post:
      consumes:
        - application/json
      description: Cancels an execution of the given name.
      operationId: workflowexecutions.projects.locations.workflows.executions.cancel
      parameters:
        - description: >-
            Required. Name of the execution to be cancelled. Format:
            projects/{project}/locations/{location}/workflows/{workflow}/executions/{execution}
          in: path
          name: name
          required: true
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/CancelExecutionRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Execution'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
  '/v1beta/{parent}/executions':
    get:
      description: >-
        Returns a list of executions which belong to the workflow with the given
        name. The method returns executions of all workflow revisions. Returned
        executions are ordered by their start time (newest first).
      operationId: workflowexecutions.projects.locations.workflows.executions.list
      parameters:
        - description: >-
            Required. Name of the workflow for which the executions should be
            listed. Format:
            projects/{project}/locations/{location}/workflows/{workflow}
          in: path
          name: parent
          required: true
          type: string
        - description: >-
            Maximum number of executions to return per call. Max supported value
            depends on the selected Execution view: it's 10000 for BASIC and 100
            for FULL. The default value used if the field is not specified is
            100, regardless of the selected view. Values greater than the max
            value will be coerced down to it.
          in: query
          name: pageSize
          type: integer
        - description: >-
            A page token, received from a previous `ListExecutions` call.
            Provide this to retrieve the subsequent page. When paginating, all
            other parameters provided to `ListExecutions` must match the call
            that provided the page token.
          in: query
          name: pageToken
          type: string
        - description: >-
            Optional. A view defining which fields should be filled in the
            returned executions. The API will default to the BASIC view.
          enum:
            - EXECUTION_VIEW_UNSPECIFIED
            - BASIC
            - FULL
          in: query
          name: view
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/ListExecutionsResponse'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
    parameters:
      - description: V1 error format.
        enum:
          - '1'
          - '2'
        in: query
        name: $.xgafv
        type: string
      - description: OAuth access token.
        in: query
        name: access_token
        type: string
      - description: Data format for response.
        enum:
          - json
          - media
          - proto
        in: query
        name: alt
        type: string
      - description: JSONP
        in: query
        name: callback
        type: string
      - description: Selector specifying which fields to include in a partial response.
        in: query
        name: fields
        type: string
      - description: >-
          API key. Your API key identifies your project and provides you with
          API access, quota, and reports. Required unless you provide an OAuth
          2.0 token.
        in: query
        name: key
        type: string
      - description: OAuth 2.0 token for the current user.
        in: query
        name: oauth_token
        type: string
      - description: Returns response with indentations and line breaks.
        in: query
        name: prettyPrint
        type: boolean
      - description: >-
          Available to use for quota purposes for server-side applications. Can
          be any arbitrary string assigned to a user, but should not exceed 40
          characters.
        in: query
        name: quotaUser
        type: string
      - description: 'Upload protocol for media (e.g. "raw", "multipart").'
        in: query
        name: upload_protocol
        type: string
      - description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
        in: query
        name: uploadType
        type: string
    post:
      consumes:
        - application/json
      description: Creates a new execution using the latest revision of the given workflow.
      operationId: workflowexecutions.projects.locations.workflows.executions.create
      parameters:
        - description: >-
            Required. Name of the workflow for which an execution should be
            created. Format:
            projects/{project}/locations/{location}/workflows/{workflow} The
            latest revision of the workflow will be used.
          in: path
          name: parent
          required: true
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Execution'
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Execution'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - projects
schemes:
  - https
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': >-
        See, edit, configure, and delete your Google Cloud data and see the
        email address for your Google Account.
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authorizationCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': >-
        See, edit, configure, and delete your Google Cloud data and see the
        email address for your Google Account.
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
swagger: '2.0'
tags:
  - name: projects
x-components:
  parameters:
    _.xgafv:
      description: V1 error format.
      enum:
        - '1'
        - '2'
      in: query
      name: $.xgafv
      type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      type: string
    alt:
      description: Data format for response.
      enum:
        - json
        - media
        - proto
      in: query
      name: alt
      type: string
    callback:
      description: JSONP
      in: query
      name: callback
      type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      type: string
    key:
      description: >-
        API key. Your API key identifies your project and provides you with API
        access, quota, and reports. Required unless you provide an OAuth 2.0
        token.
      in: query
      name: key
      type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      type: boolean
    quotaUser:
      description: >-
        Available to use for quota purposes for server-side applications. Can be
        any arbitrary string assigned to a user, but should not exceed 40
        characters.
      in: query
      name: quotaUser
      type: string
    uploadType:
      description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
      in: query
      name: uploadType
      type: string
    upload_protocol:
      description: 'Upload protocol for media (e.g. "raw", "multipart").'
      in: query
      name: upload_protocol
      type: string

