basePath: /mailboxvalidator/MailboxValidator-Disposable-Email-Checker/1.0.0
host: virtserver.swaggerhub.com
info:
  contact:
    x-twitter: MailBoxV
  description: >-
    The MailboxValidator Disposable Email Checker API checks if a single email
    address is from a disposable email provider and returns the results in
    either JSON or XML format. Refer to
    https://www.mailboxvalidator.com/api-email-disposable for further
    information.
  title: MailboxValidator Disposable Email Checker
  version: 1.0.0
  x-apisguru-categories:
    - email
  x-logo:
    url: 'https://twitter.com/MailBoxV/profile_image?size=original'
  x-origin:
    - converter:
        url: 'https://github.com/mermade/oas-kit'
        version: 7.0.4
      format: openapi
      url: >-
        https://api.swaggerhub.com/apis/mailboxvalidator/MailboxValidator-Disposable-Email-Checker/1.0.0
      version: '3.0'
  x-providerName: mailboxvalidator.com
  x-serviceName: disposable
paths:
  /v1/email/disposable:
    get:
      description: >-
        The Disposable Email Checker API does checking on a single email address
        and returns if it is from a disposable email provider in either JSON or
        XML format.
      parameters:
        - description: Return the result in json (default) or xml format.
          enum:
            - json
            - xml
          in: query
          name: format
          type: string
        - description: The email address to check if is from a disposable email provider.
          in: query
          name: email
          required: true
          type: string
        - description: API key.
          in: query
          name: key
          required: true
          type: string
      produces:
        - application/json; charset=utf-8
      responses:
        '200':
          description: disposable email checker response
          schema:
            type: string
schemes:
  - https
swagger: '2.0'

