basePath: /
definitions:
  AccessDeniedException: {}
  Arn:
    maxLength: 255
    minLength: 1
    pattern: '^[A-Za-z0-9:\/_-]*$'
    type: string
  ConflictException: {}
  EndpointTemporarilyUnavailableException: {}
  GetRoutingControlStateRequest:
    properties:
      RoutingControlArn:
        allOf:
          - $ref: '#/definitions/Arn'
          - description: >-
              The Amazon Resource Number (ARN) for the routing control that you
              want to get the state for.
    required:
      - RoutingControlArn
    title: GetRoutingControlStateRequest
    type: object
  GetRoutingControlStateResponse:
    properties:
      RoutingControlArn:
        allOf:
          - $ref: '#/definitions/Arn'
          - description: The Amazon Resource Number (ARN) of the response.
      RoutingControlState:
        allOf:
          - $ref: '#/definitions/RoutingControlState'
          - description: The state of the routing control.
    required:
      - RoutingControlArn
      - RoutingControlState
    type: object
  InternalServerException: {}
  ResourceNotFoundException: {}
  RoutingControlState:
    enum:
      - 'On'
      - 'Off'
    type: string
  ThrottlingException: {}
  UpdateRoutingControlStateEntries:
    items:
      $ref: '#/definitions/UpdateRoutingControlStateEntry'
    type: array
  UpdateRoutingControlStateEntry:
    description: A routing control state.
    properties:
      RoutingControlArn:
        allOf:
          - $ref: '#/definitions/Arn'
          - description: >-
              The Amazon Resource Number (ARN) for the routing control state
              entry.
      RoutingControlState:
        allOf:
          - $ref: '#/definitions/RoutingControlState'
          - description: >-
              The routing control state in a set of routing control state
              entries.
    required:
      - RoutingControlArn
      - RoutingControlState
    type: object
  UpdateRoutingControlStateRequest:
    properties:
      RoutingControlArn:
        allOf:
          - $ref: '#/definitions/Arn'
          - description: >-
              The Amazon Resource Number (ARN) for the routing control that you
              want to update the state for.
      RoutingControlState:
        allOf:
          - $ref: '#/definitions/RoutingControlState'
          - description: >-
              The state of the routing control. You can set the value to be On
              or Off.
    required:
      - RoutingControlArn
      - RoutingControlState
    title: UpdateRoutingControlStateRequest
    type: object
  UpdateRoutingControlStateResponse:
    properties: {}
    type: object
  UpdateRoutingControlStatesRequest:
    properties:
      UpdateRoutingControlStateEntries:
        allOf:
          - $ref: '#/definitions/UpdateRoutingControlStateEntries'
          - description: A set of routing control entries that you want to update.
    required:
      - UpdateRoutingControlStateEntries
    title: UpdateRoutingControlStatesRequest
    type: object
  UpdateRoutingControlStatesResponse:
    properties: {}
    type: object
  ValidationException: {}
externalDocs:
  description: Amazon Web Services documentation
  url: 'https://docs.aws.amazon.com/route53-recovery-cluster/'
host: route53-recovery-cluster.us-east-1.amazonaws.com
info:
  contact:
    email: mike.ralphson@gmail.com
    name: Mike Ralphson
    url: 'https://github.com/mermade/aws2openapi'
    x-twitter: PermittedSoc
  description: >-
    <p>Welcome to the Amazon Route 53 Application Recovery Controller API
    Reference Guide for Recovery Control Data Plane .</p> <p>Recovery control in
    Route 53 Application Recovery Controller includes extremely reliable routing
    controls that enable you to recover applications by rerouting traffic, for
    example, across Availability Zones or AWS Regions. Routing controls are
    simple on/off switches hosted on a cluster. A cluster is a set of five
    redundant regional endpoints against which you can execute API calls to
    update or get the state of routing controls. You use routing controls to
    failover traffic to recover your application across Availability Zones or
    Regions.</p> <p>This API guide includes information about how to get and
    update routing control states in Route 53 Application Recovery
    Controller.</p> <p>For more information about Route 53 Application Recovery
    Controller, see the following:</p> <ul> <li> <p>You can create clusters,
    routing controls, and control panels by using the control plane API for
    Recovery Control. For more information, see <a
    href="https://docs.aws.amazon.com/recovery-cluster/latest/api/">Amazon Route
    53 Application Recovery Controller Recovery Control API Reference</a>.</p>
    </li> <li> <p>Route 53 Application Recovery Controller also provides
    continuous readiness checks to ensure that your applications are scaled to
    handle failover traffic. For more information about the related API actions,
    see <a
    href="https://docs.aws.amazon.com/recovery-readiness/latest/api/">Amazon
    Route 53 Application Recovery Controller Recovery Readiness API
    Reference</a>.</p> </li> <li> <p>For more information about creating
    resilient applications and preparing for recovery readiness with Route 53
    Application Recovery Controller, see the <a
    href="r53recovery/latest/dg/">Amazon Route 53 Application Recovery
    Controller Developer Guide</a>.</p> </li> </ul>
  license:
    name: Apache 2.0 License
    url: 'http://www.apache.org/licenses/'
  termsOfService: 'https://aws.amazon.com/service-terms/'
  title: Route53 Recovery Cluster
  version: '2019-12-02'
  x-apiClientRegistration:
    url: >-
      https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-aws-signingName: route53-recovery-cluster
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://twitter.com/awscloud/profile_image?size=original'
  x-origin:
    - contentType: application/json
      converter:
        url: 'https://github.com/mermade/aws2openapi'
        version: 1.0.0
      url: >-
        https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/route53-recovery-cluster-2019-12-02.normal.json
      x-apisguru-driver: external
  x-preferred: true
  x-providerName: amazonaws.com
  x-release: v4
  x-serviceName: route53-recovery-cluster
paths:
  /#X-Amz-Target=ToggleCustomerAPI.GetRoutingControlState:
    parameters:
      - in: header
        name: X-Amz-Content-Sha256
        required: false
        type: string
      - in: header
        name: X-Amz-Date
        required: false
        type: string
      - in: header
        name: X-Amz-Algorithm
        required: false
        type: string
      - in: header
        name: X-Amz-Credential
        required: false
        type: string
      - in: header
        name: X-Amz-Security-Token
        required: false
        type: string
      - in: header
        name: X-Amz-Signature
        required: false
        type: string
      - in: header
        name: X-Amz-SignedHeaders
        required: false
        type: string
    post:
      consumes:
        - application/json
      description: >-
        <p>Get the state for a routing control. A routing control is a simple
        on/off switch that you can use to route traffic to cells. When the state
        is On, traffic flows to a cell. When it's off, traffic does not flow.
        </p> <p>Before you can create a routing control, you first must create a
        cluster to host the control. For more information, see <a
        href="https://docs.aws.amazon.com/recovery-cluster/latest/api/cluster.html">CreateCluster</a>.
        Access one of the endpoints for the cluster to get or update the routing
        control state to redirect traffic.</p> <p>For more information about
        working with routing controls, see <a
        href="https://docs.aws.amazon.com/r53recovery/latest/dg/routing-control.html">Routing
        control</a> in the Route 53 Application Recovery Controller Developer
        Guide.</p>
      operationId: GetRoutingControlState
      parameters:
        - enum:
            - ToggleCustomerAPI.GetRoutingControlState
          in: header
          name: X-Amz-Target
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/GetRoutingControlStateRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GetRoutingControlStateResponse'
        '480':
          description: AccessDeniedException
          schema:
            $ref: '#/definitions/AccessDeniedException'
        '481':
          description: InternalServerException
          schema:
            $ref: '#/definitions/InternalServerException'
        '482':
          description: ResourceNotFoundException
          schema:
            $ref: '#/definitions/ResourceNotFoundException'
        '483':
          description: ValidationException
          schema:
            $ref: '#/definitions/ValidationException'
        '484':
          description: ThrottlingException
          schema:
            $ref: '#/definitions/ThrottlingException'
        '485':
          description: EndpointTemporarilyUnavailableException
          schema:
            $ref: '#/definitions/EndpointTemporarilyUnavailableException'
  /#X-Amz-Target=ToggleCustomerAPI.UpdateRoutingControlState:
    parameters:
      - in: header
        name: X-Amz-Content-Sha256
        required: false
        type: string
      - in: header
        name: X-Amz-Date
        required: false
        type: string
      - in: header
        name: X-Amz-Algorithm
        required: false
        type: string
      - in: header
        name: X-Amz-Credential
        required: false
        type: string
      - in: header
        name: X-Amz-Security-Token
        required: false
        type: string
      - in: header
        name: X-Amz-Signature
        required: false
        type: string
      - in: header
        name: X-Amz-SignedHeaders
        required: false
        type: string
    post:
      consumes:
        - application/json
      description: >-
        <p>Set the state of the routing control to reroute traffic. You can set
        the value to be On or Off. When the state is On, traffic flows to a
        cell. When it's off, traffic does not flow.</p> <p>For more information
        about working with routing controls, see <a
        href="https://docs.aws.amazon.com/r53recovery/latest/dg/routing-control.html">Routing
        control</a> in the Route 53 Application Recovery Controller Developer
        Guide.</p>
      operationId: UpdateRoutingControlState
      parameters:
        - enum:
            - ToggleCustomerAPI.UpdateRoutingControlState
          in: header
          name: X-Amz-Target
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UpdateRoutingControlStateRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/UpdateRoutingControlStateResponse'
        '480':
          description: AccessDeniedException
          schema:
            $ref: '#/definitions/AccessDeniedException'
        '481':
          description: InternalServerException
          schema:
            $ref: '#/definitions/InternalServerException'
        '482':
          description: ResourceNotFoundException
          schema:
            $ref: '#/definitions/ResourceNotFoundException'
        '483':
          description: ValidationException
          schema:
            $ref: '#/definitions/ValidationException'
        '484':
          description: ThrottlingException
          schema:
            $ref: '#/definitions/ThrottlingException'
        '485':
          description: EndpointTemporarilyUnavailableException
          schema:
            $ref: '#/definitions/EndpointTemporarilyUnavailableException'
        '486':
          description: ConflictException
          schema:
            $ref: '#/definitions/ConflictException'
  /#X-Amz-Target=ToggleCustomerAPI.UpdateRoutingControlStates:
    parameters:
      - in: header
        name: X-Amz-Content-Sha256
        required: false
        type: string
      - in: header
        name: X-Amz-Date
        required: false
        type: string
      - in: header
        name: X-Amz-Algorithm
        required: false
        type: string
      - in: header
        name: X-Amz-Credential
        required: false
        type: string
      - in: header
        name: X-Amz-Security-Token
        required: false
        type: string
      - in: header
        name: X-Amz-Signature
        required: false
        type: string
      - in: header
        name: X-Amz-SignedHeaders
        required: false
        type: string
    post:
      consumes:
        - application/json
      description: >-
        <p>Set multiple routing control states. You can set the value for each
        state to be On or Off. When the state is On, traffic flows to a cell.
        When it's off, traffic does not flow.</p> <p>For more information about
        working with routing controls, see <a
        href="https://docs.aws.amazon.com/r53recovery/latest/dg/routing-control.html">Routing
        control</a> in the Route 53 Application Recovery Controller Developer
        Guide.</p>
      operationId: UpdateRoutingControlStates
      parameters:
        - enum:
            - ToggleCustomerAPI.UpdateRoutingControlStates
          in: header
          name: X-Amz-Target
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UpdateRoutingControlStatesRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/UpdateRoutingControlStatesResponse'
        '480':
          description: AccessDeniedException
          schema:
            $ref: '#/definitions/AccessDeniedException'
        '481':
          description: InternalServerException
          schema:
            $ref: '#/definitions/InternalServerException'
        '482':
          description: ResourceNotFoundException
          schema:
            $ref: '#/definitions/ResourceNotFoundException'
        '483':
          description: ValidationException
          schema:
            $ref: '#/definitions/ValidationException'
        '484':
          description: ThrottlingException
          schema:
            $ref: '#/definitions/ThrottlingException'
        '485':
          description: EndpointTemporarilyUnavailableException
          schema:
            $ref: '#/definitions/EndpointTemporarilyUnavailableException'
        '486':
          description: ConflictException
          schema:
            $ref: '#/definitions/ConflictException'
schemes:
  - http
security:
  - hmac: []
securityDefinitions:
  hmac:
    description: Amazon Signature authorization v4
    in: header
    name: Authorization
    type: apiKey
    x-amazon-apigateway-authtype: awsSigv4
swagger: '2.0'
x-components:
  parameters:
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      type: string
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      type: string
x-hasEquivalentPaths: true

