basePath: /
definitions:
  Address_AutoComplete: {}
  Caller_ID: {}
  Contact_Enrichment: {}
  Email_ID: {}
  ID_Verification: {}
host: api.peoplefinderspro.com
info:
  description: >-
    Self Service Developer API documentation and demo.


    ##Getting Started


    You will need an API access profile user and password in order to access
    search endpoints.

    Your access profile user and password is used for authenticating all
    requests to our search API. 

    You MUST pass the user and password each time you perform a search request.
  title: Self Service Developer API
  version: 1.0.0
  x-apisguru-categories:
    - marketing
  x-origin:
    - format: swagger
      url: 'https://pfent1821.docs.apiary.io/api-description-document'
      version: '2.0'
  x-providerName: peoplefinderspro.com
paths:
  /address/autocomplete:
    post:
      consumes:
        - application/json
      description: >-
        ###### *Click on the grey search box above, to view sample
        request/response objects for Address Autocomplete Search*


        Perform a search:


        1. Add your key and key secret to the request headers.
            + galaxy-ap-name: [Key]
            + galaxy-ap-password: [Secret]
            + galaxy-search-type: DevAPIAddressAutoComplete

        2.  Add search criteria to your request.
            ~~~html
                    {
                        "Input":"1821 Q"
                    }
            ~~~

        3.  Submit your search


        The JSON request should have parts of the address.


        + <code>Input</code> = null (optional, string) ... address.
      parameters:
        - description: e.g. Key
          in: header
          name: galaxy-ap-name
          required: false
          type: string
          x-example: Key
        - description: e.g. Secret
          in: header
          name: galaxy-ap-password
          required: false
          type: string
          x-example: Secret
        - description: e.g. DevAPIAddressAutoComplete
          in: header
          name: galaxy-search-type
          required: false
          type: string
          x-example: DevAPIAddressAutoComplete
        - in: body
          name: body
          schema:
            example:
              Input: 1821 Q
            properties:
              Input:
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
          headers: {}
      summary: Search
      tags: []
  /contact/enrich:
    post:
      consumes:
        - application/json
      description: >-
        ###### *Click on the grey search box above, to view sample
        request/response objects for Contact Enrichment Search*


        Perform a search:


        1. Add your key and key secret to the request headers.
            + galaxy-ap-name: [Key]
            + galaxy-ap-password: [Secret]
            + galaxy-search-type: DevAPIContactEnrich

        2.  Add search criteria to your request. At least two are required:
        Name, Phone, Address, or Email.
            ~~~html
                    {
                        "FirstName": "John",
                        "MiddleName": "T",
                        "LastName": "Lawrence",
                        "Dob":"",
                        "Age": 0,
                        "Address": {
                            "addressLine1":"123 Q Street",
                            "addressLine2":"Sacramento, CA"
                        },
                        "PhoneNumber":"",
                        "Email":""
                    }
            ~~~

        3.  Submit your search


        A complete list of JSON request properties follows.


        + <code>FirstName</code>= null (optional, string) ... First name.


        + <code>MiddleName</code> = null (optional, string) ... Middle name or
        middle initial.


        + <code>LastName</code> = null (optional, string) ... Last name.


        + <code>Dob</code> = null (optional, string) ... Date of birth (format:
        MM/DD/YYYY).


        + <code>Age</code> = null (optional, int) ... Age.


        + <code>Addresses</code> = null (optional, Addresses[]) ... List of
        addresses.
            + <code>Members</code>
                + <code>AddressLine1</code> = null (optional, string) ... House number, street name and Unit number (i.e. 123 Q Street, Unit 102) or PO Box (i.e. 1821 Q Street).
                + <code>AddressLine2</code> = null (optional, string) ... State or City and State or Zip (i.e. Sacramento, CA).

        + <code>Phone</code> = null (optional, string) ... Phone number
        (formats: ###-###-####, (###) ###-####).


        + <code>Email</code> = null (optional, string) ... E-mail address.
      parameters:
        - description: e.g. Key
          in: header
          name: galaxy-ap-name
          required: false
          type: string
          x-example: Key
        - description: e.g. Secret
          in: header
          name: galaxy-ap-password
          required: false
          type: string
          x-example: Secret
        - description: e.g. DevAPIContactEnrich
          in: header
          name: galaxy-search-type
          required: false
          type: string
          x-example: DevAPIContactEnrich
        - in: body
          name: body
          schema:
            example:
              Address:
                addressLine1: ''
                addressLine2: ''
              Age: 0
              Dob: ''
              Email: ''
              FirstName: ''
              LastName: ''
              MiddleName: ''
              PhoneNumber: ''
            properties:
              Address:
                properties:
                  addressLine1:
                    type: string
                  addressLine2:
                    type: string
                type: object
              Age:
                type: number
              Dob:
                type: string
              Email:
                type: string
              FirstName:
                type: string
              LastName:
                type: string
              MiddleName:
                type: string
              PhoneNumber:
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
          headers: {}
      summary: Search
      tags: []
  /email/enrich:
    post:
      consumes:
        - application/json
      description: >-
        ###### *Click on the grey search box above, to view sample
        request/response objects for Email Enrichment Search*


        Perform a search:


        1. Add your Access Profile username and password to the request headers.
            + galaxy-ap-name: [Key]
            + galaxy-ap-password: [Secret]
            + galaxy-search-type: DevAPIEmailID

        2.  Add search criteria to your request.
            ~~~html
                    {
                        "Email":"johnsmith@somedomain"
                    }
            ~~~

        3.  Submit your search


        The JSON request should have an email.


        + <code>Email</code> = null (optional, string) ... E-mail address.
      parameters:
        - description: e.g. Key
          in: header
          name: galaxy-ap-name
          required: false
          type: string
          x-example: Key
        - description: e.g. Secret
          in: header
          name: galaxy-ap-password
          required: false
          type: string
          x-example: Secret
        - description: e.g. DevAPIEmailID
          in: header
          name: galaxy-search-type
          required: false
          type: string
          x-example: DevAPIEmailID
        - in: body
          name: body
          schema:
            example:
              Email: ''
            properties:
              Email:
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
          headers: {}
      summary: Search
      tags: []
  /identity/verify_id:
    post:
      consumes:
        - application/json
      description: >-
        ###### *Click on the grey search box above, to view sample
        request/response objects for the Identity Verification Search*


        Perform a search:


        1. Add your key and key secret to the request headers.
            + galaxy-ap-name: [Key]
            + galaxy-ap-password: [Secret]
            + galaxy-search-type: DevAPIIDVerification

        2.  Add search criteria to your request. At least two are required: SSN,
        Name, Phone, Address or Email.
            ~~~html
                    {
                        "FirstName": "John",
                        "MiddleName": "T",
                        "LastName": "Lawrence",
                        "Dob":"",
                        "Age": 0,
                        "Address": {
                            "addressLine1":"123 Q Street, Unit 102",
                            "addressLine2":"Sacramento, CA"
                        },
                        "PhoneNumber":"",
                        "Email":""
                    }
            ~~~

        3.  Submit your search


        A complete list of JSON request properties follows.


        + <code>FirstName</code>= null (optional, string) ... First name.


        + <code>MiddleName</code> = null (optional, string) ... Middle name or
        middle initial.


        + <code>LastName</code> = null (optional, string) ... Last name.


        + <code>Dob</code> = null (optional, string) ... Date of birth (format:
        MM/DD/YYYY).


        + <code>Age</code> = null (optional, int) ... Age.


        + <code>Addresses</code> = null (optional, Addresses[]) ... List of
        addresses.
            + <code>Members</code>
                + <code>AddressLine1</code> = null (optional, string) ... House number, street name and Unit number (i.e. 123 Q Street, Unit 102) or PO Box (i.e. 1821 Q Street).
                + <code>AddressLine2</code> = null (optional, string) ... State or City and State or Zip (i.e. Sacramento, CA).

        + <code>Phone</code> = null (optional, string) ... Phone number
        (formats: ###-###-####, (###) ###-####).


        + <code>Email</code> = null (optional, string) ... E-mail address.
      operationId: Search
      parameters:
        - description: e.g. Key
          in: header
          name: galaxy-ap-name
          required: false
          type: string
          x-example: Key
        - description: e.g. Secret
          in: header
          name: galaxy-ap-password
          required: false
          type: string
          x-example: Secret
        - description: e.g. DevAPIIDVerification
          in: header
          name: galaxy-search-type
          required: false
          type: string
          x-example: DevAPIIDVerification
        - in: body
          name: body
          schema:
            example:
              Address:
                addressLine1: ''
                addressLine2: ''
              Age: 0
              Dob: ''
              Email: ''
              FirstName: ''
              LastName: ''
              MiddleName: ''
              PhoneNumber: ''
            properties:
              Address:
                properties:
                  addressLine1:
                    type: string
                  addressLine2:
                    type: string
                type: object
              Age:
                type: number
              Dob:
                type: string
              Email:
                type: string
              FirstName:
                type: string
              LastName:
                type: string
              MiddleName:
                type: string
              PhoneNumber:
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
          headers: {}
      summary: Search
      tags: []
  /phone/enrich:
    post:
      consumes:
        - application/json
      description: >-
        ###### *Click on the grey search box above, to view sample
        request/response objects for Phone Enrichment Search*


        Perform a search:


        1. Add your key and key secret to the request headers.
            + galaxy-ap-name: [Key]
            + galaxy-ap-password: [Secret]
            + galaxy-search-type: DevAPICallerID

        2.  Add search criteria to your request.
            ~~~html
                    {
                        "Phone":"(123) 456-7890"
                    }
            ~~~

        3.  Submit your search


        The JSON request should have a phone number.


        + <code>Phone</code> = null (optional, string) ... Phone number
        (formats: ###-###-####, (###) ###-####).
      parameters:
        - description: e.g. Key
          in: header
          name: galaxy-ap-name
          required: false
          type: string
          x-example: Key
        - description: e.g. Secret
          in: header
          name: galaxy-ap-password
          required: false
          type: string
          x-example: Secret
        - description: e.g. DevAPICallerID
          in: header
          name: galaxy-search-type
          required: false
          type: string
          x-example: DevAPICallerID
        - in: body
          name: body
          schema:
            example:
              Phone: ''
            properties:
              Phone:
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
          headers: {}
      summary: Search
      tags: []
schemes:
  - https
swagger: '2.0'
tags: []
x-components:
  requestBodies:
    SearchBody:
      content:
        application/json:
          schema:
            example:
              Address:
                addressLine1: ''
                addressLine2: ''
              Age: 0
              Dob: ''
              Email: ''
              FirstName: ''
              LastName: ''
              MiddleName: ''
              PhoneNumber: ''
            properties:
              Address:
                properties:
                  addressLine1:
                    type: string
                  addressLine2:
                    type: string
                type: object
              Age:
                type: number
              Dob:
                type: string
              Email:
                type: string
              FirstName:
                type: string
              LastName:
                type: string
              MiddleName:
                type: string
              PhoneNumber:
                type: string
            type: object

